/**
 * Registry behind the blog index (app/blog/page-client.tsx).
 *
 * The index used to be a hand-typed copy of post data that drifted: it omitted dozens of
 * posts, was not date-sorted, and showed read times nobody had measured. It now reads this
 * one list. `lib/blog-posts.test.ts` renders every app/blog/<slug>/page.tsx and fails when
 * an entry disagrees with its page (title, description, date, category, read time), when an
 * indexable post is missing here, or when a noindex post is still listed. So adding a post
 * means adding one entry; retiring one (noindex) means deleting its entry.
 *
 * `readMinutes` is the number the post's own byline shows (same word count, same
 * readingTimeMinutes()). Hand-built pages without a byline leave it out rather than guess.
 */
export type BlogPostEntry = {
  slug: string
  title: string
  excerpt: string
  /** ISO date, YYYY-MM-DD. */
  published: string
  category: string
  /** Card image under /public. Defaults to the shared office photo. */
  image?: string
  readMinutes?: number
  /** Cities the post covers, for the index city filter. */
  cities?: readonly string[]
}

/**
 * Page categories that the index folds into a sibling so the filter list stays short
 * ("Mortgage" and "Mortgages" are one topic). Applied when comparing to the page.
 */
export const BLOG_INDEX_CATEGORY_ALIASES: Readonly<Record<string, string>> = {
  Mortgage: "Mortgages",
  Investing: "Investment",
}

export const DEFAULT_BLOG_IMAGE = "/modern-office-building.png"

const BLOG_POSTS: readonly BlogPostEntry[] = [
  {
    slug: "appraisal-comes-in-low",
    title: "When the Appraisal Comes In Low",
    excerpt: "Lenders size the loan from the lower of price or appraised value. That turns an appraisal gap into cash, a renegotiation, or a cancellation, and all of it runs on a deadline.",
    published: "2026-09-17",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "credit-before-mortgage-rapid-rescore",
    title: "Credit Before a Mortgage: What a Rapid Rescore Is and Is Not",
    excerpt: "A rescore speeds up reporting of something already true. It does not remove accurate information. What actually moves a score during a loan file, and what stalls one.",
    published: "2026-09-17",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "divorce-and-the-mortgage",
    title: "Divorce and the Mortgage: Assume, Refinance, or Sell",
    excerpt: "A decree allocates responsibility between two people. It does not remove either from the note. What actually separates a mortgage, and what each path requires.",
    published: "2026-09-17",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "home-inspection-vs-appraisal",
    title: "Home Inspection vs Appraisal: Two Reports, Two Audiences",
    excerpt: "An inspection is your condition report. An appraisal is the lender's opinion of value. They run on separate Utah deadlines and neither substitutes for the other.",
    published: "2026-09-17",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "how-fha-loan-assumption-works",
    title: "How an FHA Loan Assumption Actually Works",
    excerpt: "Assuming an FHA loan transfers the existing rate and balance to the buyer. You still qualify, you still cover the equity gap, and the mortgage insurance travels with the loan.",
    published: "2026-09-17",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 6,
  },
  {
    slug: "seller-concessions-what-they-cover",
    title: "Seller Concessions: What They Can and Cannot Pay For",
    excerpt: "A seller credit can cover closing costs, prepaids, and a rate buydown, but not the down payment. Every program caps the amount, and the cap depends on the file.",
    published: "2026-09-17",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "va-loan-assumption-entitlement",
    title: "VA Loan Assumption and What Happens to Entitlement",
    excerpt: "A VA loan can often be assumed, but the seller's entitlement stays tied up unless an eligible buyer substitutes theirs and the VA approves a release of liability.",
    published: "2026-09-17",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 5,
  },
  {
    slug: "types-of-basements",
    title: "Types of Basements: What Each One Means for Your Home",
    excerpt: "Full, partial, walkout, walk-up, daylight, and crawlspace. Six basement types explained, including the egress rule that decides if a basement room is a legal bedroom.",
    published: "2026-09-13",
    category: "Buying Guide",
    image: "/suburban-house-garden.webp",
    readMinutes: 4,
  },
  {
    slug: "1099-mortgage-documentation-checklist",
    title: "1099 Mortgage Documentation Checklist",
    excerpt: "What contract and gig workers typically gather for a mortgage: returns, transcripts, YTD P&L, statements, and contracts.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "apr-vs-rate-on-a-loan-estimate",
    title: "APR vs Rate on a Loan Estimate",
    excerpt: "The note rate prices principal and interest. APR folds in most lender prepaid finance charges. Not a live-rate table.",
    published: "2026-08-29",
    category: "Mortgages",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "arm-caps-in-plain-english",
    title: "ARM Caps in Plain English",
    excerpt: "Initial, periodic, and lifetime caps are percentage-point limits on the note rate. They are not a payment promise.",
    published: "2026-08-29",
    category: "Mortgages",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "asset-depletion-qualifying-non-qm",
    title: "Asset-Depletion Qualifying: Retirement and Investment Assets",
    excerpt: "Eligible assets can be treated as qualifying income under a written formula. Agency and Non-QM paths differ. Not “cash means approved.”",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "authorized-user-tradelines-mortgage",
    title: "Authorized User Tradelines: Help or Overlay Risk",
    excerpt: "What authorized-user tradelines do and do not do on a mortgage tri-merge, and why they are not a shortcut to a higher score.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "bank-statement-loans-when-tax-returns-undercount-income",
    title: "Bank-Statement Loans When Tax Returns Undercount Income",
    excerpt: "When write-offs shrink taxable income, some Non-QM programs look at bank deposits. Who they are for, what they cost, and what they are not.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "biweekly-extra-principal-vs-refinance",
    title: "Biweekly Extra Principal vs Refinance",
    excerpt: "One extra payment a year versus changing the note. This page illustrates the idea and does not quote interest saved.",
    published: "2026-08-29",
    category: "Refinance",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "business-vs-personal-bank-co-mingling",
    title: "Business Bank vs Personal: Co-Mingling That Stalls Files",
    excerpt: "Business deposits in a personal account stall sourcing and deposit averages. Seasoning is a paper trail, not a workaround.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "can-i-get-a-mortgage-if-my-income-changes-every-month",
    title: "Can I Get a Mortgage If My Income Changes Every Month?",
    excerpt: "Yes, if you can document a pattern. Underwriters typically average 12–24 months of variable income rather than last month’s paycheck.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "cash-out-to-buy-a-rental",
    title: "Cash-Out to Buy a Rental: Occupancy and LTV Traps",
    excerpt: "Cash-out on the home you occupy is one occupancy and LTV. The rental you buy with the proceeds is another.",
    published: "2026-08-29",
    category: "Refinance",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "closing-credit-card-before-mortgage",
    title: "Closing a Credit Card Before You Apply",
    excerpt: "Closing a card can raise utilization by shrinking available credit. AUS reads the tri-merge. Not a score-raise method.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "commission-income-mortgage-averaging",
    title: "Commission-Only Sales: Averaging and a Down Year",
    excerpt: "Commission income is typically averaged, and a down year usually counts. How 12- vs 24-month averages work.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "compensating-factors-in-aus-findings",
    title: "Compensating Factors That Appear in Findings",
    excerpt: "Reserves, residual income, and other strengths that show up in AUS or manual underwriting. Not a guarantee that findings will flip.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "cosign-vs-co-borrower",
    title: "Cosign vs Co-Borrower",
    excerpt: "Who is on the note, who is on title, and who is only helping with credit, and what each role means for the loan.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "cpa-letter-vs-tax-returns-underwriting",
    title: "CPA Letter vs Tax Returns: What Actually Moves Underwriting",
    excerpt: "Agency self-employed files are usually moved by returns and transcripts. A CPA letter supports; it does not replace the stack.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "cross-collateral-equity-to-buy-another-house",
    title: "Cross-Collateral and Using Equity to Buy Another House",
    excerpt: "Pledging more than one property versus cash-out or a HELOC. Educational only; this is not a published product you can assume.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "declined-after-pre-approval",
    title: "Declined After Pre-Approval: Typical Condition Fails",
    excerpt: "A pre-approval is not a commitment to lend. Job changes, large deposits, new debt, and income that will not average are the usual late fails.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "delayed-financing-after-cash-purchase",
    title: "Delayed Financing After a Cash Purchase",
    excerpt: "Agency delayed-financing exception: cash purchase, then a cash-out later. Overlay is not a statute.",
    published: "2026-08-29",
    category: "Refinance",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "depreciation-add-back-schedule-e",
    title: "Depreciation Add-Back: What Agency Files Allow",
    excerpt: "How underwriters add depreciation back on Schedule E for rental qualifying. Distinct from the Schedule E overview. Not tax advice.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "discount-points-breakeven-without-sales-pitch",
    title: "Discount Points: Breakeven Without a Sales Pitch",
    excerpt: "One point is typically 1% of the loan to lower the note. Break-even is cost divided by monthly P&I savings. This is not a temporary buydown.",
    published: "2026-08-29",
    category: "Mortgages",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "dpa-stacked-with-fha-gift-funds",
    title: "UHC / DPA Stacked with an FHA Gift: How They Work Together",
    excerpt: "Down payment assistance is often a second lien. A gift is not. Stacking them on FHA is common and still has paper-trail and agency rules.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "dscr-vs-full-doc-rental-loan",
    title: "DSCR vs Full-Doc Rental Loan",
    excerpt: "DSCR qualifies on rent versus the payment. Full-doc qualifies the borrower. Occupancy and documents differ.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "dti-frontend-backend-with-hoa",
    title: "DTI: Front-End vs Back-End with HOA",
    excerpt: "HOA dues are housing expense in front-end DTI, then roll into back-end with other debts. A modest PITI plus a large HOA can still fail the ratio.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "earnest-money-vs-down-payment-vs-closing-costs",
    title: "Earnest Money vs Down Payment vs Closing Costs",
    excerpt: "Three different cash lines. Earnest money is usually credited at closing. Timing and the Utah REPC still matter. Not legal advice.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "escrow-cushion-how-it-is-set",
    title: "Escrow: How the Cushion Is Set, Why It Changes",
    excerpt: "RESPA aggregate analysis generally caps the cushion at about two months of disbursements. Servicers may require less. Not a universal formula.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "escrow-shortage-after-first-year",
    title: "Escrow Shortage After the First Year",
    excerpt: "How a shortage appears on the first annual analysis, and typical options to pay or spread. Not tax advice.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "fha-condo-roster-project-approval",
    title: "FHA Condo Roster / Project Approval",
    excerpt: "Look up the project on HUD’s condominium list before you write an FHA offer. Expired approval is not current approval.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "fha-va-streamline-refinance-less-docs",
    title: "Streamline Refi: What “Less Docs” Still Requires",
    excerpt: "FHA Streamline and VA IRRRL reduce documentation. Occupancy, payment history, and a net-benefit test still apply.",
    published: "2026-08-29",
    category: "Refinance",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "first-mortgage-statement-vs-note-rate",
    title: "First Mortgage Statement vs Note Rate",
    excerpt: "The first statement is usually PITI and odd-days timing, not a rate change. Not tax advice.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "first-rental-occupancy-if-you-still-live-there",
    title: "First Rental: Occupancy If You Still Live in Your Home",
    excerpt: "If you keep occupying your current home, the rental you buy is typically investment occupancy. Distinct from a duplex house-hack.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "first-time-buyer-file-mistakes",
    title: "First-Time Buyer Mistakes That Are Really File Mistakes",
    excerpt: "New debt, a job change, large deposits, and occupancy changes are the common reasons underwriting stalls for first-time buyers.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "gift-funds-down-payment-rules",
    title: "Gift Funds for a Down Payment: What Lenders Need to See",
    excerpt: "Gift letters, paper trails, and program differences for FHA, conventional, and VA. Family help is common. Undocumented cash is not.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "gig-plus-w2-income-mortgage-average",
    title: "Gig Plus W-2 Mix: How the Average Is Built",
    excerpt: "Gig or 1099 income and W-2 wages are usually averaged as separate streams, then added. A peak gig month is not the qualifying method.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "hazard-vs-ho3-vs-ho6-condo-insurance",
    title: "Hazard vs HO-3 vs HO-6",
    excerpt: "What lenders mean by hazard insurance, when an HO-3 fits a house, and when a condo needs an HO-6 plus the master. Not insurance advice.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "heloc-after-year-two-vs-cash-out",
    title: "HELOC After Year Two vs Cash-Out",
    excerpt: "When you can tap equity after a recent closing, and how seasoning rules affect a HELOC or a cash-out refinance.",
    published: "2026-08-29",
    category: "Refinance",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "heloc-vs-cash-out-refinance",
    title: "Cash-Out vs HELOC: Payment, Lien Position, and Tax Questions",
    excerpt: "A cash-out refinance replaces the first lien. A HELOC sits in second position. Payment, rate risk, and tax questions differ. Not tax advice.",
    published: "2026-08-29",
    category: "Refinance",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "hill-afb-va-coe-occupancy",
    title: "Hill AFB / VA: Certificate of Eligibility and Occupancy",
    excerpt: "Hill Air Force Base is in Davis County, Utah. How the VA Certificate of Eligibility and occupancy rules apply to a purchase near the base. Occupancy must match use.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "house-hacking-duplex-with-fha",
    title: "House-Hacking a Duplex with FHA",
    excerpt: "FHA can finance a 2–4 unit if you occupy one unit as your home. Self-sufficiency is a 3–4 unit test, not a duplex test.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "how-long-first-purchase-takes",
    title: "How Long a First Purchase Usually Takes",
    excerpt: "Pre-approval through contract, underwriting, CTC, and funding. Ranges, not a closing-date promise.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "how-underwriters-verify-income",
    title: "How Underwriters Verify Income (W-2 vs 1099 vs Bank)",
    excerpt: "W-2, 1099, and bank-statement files are verified differently: paystubs and VOE vs returns and transcripts vs deposits.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "impounds-vs-waiving-escrow",
    title: "Impounds vs Waiving Escrow",
    excerpt: "Waiver is an overlay, not a right. Cash-to-close versus monthly draft. Not a promise you can waive.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "interest-only-mortgages-who-they-are-for",
    title: "Interest-Only Mortgages: Who They Are For, Who They Hurt",
    excerpt: "IO skips scheduled principal for a stated period. Payment shock is the risk. Not a teaser-rate promise.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "itin-non-us-citizen-mortgage-documentation",
    title: "ITIN / Non-U.S. Citizen Mortgage Documentation",
    excerpt: "What lenders typically document for ITIN and lawful-presence files. Citizenship is a legal eligibility topic, not a national-origin preference.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "jumbo-vs-conforming-fhfa-county-limit",
    title: "Jumbo vs Conforming: Look Up This Year’s FHFA County Limit",
    excerpt: "A jumbo loan is simply above the FHFA conforming limit for the property county. How to look the limit up without memorizing a stale number.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "just-went-1099-last-month",
    title: "I Just Went 1099 Last Month",
    excerpt: "A brand-new 1099 job is usually not yet a qualifying average. What still counts from W-2 history and when a one-year overlay even enters the chat.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "k-1-income-what-usually-counts",
    title: "K-1 Income: What Usually Counts",
    excerpt: "Partnership and S-corp K-1 income is taken from the form and matching returns, not from distributions alone.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "large-deposits-60-day-paper-trail",
    title: "Large Deposits: 60-Day Paper Trail",
    excerpt: "About 60 days of statements, and large deposits in that window have to be sourced. Cash from family without a gift letter is a common stall.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "manufactured-housing-adu-financing",
    title: "Manufactured Housing and ADU Financing",
    excerpt: "Two property types, two underwrites. Do not collapse them, and confirm the current handbook for your loan program.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "medical-collections-after-fico-model-change",
    title: "Medical Collections After the FICO Model Change",
    excerpt: "Bureau medical-collection reporting changed in 2022–2023. Mortgage files often still use classic FICO. Not a score-raise promise.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "mip-vs-pmi-how-mortgage-insurance-ends",
    title: "How MIP vs PMI Actually Leaves the Loan",
    excerpt: "FHA annual MIP is timed from original LTV. Conventional PMI can often come off with equity. This post covers how each one ends.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "mortgage-reserves-months-of-pitia",
    title: "Mortgage Reserves: How Many Months of PITIA",
    excerpt: "Reserves are remaining liquid assets after cash to close, counted as months of PITIA. Not extra closing costs. Gift funds often cannot fill this line.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "new-auto-loan-during-underwriting",
    title: "New Auto Loan During Underwriting",
    excerpt: "A car payment signed after pre-approval usually shows on the next credit pull and changes DTI. Ask before you sign.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "no-closing-cost-refinance-rate-credit-tradeoff",
    title: "“No Closing Cost” Refinance: The Cost Is in the Rate",
    excerpt: "A lender credit that covers fees is usually paid for with a higher note rate. Run break-even. Not a free refinance.",
    published: "2026-08-29",
    category: "Refinance",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "no-traditional-credit-alternative-credit",
    title: "No Traditional Credit / Alternative Credit",
    excerpt: "Rent and utilities can document a thin file. Weak traditional credit is a different path. Fair Housing safe.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "parent-gifting-down-payment-who-signs",
    title: "Parent Is Gifting: Who Signs What",
    excerpt: "Gift letter, donor statements, occupancy, and title: who signs when a parent helps with down payment.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "pmi-removal-original-value-vs-new-appraisal",
    title: "Removing PMI: Original Value vs New Appraisal",
    excerpt: "HPA cancellation uses original value. A new appraisal of current value is a separate path with its own investor rules.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "pre-approval-vs-aus-vs-clear-to-close",
    title: "Pre-Approval Letter vs AUS Findings vs Clear to Close",
    excerpt: "Three documents, three jobs. A letter is a snapshot, AUS is an engine result, and CTC is an underwriter sign-off. None of them guarantees you will fund.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "rate-lock-extension-vs-floating",
    title: "Rate Lock Extension vs Floating",
    excerpt: "A lock holds a quoted rate for a window. Floating leaves it open. An extension is a cost if you miss the window. Not a live-rate table.",
    published: "2026-08-29",
    category: "Mortgages",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "rate-lock-if-rates-drop",
    title: "What a Lock Does If Rates Drop After You Lock",
    excerpt: "A lock does not automatically follow the market down. Float-down is a written lock-desk policy. Not a live-rate table.",
    published: "2026-08-29",
    category: "Mortgages",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "recast-vs-refinance",
    title: "Recast vs Refinance",
    excerpt: "Recast keeps the rate and re-spreads the payment after a lump sum. Refinance changes the note. Not a savings quote.",
    published: "2026-08-29",
    category: "Refinance",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "refinance-break-even-when-lower-rate-loses",
    title: "When a Lower Rate Still Loses After Costs",
    excerpt: "Break-even months include points and origination, not just the appraisal. A lower note rate can still lose if you move first.",
    published: "2026-08-29",
    category: "Refinance",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "refinancing-condo-aging-hoa",
    title: "Refinancing a Condo with an Aging HOA",
    excerpt: "Project risk, including reserves, litigation, and insurance, can stall a condo refinance.",
    published: "2026-08-29",
    category: "Refinance",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "relocating-to-utah-job-seasoning",
    title: "Relocating to Utah: Income Seasoning for a New Job",
    excerpt: "An offer letter can sometimes qualify a conventional purchase before the first paycheck. Sixty days is not a published Fannie Mae rule.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "schedule-e-rental-income-purchase-file",
    title: "Rental Income on Schedule E in a Purchase File",
    excerpt: "How existing rental income on Schedule E is averaged on a purchase, and why proposed rent is a different calculation.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "second-home-vs-investment-occupancy",
    title: "Second Home vs Investment Occupancy",
    excerpt: "Primary, second home, and investment occupancy are different. Misstating occupancy is fraud, not a strategy.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "selling-with-va-loan-entitlement-restoration",
    title: "Selling with a VA Loan: Entitlement Restoration",
    excerpt: "How VA entitlement is typically restored after you sell and pay off the loan. This differs from keeping a VA loan and buying another.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "should-i-wait-for-20-percent-down",
    title: "Should I Wait for 20% Down?",
    excerpt: "Waiting for 20% can avoid conventional PMI. Buying sooner with PMI is a cash-and-timeline trade-off.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "spouse-w2-offset-1099-volatility",
    title: "Using a Spouse’s W-2 to Offset 1099 Volatility",
    excerpt: "A steadier W-2 helps when that person is a co-borrower. A non-borrowing spouse’s paycheck does not automatically average in. Utah is not a community-property state.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "student-loans-dti-idr-save",
    title: "Student Loans and DTI After IDR / SAVE Changes",
    excerpt: "A $0 student-loan line on a dashboard is not automatically $0 in DTI. How agencies typically count IDR, deferment, and forbearance.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "temporary-buydown-who-pays-year-three",
    title: "Temporary Buydown: Who Pays, What Happens in Year 3",
    excerpt: "2-1 and 3-2-1 buydowns subsidize the payment for a few years. The note rate does not change. Distinct from buying discount points.",
    published: "2026-08-29",
    category: "Mortgages",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "title-insurance-owner-vs-lender",
    title: "Title Insurance: Owner’s vs Lender’s Policy",
    excerpt: "Lender’s policy protects the loan. Owner’s policy protects you. Not legal advice and not a premium quote.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "townhome-vs-condo-hoa-docs-lenders-ask",
    title: "Townhome vs Condo: HOA Docs a Lender Will Ask For",
    excerpt: "Lenders underwrite the legal regime, not the listing photo. Not every townhome is a condo. HOA dues still sit in DTI either way.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "two-years-of-tax-returns-vs-one-year-mortgage",
    title: "Two Years of Tax Returns vs One Year: When Overlays Allow",
    excerpt: "Most agency self-employed files want two years of returns. Some overlays allow one year in the same line of work.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "usda-map-income-limit-eligibility",
    title: "USDA Map and Income Limit: Am I Even Eligible?",
    excerpt: "USDA is address-specific and household-income-specific. How to use the official map and income tools before you assume zero-down is available.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "usda-vs-va-vs-fha-veteran-rural",
    title: "USDA vs VA vs FHA for a Veteran in a Rural Tract",
    excerpt: "Comparison of typical tests when a veteran is buying in a USDA-map area. Not a recommendation to take one program.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "utah-cash-to-close-besides-down-payment",
    title: "How Much Cash Do I Need Besides Down Payment in Utah?",
    excerpt: "Earnest money, title, origination, prepaids, and reserves sit on top of down payment. Utah closings vary by county and title company.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "utah-closing-costs-title-origination-prepaids",
    title: "Closing Costs in Utah: Title, Origination, and Prepaids",
    excerpt: "Utah funds at title companies, uses deeds of trust, and has no statewide transfer tax. Recording, title premiums, and tax calendars still vary by county.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "utah-property-tax-calendar-first-escrow-analysis",
    title: "Utah Property Tax Calendar vs Your First Escrow Analysis",
    excerpt: "Utah taxes are typically due November 30, billed once a year. Why the first mortgage escrow analysis can surprise. Not tax advice.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "utah-repc-deadline-and-your-loan",
    title: "What a Utah REPC Deadline Actually Does to Your Loan",
    excerpt: "Utah due diligence and financing/appraisal are separate 5:00 p.m. Mountain Time clocks. A lender timeline is not a REPC deadline.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "va-entitlement-second-va-loan",
    title: "Can I Use VA If I Still Have a VA Loan?",
    excerpt: "Remaining entitlement, occupancy, and restoration: how a second VA purchase is underwritten when you have not sold the first home.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "va-funding-fee-finance-vs-pay-cash",
    title: "VA Funding Fee: Finance vs Pay Cash",
    excerpt: "Worked examples of financing the VA funding fee versus paying it in cash. Snapshot percents, exemptions, and cash to close. Not advice.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "va-residual-income-vs-dti",
    title: "VA Residual Income vs DTI",
    excerpt: "VA residual income is cash left after PITI and debts. It can fail when DTI looks fine, and pass when DTI looks high.",
    published: "2026-08-29",
    category: "Loan Programs",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "w2-overtime-likely-to-continue",
    title: "Overtime on a W-2: What “Likely to Continue” Means",
    excerpt: "Underwriters usually average overtime over a documented history and ask whether it is likely to continue.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "week-after-mortgage-funding",
    title: "What Happens the Week After Funding",
    excerpt: "Recording, first payment date, and servicing letters. Not legal advice and not a closing-date promise.",
    published: "2026-08-29",
    category: "First-Time Buyers",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "what-a-mortgage-conversation-asks",
    title: "What a Mortgage Conversation Asks and Will Not Promise",
    excerpt: "Occupancy, income type, debts, assets, and credit authorization. A conversation is not approval, a lock, or a quote.",
    published: "2026-08-29",
    category: "Mortgages",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "what-a-tri-merge-credit-report-shows",
    title: "What a Tri-Merge Credit Report Actually Shows",
    excerpt: "Equifax, Experian, and TransUnion together. Mortgage files often use classic FICO and the middle score. Not a consumer-app score.",
    published: "2026-08-29",
    category: "Credit",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "backyard-upgrades-and-fertilizer-guide",
    title: "Backyard Upgrades & Lawn Care: A Seasonal Fertilizer Guide",
    excerpt: "Value-adding backyard projects plus a simple seasonal fertilizer schedule and the common DIY fixes that keep a yard healthy.",
    published: "2026-07-24",
    category: "Home Improvement",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "build-rental-portfolio-investor-2026",
    title: "How to Build a Rental Portfolio as an Investor in 2026",
    excerpt: "A staged playbook for going from one rental to a portfolio: financing, metrics, systems, and when to scale.",
    published: "2026-07-24",
    category: "Investment",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "cash-on-cash-return-explained",
    title: "Cash-on-Cash Return, Explained (with the Math)",
    excerpt: "What cash-on-cash return measures, the exact formula, a worked example, and how it differs from cap rate and CAGR.",
    published: "2026-07-24",
    category: "Finance",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "collect-rent-with-crypto-guide",
    title: "How to Collect Rent Using Crypto: A Landlord's Guide",
    excerpt: "A practical guide to accepting rent in crypto: stablecoins vs volatile assets, tax and record-keeping, and how to keep it low-risk.",
    published: "2026-07-24",
    category: "Payments",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "finishing-basement-roi",
    title: "Finishing a Basement: Costs, Permits & ROI",
    excerpt: "What a finished basement really costs, the permits and egress rules that matter, and how the ROI compares to other projects.",
    published: "2026-07-24",
    category: "Home Improvement",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "home-maintenance-schedule",
    title: "Home Maintenance Schedule: A Monthly & Annual Checklist",
    excerpt: "A complete home-care checklist for homeowners, filters, HVAC, gutters, winterizing, and how ONDO can auto-remind you.",
    published: "2026-07-24",
    category: "Home Care",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "mortgage-paydown-hacks",
    title: "Mortgage Pay-Down Hacks That Actually Save Interest",
    excerpt: "Biweekly payments, extra principal, recasting, and refinancing, which mortgage pay-down tactics really move the needle, and when not to.",
    published: "2026-07-24",
    category: "Finance",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "online-notary-for-lease-agreements",
    title: "Online Notary for Lease Agreements: Landlord Guide",
    excerpt: "When a lease needs notarization, how remote online notarization (RON) works, and what makes it legally sound across states.",
    published: "2026-07-24",
    category: "Notary",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "property-management-calculators-which-one",
    title: "Property Management Calculators: Which One to Use",
    excerpt: "A field guide to the core real-estate calculators (cash-on-cash, cap rate, DSCR, ROI, and more) and exactly when each one earns its keep.",
    published: "2026-07-24",
    category: "Calculators",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "property-management-pwa-offline",
    title: "What Is a PWA? Why Property Apps Should Work Offline",
    excerpt: "How progressive web apps deliver installable, offline-capable property management, and why that matters in the field.",
    published: "2026-07-24",
    category: "Product",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "real-estate-agents-manage-own-rentals",
    title: "Why Real Estate Agents Should Manage Their Own Rentals",
    excerpt: "Agents already have the market data, network, and licensing edge. Here is why self-managing your rentals compounds that advantage.",
    published: "2026-07-24",
    category: "For Agents",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "switch-from-turbotenant-migration-guide",
    title: "How to Switch from TurboTenant: Migration Guide",
    excerpt: "Move off TurboTenant without losing data or disrupting tenants. A checklist for exporting, importing, and cutting over cleanly.",
    published: "2026-07-24",
    category: "Migration",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "tenant-rights-checklist",
    title: "Tenant Rights Checklist: What Every Renter Should Know",
    excerpt: "A practical checklist of core renter protections: deposits, repairs, entry notice, and how to document issues.",
    published: "2026-07-24",
    category: "For Renters",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "turbotenant-vs-buildium-vs-ondo",
    title: "TurboTenant vs Buildium vs Ondo: The Honest Comparison",
    excerpt: "A straight comparison of TurboTenant, Buildium, and Ondo across pricing, features, tenant fees, and who each one actually fits.",
    published: "2026-07-24",
    category: "Comparison",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "ultimate-guide-becoming-utah-landlord-2026",
    title: "The Ultimate Guide to Becoming a Utah Landlord (2026)",
    excerpt: "Everything you need to start, scale, and protect a Utah rental portfolio in 2026, the new state property-management license law, financing, tenant screening, leases, taxes, and when to hand it off.",
    published: "2026-05-18",
    category: "Property Management",
    image: "/modern-office-building.webp",
    readMinutes: 8,
  },
  {
    slug: "best-neighborhoods-draper-utah",
    title: "Best Neighborhoods in Draper, Utah (2026 Guide)",
    excerpt: "A local guide to Draper's top neighborhoods, South Mountain, Suncrest, and Draper Peaks, with home prices, schools, lifestyle, and investment notes.",
    published: "2026-04-06",
    category: "Neighborhood Guide",
    image: "/suburban-house-garden.webp",
    readMinutes: 3,
  },
  {
    slug: "best-neighborhoods-lehi-utah",
    title: "Best Neighborhoods in Lehi, Utah (2026 Guide)",
    excerpt: "Traverse Mountain, Thanksgiving Point, or Lehi Old Town? A local breakdown of Lehi's top neighborhoods with home prices, schools, commute, and investment notes.",
    published: "2026-04-06",
    category: "Neighborhood Guide",
    image: "/modern-townhouse-garage.webp",
    readMinutes: 3,
  },
  {
    slug: "cost-of-living-draper-utah",
    title: "Cost of Living in Draper, Utah (2026)",
    excerpt: "Real numbers on housing, utilities, groceries, taxes, and commute costs in Draper, UT, compared to SLC and the national average.",
    published: "2026-04-06",
    category: "Cost of Living",
    image: "/city-map-with-pin.webp",
    readMinutes: 3,
  },
  {
    slug: "property-management-guide-lehi-investors",
    title: "Lehi, Utah Property Management Guide for Investors (2026)",
    excerpt: "Everything you need to know about managing rental property in Lehi, UT, tenant profiles, pricing, legal requirements, and what a professional PM company handles for you.",
    published: "2026-04-06",
    category: "Property Management",
    image: "/property-manager-meeting.webp",
    readMinutes: 3,
  },
  {
    slug: "renting-vs-buying-salt-lake-city",
    title: "Renting vs. Buying in Salt Lake City (2026 Analysis)",
    excerpt: "Should you rent or buy in Salt Lake City right now? A data-driven breakdown covering break-even timeline, total cost of ownership, and neighborhood-level analysis.",
    published: "2026-04-06",
    category: "Finance",
    image: "/city-map-with-pin.webp",
    readMinutes: 2,
  },
  {
    slug: "best-neighborhoods-invest-utah-real-estate",
    title: "Best Neighborhoods to Invest in Utah Real Estate",
    excerpt: "A data-driven look at the top Utah neighborhoods for real estate investment in 2026, cash flow, appreciation, and rental demand by submarket.",
    published: "2026-03-23",
    category: "Investment",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "fha-vs-conventional-loans-utah",
    title: "FHA vs Conventional Loans in Utah: Which Is Right for You?",
    excerpt: "A side-by-side comparison of FHA and conventional mortgages for Utah home buyers, down payment, PMI, credit requirements, and which loan wins in different scenarios.",
    published: "2026-03-23",
    category: "Mortgages",
    image: "/modern-apartment-balcony.webp",
    readMinutes: 6,
  },
  {
    slug: "first-time-landlord-checklist-utah",
    title: "First-Time Landlord Checklist for a Utah Rental Property",
    excerpt: "A complete checklist for first-time Utah landlords, legal setup, lease structure, tenant screening, move-in procedures, and ongoing management systems.",
    published: "2026-03-23",
    category: "Property Management",
    image: "/modern-townhouse-garage.webp",
    readMinutes: 4,
  },
  {
    slug: "how-ondo-re-uses-technology-property-management",
    title: "How Ondo RE Uses Technology to Manage Utah Rental Properties",
    excerpt: "A behind-the-scenes look at how Ondo RE uses AI, real-time reporting, and automated workflows to deliver better outcomes for Utah property owners and tenants.",
    published: "2026-03-23",
    category: "Technology",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "how-to-choose-property-management-company-utah",
    title: "How to Choose a Property Management Company in Utah",
    excerpt: "A step-by-step guide to evaluating Utah property management companies, fees, services, communication, and red flags to watch for.",
    published: "2026-03-23",
    category: "Property Management",
    image: "/property-manager-meeting.webp",
    readMinutes: 4,
  },
  {
    slug: "property-management-fees-utah",
    title: "Property Management Fees in Utah: What to Expect",
    excerpt: "A transparent breakdown of property management fees in Utah, management rates, leasing fees, maintenance markups, and how to calculate true annual cost.",
    published: "2026-03-23",
    category: "Property Management",
    image: "/property-manager-meeting.webp",
    readMinutes: 4,
  },
  {
    slug: "provo-orem-rental-market-guide",
    title: "Provo and Orem Rental Market Guide: Student Housing",
    excerpt: "A landlord's guide to the Provo and Orem rental market, BYU and UVU demand, seasonal vacancy, rent trends, and what investors should know in 2026.",
    published: "2026-03-23",
    category: "Market Data",
    image: "/modern-apartment-balcony.webp",
    readMinutes: 3,
  },
  {
    slug: "salt-lake-city-rental-market-report",
    title: "Salt Lake City Rental Market Report: Vacancy and Rents",
    excerpt: "A data-driven look at the Salt Lake City rental market in 2026, vacancy rates, average rents by neighborhood, and what landlords should expect.",
    published: "2026-03-23",
    category: "Market Data",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
  {
    slug: "utah-landlord-tenant-law-guide",
    title: "Utah Landlord-Tenant Law: What Property Owners Must Know",
    excerpt: "A practical guide to Utah rental laws in 2026, security deposits, eviction timelines, habitability standards, and Fair Housing requirements.",
    published: "2026-03-23",
    category: "Legal",
    image: "/property-manager-meeting.webp",
    readMinutes: 4,
  },
  {
    slug: "wasatch-front-real-estate-forecast-2026",
    title: "Wasatch Front Real Estate Forecast 2026: What to Watch",
    excerpt: "An outlook for the Wasatch Front real estate market in 2026, interest rates, inventory, rent trends, and strategic positioning for Utah property owners and investors.",
    published: "2026-03-23",
    category: "Market Outlook",
    image: "/modern-office-building.webp",
    readMinutes: 4,
  },
  {
    slug: "building-high-performance-real-estate-nextjs-supabase",
    title: "Building a Real Estate Platform with Next.js and Supabase",
    excerpt: "A technical deep dive into the architecture of Ondo Real Estate, featuring App Router, React Server Components, and Supabase.",
    published: "2025-12-10",
    category: "Engineering",
    image: "/modern-office-building.webp",
  },
  {
    slug: "commercial-real-estate-101-tenant-mix",
    title: "Commercial Real Estate 101: Cap Rates, NNN, and Tenant Mix",
    excerpt: "An operator’s primer on how cap rates, lease structure, and tenant mix shape commercial value and risk.",
    published: "2025-12-10",
    category: "Commercial",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "crypto-and-real-estate-hedge",
    title: "Crypto and Real Estate: Building a Barbell Hedge",
    excerpt: "A practitioner view on using fast/volatile assets and slow/real assets together without magical thinking.",
    published: "2025-12-10",
    category: "Strategy",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "dashboards-for-landlords",
    title: "Dashboards for Landlords: See Patterns, Act Faster",
    excerpt: "What to track, how to visualize it, and why dashboards turn rentals into a real business.",
    published: "2025-12-10",
    category: "Analytics",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "designing-property-owner-portal",
    title: "Designing a Property Owner Portal: Managing Assets at Scale",
    excerpt: "How we built a comprehensive dashboard for landlords to track performance, manage tenants, and organize documents.",
    published: "2025-12-10",
    category: "Product",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "engineering-real-estate-investment-calculators",
    title: "Behind the Scenes of Real Estate Investment Calculators",
    excerpt: "How we built the real estate financial calculators on this site using React and TypeScript.",
    published: "2025-12-10",
    category: "Engineering",
    image: "/modern-townhouse-garage.webp",
  },
  {
    slug: "full-stack-dev-landlord-gaps",
    title: "I’m a Full-Stack Dev and Landlord: What Software Gets Wrong",
    excerpt: "A dual lens on why property software frustrates tenants and owners, and how to design for human workflows.",
    published: "2025-12-10",
    category: "Product",
    image: "/modern-office-building.webp",
    readMinutes: 2,
  },
  {
    slug: "maintenance-capex-strategy",
    title: "Maintenance and CapEx Strategy for Rentals",
    excerpt: "A practical lifecycle and reserve plan to keep NOI stable and assets healthy.",
    published: "2025-12-10",
    category: "Operations",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "new-landlord-mistakes-systems",
    title: "New Landlord Mistakes and the Systems That Prevent Them",
    excerpt: "Evergreen pitfalls, maintenance, documentation, vacancy, and the operational playbooks that stop them.",
    published: "2025-12-10",
    category: "Operations",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "property-management-automation-checklist",
    title: "Property Management Automation Checklist",
    excerpt: "High-ROI automations for rent, maintenance, and owner reporting for small rental portfolios.",
    published: "2025-12-10",
    category: "Operations",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "vacancy-risk-playbook",
    title: "Vacancy Risk Playbook",
    excerpt: "How to model, reduce, and recover from vacancy, including Utah seasonality and leasing tactics.",
    published: "2025-12-10",
    category: "Operations",
    image: "/modern-office-building.webp",
    readMinutes: 1,
  },
  {
    slug: "mobile-notary-utah-county-guide",
    title: "Notary in Utah County: Remote Online Notarization Guide",
    excerpt: "ONDO Notary serves Utah County by Remote Online Notarization (RON), $25 per remote act, same-day when capacity allows. No mobile travel or in-office appointments.",
    published: "2025-01-10",
    category: "Notary",
    image: "/modern-apartment-balcony.webp",
  },
  {
    slug: "prepare-for-remote-online-notary-session",
    title: "Checklist: Prepare for Your Remote Online Notary Session",
    excerpt: "Follow this RON checklist to pass ID verification, avoid rescheduling, and receive sealed documents immediately after your remote online notarization.",
    published: "2025-01-10",
    category: "Notary",
    image: "/modern-office-building.webp",
  },
  {
    slug: "remote-online-notary-all-50-states",
    title: "Remote Online Notary in All 50 States",
    excerpt: "How ONDO Notary delivers secure Remote Online Notarization (RON) across all 50 U.S. states with identity verification, compliant records, and fast scheduling.",
    published: "2025-01-10",
    category: "Notary",
    image: "/modern-office-building.webp",
  },
  {
    slug: "remote-online-notary-real-estate-closings",
    title: "Remote Online Notary for Real Estate Closings",
    excerpt: "Use ONDO Remote Online Notary for purchases, refinances, HELOCs, and investor closings with compliant ID checks, audit trails, and title-ready documents.",
    published: "2025-01-10",
    category: "Notary",
    image: "/modern-townhouse-garage.webp",
  },
  {
    slug: "first-time-home-buyer-guide",
    title: "First-Time Home Buyer Guide: Everything You Need to Know",
    excerpt: "Complete guide to buying your first home in Utah, from pre-approval to closing day.",
    published: "2024-12-10",
    category: "Buying Guide",
    image: "/suburban-house-garden.webp",
    readMinutes: 4,
  },
  {
    slug: "property-management-tips-utah-landlords",
    title: "Property Management Tips for Utah Landlords",
    excerpt: "Essential tips for managing rental properties in Utah's competitive market.",
    published: "2024-12-05",
    category: "Property Management",
    image: "/property-manager-meeting.webp",
    readMinutes: 3,
    cities: ["Salt Lake City", "Lehi", "Provo", "Ogden"],
  },
  {
    slug: "mortgage-rate-trends-2025",
    title: "Mortgage Rates: How They Move and How to Read a Quote",
    excerpt: "What moves 30-year mortgage rates, why a headline average is not your quote, and how to compare Loan Estimates and decide when to lock.",
    published: "2024-11-28",
    category: "Mortgages",
    image: "/modern-townhouse-garage.webp",
    readMinutes: 3,
  },
  {
    slug: "why-utah-best-real-estate-investment",
    title: "Why Utah is the Best Place to Invest in Real Estate",
    excerpt: "Discover why Utah's fundamentals (jobs, population growth, and landlord-friendly policies) make it a top-tier market for real estate investors.",
    published: "2024-11-20",
    category: "Investment",
    image: "/modern-office-building.webp",
    readMinutes: 3,
    cities: ["Salt Lake City", "Draper", "Lehi", "Sandy", "Orem", "Ogden"],
  },
  {
    slug: "home-staging-tips-that-work",
    title: "Home Staging Tips That Actually Work",
    excerpt: "Professional staging tips to help your home sell faster and for more money.",
    published: "2024-11-15",
    category: "Selling",
    image: "/modern-apartment-balcony.webp",
    readMinutes: 3,
  },
  {
    slug: "understanding-property-taxes-utah",
    title: "Understanding Property Taxes in Utah",
    excerpt: "Complete breakdown of Utah property taxes and how they affect your investment.",
    published: "2024-11-08",
    category: "Taxes",
    image: "/modern-office-building.webp",
    readMinutes: 3,
  },
]

/** Every post, newest first (ties broken by slug so the order is stable). */
export function getBlogPosts(): BlogPostEntry[] {
  return [...BLOG_POSTS].sort(
    (a, b) => b.published.localeCompare(a.published) || a.slug.localeCompare(b.slug),
  )
}
