export type CityMarketData = {
  medianHomePrice: number
  medianRent: number
  population: number
  growthRate: string
  avgDaysOnMarket: number
  medianHouseholdIncome: number
  ownerOccupiedPct: number
  topEmployers: string[]
  commuteTimes: { destination: string; minutes: number }[]
  schoolDistrict: string
  notableSchools: string[]
  outdoorRec: string[]
  localLandmarks: string[]
  elevation?: number
  geographyNote?: string
}

export const cityMarketData: Record<string, CityMarketData> = {
  // ──────────────────────────────────────────────
  // WEBER COUNTY
  // ──────────────────────────────────────────────

  "North Ogden": {
    medianHomePrice: 425000,
    medianRent: 1450,
    population: 21000,
    growthRate: "2.1%",
    avgDaysOnMarket: 28,
    medianHouseholdIncome: 82000,
    ownerOccupiedPct: 78,
    topEmployers: ["Weber School District", "McKay-Dee Hospital", "Autoliv"],
    commuteTimes: [
      { destination: "Downtown Ogden", minutes: 10 },
      { destination: "Downtown Salt Lake City", minutes: 50 },
      { destination: "Hill Air Force Base", minutes: 20 },
    ],
    schoolDistrict: "Weber School District",
    notableSchools: ["North Ogden Elementary", "Green Acres Elementary", "North Ogden Junior High"],
    outdoorRec: ["Ben Lomond Peak Trail", "North Fork Park", "Willard Bay State Park"],
    localLandmarks: ["Pleasant Valley Branch Library", "North Ogden Divide trailhead", "Cold Water Canyon"],
    elevation: 4550,
    geographyNote: "Nestled against the western slopes of Ben Lomond Peak with panoramic views of the Great Salt Lake.",
  },

  "Ogden": {
    medianHomePrice: 365000,
    medianRent: 1350,
    population: 87000,
    growthRate: "1.8%",
    avgDaysOnMarket: 22,
    medianHouseholdIncome: 52000,
    ownerOccupiedPct: 55,
    topEmployers: ["IHC Health Services", "Weber State University", "Ogden Regional Medical Center"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 45 },
      { destination: "Hill Air Force Base", minutes: 15 },
      { destination: "Weber State University", minutes: 8 },
    ],
    schoolDistrict: "Ogden School District",
    notableSchools: ["Ogden High School", "Ben Lomond High School", "DaVinci Academy"],
    outdoorRec: ["Ogden River Parkway", "Snowbasin Resort", "Mt. Ogden Golf Course"],
    localLandmarks: ["Historic 25th Street", "Peery's Egyptian Theater", "Union Station Museums"],
    elevation: 4300,
    geographyNote: "Historic railroad city at the confluence of the Ogden and Weber rivers, framed by the Wasatch Range to the east.",
  },

  "South Ogden": {
    medianHomePrice: 385000,
    medianRent: 1400,
    population: 18000,
    growthRate: "1.5%",
    avgDaysOnMarket: 25,
    medianHouseholdIncome: 62000,
    ownerOccupiedPct: 65,
    topEmployers: ["Fresenius Medical Care", "South Ogden City", "Weber School District"],
    commuteTimes: [
      { destination: "Downtown Ogden", minutes: 8 },
      { destination: "Downtown Salt Lake City", minutes: 42 },
      { destination: "Hill Air Force Base", minutes: 12 },
    ],
    schoolDistrict: "Weber School District",
    notableSchools: ["South Ogden Junior High", "Burch Creek Elementary", "Bonneville High School"],
    outdoorRec: ["Burch Creek Trail", "Glasmann Pond Park", "Weber Pathways trails"],
    localLandmarks: ["South Ogden Nature Park", "Country Hills Golf Course", "40th Street commercial corridor"],
    elevation: 4475,
    geographyNote: "Residential suburb on the eastern bench above Ogden with quick access to Wasatch canyons.",
  },

  "Washington Terrace": {
    medianHomePrice: 340000,
    medianRent: 1300,
    population: 9500,
    growthRate: "1.2%",
    avgDaysOnMarket: 20,
    medianHouseholdIncome: 56000,
    ownerOccupiedPct: 62,
    topEmployers: ["Hill Air Force Base", "Weber School District", "IHC Health Services"],
    commuteTimes: [
      { destination: "Downtown Ogden", minutes: 7 },
      { destination: "Hill Air Force Base", minutes: 10 },
      { destination: "Downtown Salt Lake City", minutes: 45 },
    ],
    schoolDistrict: "Weber School District",
    notableSchools: ["Majestic Elementary", "Orion Junior High", "Bonneville High School"],
    outdoorRec: ["Washington Terrace Park", "Weber River Parkway", "Bonneville Shoreline Trail"],
    localLandmarks: ["Washington Terrace City Park pavilion", "Glasmann Way shops", "Historic military housing area"],
    elevation: 4370,
    geographyNote: "Small city bordered by the Weber River, primarily serving Hill Air Force Base military families.",
  },

  "Riverdale": {
    medianHomePrice: 355000,
    medianRent: 1350,
    population: 9000,
    growthRate: "1.0%",
    avgDaysOnMarket: 22,
    medianHouseholdIncome: 58000,
    ownerOccupiedPct: 58,
    topEmployers: ["Riverdale City", "Riverdale Walmart Distribution", "Fresenius Kabi"],
    commuteTimes: [
      { destination: "Downtown Ogden", minutes: 6 },
      { destination: "Hill Air Force Base", minutes: 8 },
      { destination: "Downtown Salt Lake City", minutes: 40 },
    ],
    schoolDistrict: "Weber School District",
    notableSchools: ["Riverdale Elementary", "South Ogden Junior High", "Bonneville High School"],
    outdoorRec: ["Riverdale Park", "Weber River fishing", "Golden Spike Arena trails"],
    localLandmarks: ["Riverdale Road retail corridor", "Ogden-Hinckley Airport", "Roy Complex sports fields"],
    elevation: 4340,
    geographyNote: "Commercial hub along Riverdale Road (US-26) situated between the Weber River and I-15.",
  },

  "Roy": {
    medianHomePrice: 370000,
    medianRent: 1350,
    population: 40000,
    growthRate: "1.4%",
    avgDaysOnMarket: 23,
    medianHouseholdIncome: 65000,
    ownerOccupiedPct: 68,
    topEmployers: ["Hill Air Force Base", "Weber School District", "Roy City"],
    commuteTimes: [
      { destination: "Hill Air Force Base", minutes: 5 },
      { destination: "Downtown Ogden", minutes: 10 },
      { destination: "Downtown Salt Lake City", minutes: 40 },
    ],
    schoolDistrict: "Weber School District",
    notableSchools: ["Roy High School", "Roy Junior High", "Midland Elementary"],
    outdoorRec: ["Roy Aquatic Center", "Roy West Park", "George Wahlen Veterans Memorial Park"],
    localLandmarks: ["Roy Complex", "Hill Aerospace Museum", "5600 South corridor"],
    elevation: 4360,
    geographyNote: "Flat, expansive city west of I-15 developed largely around Hill Air Force Base employment.",
  },

  "Hooper": {
    medianHomePrice: 475000,
    medianRent: 1550,
    population: 9500,
    growthRate: "3.2%",
    avgDaysOnMarket: 30,
    medianHouseholdIncome: 88000,
    ownerOccupiedPct: 85,
    topEmployers: ["Weber School District", "Hill Air Force Base", "Autoliv"],
    commuteTimes: [
      { destination: "Downtown Ogden", minutes: 18 },
      { destination: "Hill Air Force Base", minutes: 15 },
      { destination: "Downtown Salt Lake City", minutes: 50 },
    ],
    schoolDistrict: "Weber School District",
    notableSchools: ["Hooper Elementary", "Rocky Mountain Junior High", "Fremont High School"],
    outdoorRec: ["Hooper Tomato Days Festival grounds", "Great Salt Lake wetlands", "West Weber Canal trail"],
    localLandmarks: ["Hooper Historic Tomato Days Park", "Crystal Hot Springs (nearby)", "Willard Bay (nearby)"],
    elevation: 4250,
    geographyNote: "Rural agricultural community west of Ogden with large lots, horse properties, and views of the Great Salt Lake.",
  },

  // ──────────────────────────────────────────────
  // DAVIS COUNTY
  // ──────────────────────────────────────────────

  "Clinton": {
    medianHomePrice: 400000,
    medianRent: 1450,
    population: 24000,
    growthRate: "2.5%",
    avgDaysOnMarket: 24,
    medianHouseholdIncome: 76000,
    ownerOccupiedPct: 75,
    topEmployers: ["Hill Air Force Base", "Davis School District", "Freeport Center"],
    commuteTimes: [
      { destination: "Hill Air Force Base", minutes: 8 },
      { destination: "Downtown Ogden", minutes: 15 },
      { destination: "Downtown Salt Lake City", minutes: 40 },
    ],
    schoolDistrict: "Davis School District",
    notableSchools: ["Clinton Elementary", "Sunset Junior High", "Clearfield High School"],
    outdoorRec: ["Clinton City Park", "Heritage Days trails", "Great Salt Lake shorebird preserve"],
    localLandmarks: ["Freeport Center industrial park", "Clinton Veterans Memorial", "1800 North corridor"],
    elevation: 4320,
    geographyNote: "Growing suburban city west of I-15 between Clearfield and West Point on the former lakebed plain.",
  },

  "West Point": {
    medianHomePrice: 430000,
    medianRent: 1500,
    population: 13000,
    growthRate: "3.5%",
    avgDaysOnMarket: 26,
    medianHouseholdIncome: 85000,
    ownerOccupiedPct: 82,
    topEmployers: ["Davis School District", "Hill Air Force Base", "West Point City"],
    commuteTimes: [
      { destination: "Hill Air Force Base", minutes: 10 },
      { destination: "Downtown Ogden", minutes: 18 },
      { destination: "Downtown Salt Lake City", minutes: 42 },
    ],
    schoolDistrict: "Davis School District",
    notableSchools: ["West Point Elementary", "Lakeside Junior High", "Fremont High School"],
    outdoorRec: ["West Point Park", "Great Salt Lake wetlands", "Howard Slough Waterfowl Management Area"],
    localLandmarks: ["West Point Historic Cemetery", "Howard Slough preserve", "300 North corridor"],
    elevation: 4260,
    geographyNote: "Rapidly growing community on the western edge of Davis County near Great Salt Lake marshlands.",
  },

  "Sunset": {
    medianHomePrice: 345000,
    medianRent: 1300,
    population: 5500,
    growthRate: "1.0%",
    avgDaysOnMarket: 18,
    medianHouseholdIncome: 55000,
    ownerOccupiedPct: 58,
    topEmployers: ["Hill Air Force Base", "Freeport Center", "Davis School District"],
    commuteTimes: [
      { destination: "Hill Air Force Base", minutes: 5 },
      { destination: "Downtown Ogden", minutes: 12 },
      { destination: "Downtown Salt Lake City", minutes: 38 },
    ],
    schoolDistrict: "Davis School District",
    notableSchools: ["Sunset Elementary", "Sunset Junior High", "Clearfield High School"],
    outdoorRec: ["Sunset Park", "Sunset Memorial Gardens", "Clinton–Sunset bike path"],
    localLandmarks: ["Sunset Civic Center", "Main Street shops", "Bamberger Railroad heritage marker"],
    elevation: 4340,
    geographyNote: "Small city adjacent to Hill Air Force Base with affordable post-war housing stock.",
  },

  "Syracuse": {
    medianHomePrice: 465000,
    medianRent: 1550,
    population: 34000,
    growthRate: "3.8%",
    avgDaysOnMarket: 25,
    medianHouseholdIncome: 92000,
    ownerOccupiedPct: 82,
    topEmployers: ["Davis School District", "Hill Air Force Base", "Syracuse City"],
    commuteTimes: [
      { destination: "Hill Air Force Base", minutes: 10 },
      { destination: "Downtown Salt Lake City", minutes: 40 },
      { destination: "Downtown Ogden", minutes: 15 },
    ],
    schoolDistrict: "Davis School District",
    notableSchools: ["Syracuse High School", "Syracuse Elementary", "Bluff Ridge Elementary"],
    outdoorRec: ["Antelope Island causeway", "Syracuse City Park", "Jensen Nature Park"],
    localLandmarks: ["Antelope Island State Park entrance", "Syracuse Arts Academy", "Founders Park"],
    elevation: 4280,
    geographyNote: "Fast-growing lakeside community with the Antelope Island causeway as its western gateway.",
  },

  "Clearfield": {
    medianHomePrice: 375000,
    medianRent: 1400,
    population: 33000,
    growthRate: "1.6%",
    avgDaysOnMarket: 20,
    medianHouseholdIncome: 60000,
    ownerOccupiedPct: 58,
    topEmployers: ["Hill Air Force Base", "Freeport Center", "Davis School District"],
    commuteTimes: [
      { destination: "Hill Air Force Base", minutes: 5 },
      { destination: "Downtown Ogden", minutes: 12 },
      { destination: "Downtown Salt Lake City", minutes: 35 },
    ],
    schoolDistrict: "Davis School District",
    notableSchools: ["Clearfield High School", "North Davis Junior High", "Holt Elementary"],
    outdoorRec: ["Fisher Park", "Clearfield Aquatic Center", "Steed Park"],
    localLandmarks: ["Freeport Center", "Clearfield FrontRunner Station", "Hill Aerospace Museum"],
    elevation: 4350,
    geographyNote: "Military-influenced city directly south of Hill Air Force Base with FrontRunner commuter rail access.",
  },

  "Layton": {
    medianHomePrice: 445000,
    medianRent: 1500,
    population: 82000,
    growthRate: "2.2%",
    avgDaysOnMarket: 22,
    medianHouseholdIncome: 78000,
    ownerOccupiedPct: 70,
    topEmployers: ["Hill Air Force Base", "Davis School District", "Davis Hospital and Medical Center"],
    commuteTimes: [
      { destination: "Hill Air Force Base", minutes: 5 },
      { destination: "Downtown Salt Lake City", minutes: 32 },
      { destination: "Downtown Ogden", minutes: 15 },
    ],
    schoolDistrict: "Davis School District",
    notableSchools: ["Layton High School", "Northridge High School", "Central Davis Junior High"],
    outdoorRec: ["Adams Canyon Trail", "Andy Adams Park", "Layton Commons Park"],
    localLandmarks: ["Layton Hills Mall", "Davis Conference Center", "Layton FrontRunner Station"],
    elevation: 4400,
    geographyNote: "Largest city in Davis County, stretching from I-15 east to the Wasatch foothills with Adams Canyon trailhead access.",
  },

  "Kaysville": {
    medianHomePrice: 520000,
    medianRent: 1650,
    population: 33000,
    growthRate: "1.8%",
    avgDaysOnMarket: 26,
    medianHouseholdIncome: 95000,
    ownerOccupiedPct: 80,
    topEmployers: ["Davis School District", "Hill Air Force Base", "Barnes Bullets"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 28 },
      { destination: "Hill Air Force Base", minutes: 10 },
      { destination: "University of Utah", minutes: 30 },
    ],
    schoolDistrict: "Davis School District",
    notableSchools: ["Davis High School", "Kaysville Junior High", "Kaysville Elementary"],
    outdoorRec: ["Bonneville Shoreline Trail", "Kaysville City Park", "East Mountain trails"],
    localLandmarks: ["Heritage Museum at the Bamberger Ranch", "Kaysville FrontRunner Station", "Barnes Park"],
    elevation: 4400,
    geographyNote: "Charming foothill community known for tree-lined streets and older established neighborhoods along the Wasatch bench.",
  },

  "Farmington": {
    medianHomePrice: 560000,
    medianRent: 1750,
    population: 25000,
    growthRate: "3.0%",
    avgDaysOnMarket: 28,
    medianHouseholdIncome: 105000,
    ownerOccupiedPct: 78,
    topEmployers: ["Lagoon Amusement Park", "Davis School District", "HAFB/DOD contractors"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 25 },
      { destination: "Hill Air Force Base", minutes: 15 },
      { destination: "University of Utah", minutes: 28 },
    ],
    schoolDistrict: "Davis School District",
    notableSchools: ["Farmington Junior High", "Knowlton Elementary", "Davis High School"],
    outdoorRec: ["Farmington Creek Trail", "Lagoon Trail", "Farmington Bay Waterfowl Management Area"],
    localLandmarks: ["Lagoon Amusement Park", "Station Park shopping", "Farmington FrontRunner Station"],
    elevation: 4300,
    geographyNote: "Davis County seat with the popular Station Park mixed-use development and Lagoon amusement park.",
  },

  "Centerville": {
    medianHomePrice: 510000,
    medianRent: 1650,
    population: 18000,
    growthRate: "1.5%",
    avgDaysOnMarket: 25,
    medianHouseholdIncome: 92000,
    ownerOccupiedPct: 78,
    topEmployers: ["Davis School District", "Centerville City", "ParrBrownGee & Loveless"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 20 },
      { destination: "Hill Air Force Base", minutes: 20 },
      { destination: "University of Utah", minutes: 22 },
    ],
    schoolDistrict: "Davis School District",
    notableSchools: ["Centerville Elementary", "Centerville Junior High", "Bountiful High School"],
    outdoorRec: ["Deuel Creek Trail", "Porter Walton Park", "Parrish Creek Trail"],
    localLandmarks: ["Centerville City Park amphitheater", "Parrish Lane shops", "I-15 Parrish Lane interchange"],
    elevation: 4340,
    geographyNote: "Small foothill city between Bountiful and Farmington with mature shade trees and mountain-view lots.",
  },

  "Bountiful": {
    medianHomePrice: 530000,
    medianRent: 1700,
    population: 45000,
    growthRate: "1.2%",
    avgDaysOnMarket: 24,
    medianHouseholdIncome: 85000,
    ownerOccupiedPct: 75,
    topEmployers: ["Davis School District", "Lakeview Hospital", "Val Verda Senior Living"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 15 },
      { destination: "University of Utah", minutes: 18 },
      { destination: "Salt Lake International Airport", minutes: 20 },
    ],
    schoolDistrict: "Davis School District",
    notableSchools: ["Bountiful High School", "South Davis Junior High", "Bountiful Elementary"],
    outdoorRec: ["Mueller Park Trail", "Bountiful Ridge Golf Course", "Holbrook Canyon"],
    localLandmarks: ["Bountiful Davis Art Center", "Bountiful Temple", "Main Street historic district"],
    elevation: 4350,
    geographyNote: "Established South Davis community on the Wasatch bench with easy FrontRunner access to downtown SLC.",
  },

  "Woods Cross": {
    medianHomePrice: 430000,
    medianRent: 1450,
    population: 12500,
    growthRate: "1.8%",
    avgDaysOnMarket: 20,
    medianHouseholdIncome: 72000,
    ownerOccupiedPct: 68,
    topEmployers: ["Holly Refining (HF Sinclair)", "Davis School District", "Phillips 66"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 12 },
      { destination: "Salt Lake International Airport", minutes: 18 },
      { destination: "University of Utah", minutes: 15 },
    ],
    schoolDistrict: "Davis School District",
    notableSchools: ["Woods Cross High School", "Woods Cross Elementary", "Bountiful Junior High"],
    outdoorRec: ["Eaglewood Golf Course", "Woods Cross City Park", "Legacy Parkway trail"],
    localLandmarks: ["Woods Cross FrontRunner Station", "HF Sinclair refinery", "Legacy Crossing shopping"],
    elevation: 4300,
    geographyNote: "Gateway between Davis and Salt Lake counties along I-15 and Legacy Parkway with refinery-adjacent industrial heritage.",
  },

  "North Salt Lake": {
    medianHomePrice: 460000,
    medianRent: 1550,
    population: 22000,
    growthRate: "2.8%",
    avgDaysOnMarket: 22,
    medianHouseholdIncome: 80000,
    ownerOccupiedPct: 70,
    topEmployers: ["Overstock.com", "Davis School District", "Holly Refining"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 10 },
      { destination: "Salt Lake International Airport", minutes: 15 },
      { destination: "University of Utah", minutes: 14 },
    ],
    schoolDistrict: "Davis School District",
    notableSchools: ["Orchard Elementary", "North Salt Lake Elementary", "Woods Cross High School"],
    outdoorRec: ["Eaglewood Golf Course", "Foxboro Regional Park", "Legacy Parkway multi-use trail"],
    localLandmarks: ["Eaglewood Golf Course", "Foxboro North community", "North Salt Lake FrontRunner Station"],
    elevation: 4310,
    geographyNote: "Southern Davis County city experiencing significant infill development at the mouth of the I-15/Legacy Parkway corridor.",
  },

  // ──────────────────────────────────────────────
  // SALT LAKE COUNTY
  // ──────────────────────────────────────────────

  "Salt Lake City": {
    medianHomePrice: 535000,
    medianRent: 1650,
    population: 205000,
    growthRate: "1.5%",
    avgDaysOnMarket: 22,
    medianHouseholdIncome: 65000,
    ownerOccupiedPct: 48,
    topEmployers: ["University of Utah", "Intermountain Health", "State of Utah"],
    commuteTimes: [
      { destination: "University of Utah", minutes: 10 },
      { destination: "Salt Lake International Airport", minutes: 12 },
      { destination: "Silicon Slopes (Lehi)", minutes: 35 },
    ],
    schoolDistrict: "Salt Lake City School District",
    notableSchools: ["West High School", "East High School", "Highland High School"],
    outdoorRec: ["Big Cottonwood Canyon", "City Creek Canyon", "Bonneville Shoreline Trail"],
    localLandmarks: ["Temple Square", "Capitol Building", "Gateway Mall"],
    elevation: 4226,
    geographyNote: "State capital situated in a wide valley between the Wasatch Mountains and Oquirrh Mountains at the south end of the Great Salt Lake.",
  },

  "West Valley City": {
    medianHomePrice: 400000,
    medianRent: 1400,
    population: 140000,
    growthRate: "1.6%",
    avgDaysOnMarket: 20,
    medianHouseholdIncome: 58000,
    ownerOccupiedPct: 60,
    topEmployers: ["eBay", "Backcountry.com", "Discover Financial Services"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 15 },
      { destination: "Salt Lake International Airport", minutes: 12 },
      { destination: "Silicon Slopes (Lehi)", minutes: 30 },
    ],
    schoolDistrict: "Granite School District",
    notableSchools: ["Granger High School", "Hunter High School", "West Lake STEM Junior High"],
    outdoorRec: ["USANA Amphitheatre events", "Valley Fair Mall recreation", "Jordan River Parkway"],
    localLandmarks: ["Maverik Center", "USANA Amphitheatre", "Fairbourne Station TRAX"],
    elevation: 4240,
    geographyNote: "Second-largest city in Utah, a diverse suburban expanse on the valley floor west of the Jordan River.",
  },

  "Magna": {
    medianHomePrice: 380000,
    medianRent: 1350,
    population: 28000,
    growthRate: "2.0%",
    avgDaysOnMarket: 19,
    medianHouseholdIncome: 55000,
    ownerOccupiedPct: 62,
    topEmployers: ["Rio Tinto Kennecott", "Granite School District", "US Magnesium"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 22 },
      { destination: "Salt Lake International Airport", minutes: 18 },
      { destination: "Tooele", minutes: 25 },
    ],
    schoolDistrict: "Granite School District",
    notableSchools: ["Cyprus High School", "Matheson Junior High", "Magna Elementary"],
    outdoorRec: ["Great Salt Lake shoreline", "Oquirrh Mountains foothills", "Bingham Creek Trail"],
    localLandmarks: ["Kennecott Copper Mine viewpoint", "Magna Main Street", "Pleasant Green Cemetery"],
    elevation: 4280,
    geographyNote: "Historic mining community at the base of the Oquirrh Mountains, adjacent to Kennecott's Bingham Canyon Mine.",
  },

  "Kearns": {
    medianHomePrice: 370000,
    medianRent: 1350,
    population: 36000,
    growthRate: "1.2%",
    avgDaysOnMarket: 18,
    medianHouseholdIncome: 55000,
    ownerOccupiedPct: 65,
    topEmployers: ["Granite School District", "Utah Olympic Oval", "Camp Williams (nearby)"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 18 },
      { destination: "Salt Lake International Airport", minutes: 15 },
      { destination: "Silicon Slopes (Lehi)", minutes: 25 },
    ],
    schoolDistrict: "Granite School District",
    notableSchools: ["Kearns High School", "Thomas Jefferson Junior High", "Kearns-St. Ann School"],
    outdoorRec: ["Oquirrh Park Fitness Trail", "Kearns Oquirrh Park", "Utah Olympic Oval skating"],
    localLandmarks: ["Utah Olympic Oval", "Kearns Oquirrh Park", "5400 South corridor"],
    elevation: 4290,
    geographyNote: "Census-designated place in western Salt Lake Valley, home to the 2002 Olympic speed skating venue.",
  },

  "Taylorsville": {
    medianHomePrice: 410000,
    medianRent: 1400,
    population: 60000,
    growthRate: "1.3%",
    avgDaysOnMarket: 20,
    medianHouseholdIncome: 60000,
    ownerOccupiedPct: 65,
    topEmployers: ["Granite School District", "Taylorsville City", "C.R. England"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 15 },
      { destination: "Silicon Slopes (Lehi)", minutes: 25 },
      { destination: "University of Utah", minutes: 18 },
    ],
    schoolDistrict: "Granite School District",
    notableSchools: ["Taylorsville High School", "Bennion Junior High", "Vista at Entrada School of Knowledge"],
    outdoorRec: ["Taylorsville City Park", "Jordan River Parkway", "Valley Regional Park"],
    localLandmarks: ["Taylorsville Town Center", "Valley Fair Mall", "4700 South TRAX station"],
    elevation: 4330,
    geographyNote: "Central Salt Lake Valley suburb bisected by the Jordan River with convenient freeway access in all directions.",
  },

  "Murray": {
    medianHomePrice: 445000,
    medianRent: 1500,
    population: 52000,
    growthRate: "1.4%",
    avgDaysOnMarket: 21,
    medianHouseholdIncome: 62000,
    ownerOccupiedPct: 58,
    topEmployers: ["Intermountain Medical Center", "Zions Bancorporation", "Murray School District"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 12 },
      { destination: "Silicon Slopes (Lehi)", minutes: 22 },
      { destination: "University of Utah", minutes: 15 },
    ],
    schoolDistrict: "Murray School District",
    notableSchools: ["Murray High School", "Hillcrest Junior High", "Liberty Elementary"],
    outdoorRec: ["Murray Park", "Jordan River Parkway", "Murray City Golf Course"],
    localLandmarks: ["Fashion Place Mall", "Intermountain Medical Center", "Murray Theater"],
    elevation: 4340,
    geographyNote: "Centrally located city with its own school district, major hospital campus, and TRAX light rail connectivity.",
  },

  "South Salt Lake": {
    medianHomePrice: 385000,
    medianRent: 1350,
    population: 26000,
    growthRate: "2.5%",
    avgDaysOnMarket: 18,
    medianHouseholdIncome: 48000,
    ownerOccupiedPct: 40,
    topEmployers: ["Granite School District", "Central Warehouse", "Marathon Petroleum"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 8 },
      { destination: "University of Utah", minutes: 12 },
      { destination: "Silicon Slopes (Lehi)", minutes: 28 },
    ],
    schoolDistrict: "Granite School District",
    notableSchools: ["South Salt Lake Elementary", "Granite Park Junior High", "Granger High School"],
    outdoorRec: ["Fitts Park", "Jordan River Parkway", "Central Valley Golf Course"],
    localLandmarks: ["Columbus Center community hub", "State Street corridor", "Central Pointe TRAX station"],
    elevation: 4280,
    geographyNote: "Rapidly gentrifying inner-ring suburb between downtown SLC and Murray with significant transit-oriented redevelopment.",
  },

  "Millcreek": {
    medianHomePrice: 500000,
    medianRent: 1600,
    population: 62000,
    growthRate: "1.3%",
    avgDaysOnMarket: 23,
    medianHouseholdIncome: 68000,
    ownerOccupiedPct: 58,
    topEmployers: ["Granite School District", "Intermountain Health", "CHG Healthcare"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 12 },
      { destination: "University of Utah", minutes: 10 },
      { destination: "Silicon Slopes (Lehi)", minutes: 25 },
    ],
    schoolDistrict: "Granite School District",
    notableSchools: ["Skyline High School", "Evergreen Junior High", "Moss Elementary"],
    outdoorRec: ["Millcreek Canyon trails", "Parleys Creek Trail", "Tanner Park"],
    localLandmarks: ["Millcreek Canyon entrance", "Olympus Hills Shopping Center", "3300 South restaurant row"],
    elevation: 4430,
    geographyNote: "East-side community at the mouth of Millcreek Canyon, incorporated as a city in 2016 with eclectic neighborhoods.",
  },

  "Holladay": {
    medianHomePrice: 650000,
    medianRent: 1900,
    population: 32000,
    growthRate: "1.0%",
    avgDaysOnMarket: 30,
    medianHouseholdIncome: 98000,
    ownerOccupiedPct: 72,
    topEmployers: ["Granite School District", "Cottonwood Hospital", "Holladay City"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 14 },
      { destination: "University of Utah", minutes: 12 },
      { destination: "Big Cottonwood Canyon resorts", minutes: 20 },
    ],
    schoolDistrict: "Granite School District",
    notableSchools: ["Olympus High School", "Olympus Junior High", "Spring Lane Elementary"],
    outdoorRec: ["Big Cottonwood Trail", "Holladay Lions Park", "Mt. Olympus trailhead"],
    localLandmarks: ["Holladay Village", "Cottonwood Mall site redevelopment", "Mt. Olympus trailhead"],
    elevation: 4540,
    geographyNote: "Affluent east-side enclave on the Wasatch bench with immediate access to Big Cottonwood Canyon ski resorts.",
  },

  "Cottonwood Heights": {
    medianHomePrice: 680000,
    medianRent: 1950,
    population: 35000,
    growthRate: "1.1%",
    avgDaysOnMarket: 32,
    medianHouseholdIncome: 100000,
    ownerOccupiedPct: 75,
    topEmployers: ["Canyons School District", "Brighton Resort (seasonal)", "CHG Healthcare"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 18 },
      { destination: "Big Cottonwood Canyon resorts", minutes: 15 },
      { destination: "Silicon Slopes (Lehi)", minutes: 22 },
    ],
    schoolDistrict: "Canyons School District",
    notableSchools: ["Brighton High School", "Butler Middle School", "Oakdale Elementary"],
    outdoorRec: ["Big Cottonwood Canyon skiing", "Little Cottonwood Canyon climbing", "Mountview Park"],
    localLandmarks: ["Brighton and Solitude ski area access", "Cottonwood Heights Recreation Center", "Fort Union Boulevard shops"],
    elevation: 4700,
    geographyNote: "Gateway community to both Big and Little Cottonwood Canyons, sitting at the highest elevation of the Salt Lake Valley suburbs.",
  },

  "Midvale": {
    medianHomePrice: 415000,
    medianRent: 1450,
    population: 36000,
    growthRate: "2.0%",
    avgDaysOnMarket: 19,
    medianHouseholdIncome: 55000,
    ownerOccupiedPct: 48,
    topEmployers: ["Canyons School District", "Midvale City", "eBay (nearby)"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 15 },
      { destination: "Silicon Slopes (Lehi)", minutes: 20 },
      { destination: "University of Utah", minutes: 18 },
    ],
    schoolDistrict: "Canyons School District",
    notableSchools: ["Hillcrest High School", "Midvale Middle School", "Midvale Elementary"],
    outdoorRec: ["Jordan River Parkway", "Midvale City Park", "Bingham Junction Trail"],
    localLandmarks: ["Bingham Junction retail area", "Midvale TRAX station", "Historic smelter site park"],
    elevation: 4350,
    geographyNote: "Centrally located in the valley with TRAX light rail and I-15 access, undergoing revitalization near the old smelter site.",
  },

  "Sandy": {
    medianHomePrice: 540000,
    medianRent: 1700,
    population: 98000,
    growthRate: "1.5%",
    avgDaysOnMarket: 24,
    medianHouseholdIncome: 85000,
    ownerOccupiedPct: 72,
    topEmployers: ["Canyons School District", "Snowbird & Alta Ski Resorts (nearby)", "Henrie's"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 20 },
      { destination: "Silicon Slopes (Lehi)", minutes: 15 },
      { destination: "Little Cottonwood Canyon resorts", minutes: 20 },
    ],
    schoolDistrict: "Canyons School District",
    notableSchools: ["Alta High School", "Jordan High School", "Quail Hollow Elementary"],
    outdoorRec: ["Bell Canyon Trail", "Dimple Dell Nature Park", "Little Cottonwood Canyon"],
    localLandmarks: ["The Shops at South Town", "Real Salt Lake America First Field", "Sandy Amphitheater"],
    elevation: 4480,
    geographyNote: "Large east-side suburb extending from the valley floor to the mouth of Little Cottonwood Canyon.",
  },

  "West Jordan": {
    medianHomePrice: 445000,
    medianRent: 1500,
    population: 118000,
    growthRate: "1.8%",
    avgDaysOnMarket: 22,
    medianHouseholdIncome: 75000,
    ownerOccupiedPct: 72,
    topEmployers: ["Jordan School District", "Mountain America Credit Union", "Sysco Intermountain"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 22 },
      { destination: "Silicon Slopes (Lehi)", minutes: 15 },
      { destination: "Salt Lake International Airport", minutes: 25 },
    ],
    schoolDistrict: "Jordan School District",
    notableSchools: ["West Jordan High School", "Copper Hills High School", "Joel P. Jensen Middle School"],
    outdoorRec: ["Ron Wood Park", "Oquirrh Lake at Daybreak", "Jordan River Parkway"],
    localLandmarks: ["Jordan Landing shopping center", "Gardner Village", "Veterans Memorial Park"],
    elevation: 4380,
    geographyNote: "Sprawling west-side city stretching from the Jordan River to the Oquirrh foothills with the master-planned Daybreak community.",
  },

  "South Jordan": {
    medianHomePrice: 580000,
    medianRent: 1800,
    population: 80000,
    growthRate: "2.5%",
    avgDaysOnMarket: 26,
    medianHouseholdIncome: 105000,
    ownerOccupiedPct: 78,
    topEmployers: ["Jordan School District", "Merit Medical Systems", "Domo"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 25 },
      { destination: "Silicon Slopes (Lehi)", minutes: 10 },
      { destination: "Salt Lake International Airport", minutes: 28 },
    ],
    schoolDistrict: "Jordan School District",
    notableSchools: ["Bingham High School", "South Jordan Middle School", "Elk Meadows Elementary"],
    outdoorRec: ["Oquirrh Lake at Daybreak", "Mulligans Golf Course", "SoJo Trail"],
    localLandmarks: ["Daybreak community", "The District shopping center", "South Jordan FrontRunner Station"],
    elevation: 4430,
    geographyNote: "Affluent south-valley city anchored by the Daybreak master-planned community and growing tech corridor.",
  },

  "Riverton": {
    medianHomePrice: 550000,
    medianRent: 1750,
    population: 46000,
    growthRate: "2.0%",
    avgDaysOnMarket: 27,
    medianHouseholdIncome: 100000,
    ownerOccupiedPct: 82,
    topEmployers: ["Jordan School District", "Riverton City", "Mountain Point Medical Center"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 28 },
      { destination: "Silicon Slopes (Lehi)", minutes: 12 },
      { destination: "Salt Lake International Airport", minutes: 30 },
    ],
    schoolDistrict: "Jordan School District",
    notableSchools: ["Riverton High School", "Oquirrh Hills Middle School", "Rose Creek Elementary"],
    outdoorRec: ["Riverton City Park", "Butterfield Canyon Trail", "Old Farm Park"],
    localLandmarks: ["Mountain Point Medical Center", "Riverton Town Center", "12600 South corridor"],
    elevation: 4480,
    geographyNote: "Family-oriented south-valley community with a blend of newer subdivisions and remnant equestrian properties.",
  },

  "Herriman": {
    medianHomePrice: 520000,
    medianRent: 1700,
    population: 60000,
    growthRate: "5.5%",
    avgDaysOnMarket: 28,
    medianHouseholdIncome: 95000,
    ownerOccupiedPct: 80,
    topEmployers: ["Jordan School District", "Herriman City", "Facebook Data Center (nearby)"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 32 },
      { destination: "Silicon Slopes (Lehi)", minutes: 15 },
      { destination: "Salt Lake International Airport", minutes: 35 },
    ],
    schoolDistrict: "Jordan School District",
    notableSchools: ["Herriman High School", "Fort Herriman Middle School", "Butterfield Canyon Elementary"],
    outdoorRec: ["Butterfield Canyon OHV trails", "Blackridge Reservoir", "Herriman Hills Trail"],
    localLandmarks: ["Herriman Towne Center", "Blackridge Reservoir Park", "Rose Creek development"],
    elevation: 5100,
    geographyNote: "One of Utah's fastest-growing cities, climbing up the eastern slopes of the Oquirrh Mountains southwest of the valley.",
  },

  "Bluffdale": {
    medianHomePrice: 590000,
    medianRent: 1800,
    population: 18000,
    growthRate: "4.5%",
    avgDaysOnMarket: 30,
    medianHouseholdIncome: 110000,
    ownerOccupiedPct: 82,
    topEmployers: ["Jordan School District", "NSA Utah Data Center", "The Point development"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 30 },
      { destination: "Silicon Slopes (Lehi)", minutes: 8 },
      { destination: "Salt Lake International Airport", minutes: 32 },
    ],
    schoolDistrict: "Jordan School District",
    notableSchools: ["Bluffdale Elementary", "Riverton High School", "Mountain Ridge Junior High"],
    outdoorRec: ["Porter Rockwell Trail", "Steep Mountain Trail", "Jordan River Parkway"],
    localLandmarks: ["NSA Utah Data Center", "The Point of the Mountain redevelopment", "Porter Rockwell Trail"],
    elevation: 4550,
    geographyNote: "Southern Salt Lake County city at the Point of the Mountain, site of the former state prison now being redeveloped as a massive mixed-use project.",
  },

  "Draper": {
    medianHomePrice: 640000,
    medianRent: 1900,
    population: 51000,
    growthRate: "2.2%",
    avgDaysOnMarket: 28,
    medianHouseholdIncome: 115000,
    ownerOccupiedPct: 78,
    topEmployers: ["eBay", "1-800 Contacts", "Canyons School District"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 25 },
      { destination: "Silicon Slopes (Lehi)", minutes: 8 },
      { destination: "University of Utah", minutes: 28 },
    ],
    schoolDistrict: "Canyons School District",
    notableSchools: ["Corner Canyon High School", "Draper Park Middle School", "Willow Springs Elementary"],
    outdoorRec: ["Corner Canyon trails", "Lone Peak trailhead", "Draper City Park"],
    localLandmarks: ["Loveland Living Planet Aquarium", "1300 East retail corridor", "Corner Canyon trailhead"],
    elevation: 4530,
    geographyNote: "Upscale south-valley city at the base of the Wasatch Range with world-class mountain biking in Corner Canyon.",
  },

  // ──────────────────────────────────────────────
  // UTAH COUNTY
  // ──────────────────────────────────────────────

  "Lehi": {
    medianHomePrice: 550000,
    medianRent: 1750,
    population: 82000,
    growthRate: "5.0%",
    avgDaysOnMarket: 24,
    medianHouseholdIncome: 105000,
    ownerOccupiedPct: 78,
    topEmployers: ["Adobe", "Microsoft", "Ancestry"],
    commuteTimes: [
      { destination: "Downtown Salt Lake City", minutes: 35 },
      { destination: "Silicon Slopes (Lehi)", minutes: 5 },
      { destination: "Provo/BYU", minutes: 25 },
    ],
    schoolDistrict: "Alpine School District",
    notableSchools: ["Lehi High School", "Skyridge High School", "Willowcreek Middle School"],
    outdoorRec: ["Murdock Canal Trail", "Thanksgiving Point gardens", "Utah Lake shoreline"],
    localLandmarks: ["Thanksgiving Point", "Silicon Slopes tech campus", "Lehi Roller Mills"],
    elevation: 4550,
    geographyNote: "Epicenter of Utah's Silicon Slopes tech corridor at the Point of the Mountain between Salt Lake and Utah counties.",
  },

  "Saratoga Springs": {
    medianHomePrice: 520000,
    medianRent: 1700,
    population: 45000,
    growthRate: "7.0%",
    avgDaysOnMarket: 26,
    medianHouseholdIncome: 98000,
    ownerOccupiedPct: 82,
    topEmployers: ["Alpine School District", "Saratoga Springs City", "Lehi tech corridor employers"],
    commuteTimes: [
      { destination: "Silicon Slopes (Lehi)", minutes: 12 },
      { destination: "Downtown Salt Lake City", minutes: 42 },
      { destination: "Provo/BYU", minutes: 30 },
    ],
    schoolDistrict: "Alpine School District",
    notableSchools: ["Westlake High School", "Vista Heights Middle School", "Harvest Elementary"],
    outdoorRec: ["Utah Lake State Park", "Pelican Point shoreline", "Saratoga Springs Hot Pot"],
    localLandmarks: ["Neptune Park", "Talus Ridge development", "Grandeur at Saratoga Springs"],
    elevation: 4510,
    geographyNote: "Booming lakeside city on the northwest shore of Utah Lake with expansive master-planned communities.",
  },

  "Eagle Mountain": {
    medianHomePrice: 450000,
    medianRent: 1550,
    population: 55000,
    growthRate: "8.0%",
    avgDaysOnMarket: 25,
    medianHouseholdIncome: 88000,
    ownerOccupiedPct: 82,
    topEmployers: ["Alpine School District", "Eagle Mountain City", "Camp Williams"],
    commuteTimes: [
      { destination: "Silicon Slopes (Lehi)", minutes: 18 },
      { destination: "Downtown Salt Lake City", minutes: 48 },
      { destination: "Provo/BYU", minutes: 35 },
    ],
    schoolDistrict: "Alpine School District",
    notableSchools: ["Cedar Valley High School", "Frontier Middle School", "Pony Express Elementary"],
    outdoorRec: ["Tickville Gulch Trail", "Cory Wride Memorial Park", "Cedar Fort Reservoir"],
    localLandmarks: ["Pony Express Trail marker", "Eagle Mountain City Park", "Ranches at Eagle Mountain"],
    elevation: 4900,
    geographyNote: "One of Utah's fastest-growing cities on the western side of the Lake Mountains in Cedar Valley.",
  },

  "Alpine": {
    medianHomePrice: 850000,
    medianRent: 2400,
    population: 11000,
    growthRate: "1.5%",
    avgDaysOnMarket: 38,
    medianHouseholdIncome: 140000,
    ownerOccupiedPct: 90,
    topEmployers: ["Alpine School District", "Alpine City", "Local professional services"],
    commuteTimes: [
      { destination: "Silicon Slopes (Lehi)", minutes: 12 },
      { destination: "Provo/BYU", minutes: 20 },
      { destination: "Downtown Salt Lake City", minutes: 40 },
    ],
    schoolDistrict: "Alpine School District",
    notableSchools: ["Lone Peak High School", "Timberline Middle School", "Alpine Elementary"],
    outdoorRec: ["Lone Peak Wilderness", "Lambert Park trails", "Alpine Loop Scenic Byway"],
    localLandmarks: ["Alpine Loop road", "Lambert Park", "Smooth Canyon trailhead"],
    elevation: 5050,
    geographyNote: "Small, affluent foothill community nestled at the base of Lone Peak with large lots and mountain views.",
  },

  "Highland": {
    medianHomePrice: 720000,
    medianRent: 2200,
    population: 19000,
    growthRate: "1.8%",
    avgDaysOnMarket: 35,
    medianHouseholdIncome: 128000,
    ownerOccupiedPct: 92,
    topEmployers: ["Alpine School District", "Highland City", "Lehi tech corridor employers"],
    commuteTimes: [
      { destination: "Silicon Slopes (Lehi)", minutes: 10 },
      { destination: "Provo/BYU", minutes: 18 },
      { destination: "Downtown Salt Lake City", minutes: 38 },
    ],
    schoolDistrict: "Alpine School District",
    notableSchools: ["Lone Peak High School", "Mountain Ridge Junior High", "Highland Elementary"],
    outdoorRec: ["Murdock Canal Trail", "Highland Glen Park", "Dry Creek Trail"],
    localLandmarks: ["Highland Town Center", "Highland Glen Park splash pad", "Art Dye Park"],
    elevation: 4800,
    geographyNote: "Upscale residential community between Alpine and American Fork known for its large-lot neighborhoods and mountain backdrop.",
  },

  "American Fork": {
    medianHomePrice: 480000,
    medianRent: 1600,
    population: 35000,
    growthRate: "2.5%",
    avgDaysOnMarket: 23,
    medianHouseholdIncome: 82000,
    ownerOccupiedPct: 70,
    topEmployers: ["Alpine School District", "Northrop Grumman", "BD Medical"],
    commuteTimes: [
      { destination: "Silicon Slopes (Lehi)", minutes: 8 },
      { destination: "Provo/BYU", minutes: 18 },
      { destination: "Downtown Salt Lake City", minutes: 35 },
    ],
    schoolDistrict: "Alpine School District",
    notableSchools: ["American Fork High School", "Shelley Elementary", "Forbes Elementary"],
    outdoorRec: ["American Fork Canyon", "Timpanogos Cave National Monument", "Art Dye Park"],
    localLandmarks: ["Timpanogos Cave National Monument", "American Fork Steel Days", "Historic Main Street"],
    elevation: 4600,
    geographyNote: "Gateway city to American Fork Canyon and Timpanogos Cave, with a blend of historic downtown and new development.",
  },

  "Pleasant Grove": {
    medianHomePrice: 470000,
    medianRent: 1550,
    population: 40000,
    growthRate: "2.2%",
    avgDaysOnMarket: 22,
    medianHouseholdIncome: 80000,
    ownerOccupiedPct: 72,
    topEmployers: ["Alpine School District", "Purple Mattress", "Xactware Solutions"],
    commuteTimes: [
      { destination: "Silicon Slopes (Lehi)", minutes: 10 },
      { destination: "Provo/BYU", minutes: 15 },
      { destination: "Downtown Salt Lake City", minutes: 38 },
    ],
    schoolDistrict: "Alpine School District",
    notableSchools: ["Pleasant Grove High School", "Manila Elementary", "Pleasant Grove Junior High"],
    outdoorRec: ["Battle Creek Falls Trail", "Grove Creek Trail", "Manila Creek Park"],
    localLandmarks: ["Strawberry Days rodeo grounds", "Veterans Memorial Park", "Battle Creek Falls trailhead"],
    elevation: 4660,
    geographyNote: "Known as 'Utah's City of Trees,' situated at the base of Mt. Timpanogos with historic orchards and newer tech campuses.",
  },

  "Lindon": {
    medianHomePrice: 560000,
    medianRent: 1750,
    population: 12000,
    growthRate: "2.0%",
    avgDaysOnMarket: 28,
    medianHouseholdIncome: 98000,
    ownerOccupiedPct: 80,
    topEmployers: ["DigiCert", "4Life Research", "Alpine School District"],
    commuteTimes: [
      { destination: "Silicon Slopes (Lehi)", minutes: 10 },
      { destination: "Provo/BYU", minutes: 12 },
      { destination: "Downtown Salt Lake City", minutes: 40 },
    ],
    schoolDistrict: "Alpine School District",
    notableSchools: ["Lindon Elementary", "Oak Canyon Junior High", "Pleasant Grove High School"],
    outdoorRec: ["Murdock Canal Trail", "Hollow Park", "Lindon City Park"],
    localLandmarks: ["Lindon Marina at Utah Lake", "4Life Research campus", "Lindon Hollow Park"],
    elevation: 4660,
    geographyNote: "Small city between Pleasant Grove and Orem with a mix of tech-company campuses and family neighborhoods.",
  },

  "Vineyard": {
    medianHomePrice: 460000,
    medianRent: 1600,
    population: 22000,
    growthRate: "12.0%",
    avgDaysOnMarket: 22,
    medianHouseholdIncome: 85000,
    ownerOccupiedPct: 65,
    topEmployers: ["Alpine School District", "Vineyard City", "Anderson Geneva development"],
    commuteTimes: [
      { destination: "Provo/BYU", minutes: 10 },
      { destination: "Silicon Slopes (Lehi)", minutes: 15 },
      { destination: "Downtown Salt Lake City", minutes: 42 },
    ],
    schoolDistrict: "Alpine School District",
    notableSchools: ["Vineyard Elementary", "Canyon View Junior High", "Orem High School"],
    outdoorRec: ["Utah Lake shoreline trail", "Vineyard Connector Trail", "future lakefront promenade"],
    localLandmarks: ["Anderson Geneva steel mill redevelopment", "FrontRunner Vineyard Station", "The Shoreline at Vineyard"],
    elevation: 4490,
    geographyNote: "Utah's fastest-growing city, built on the former Geneva Steel site along the northeast shore of Utah Lake.",
  },

  "Orem": {
    medianHomePrice: 455000,
    medianRent: 1550,
    population: 100000,
    growthRate: "1.8%",
    avgDaysOnMarket: 22,
    medianHouseholdIncome: 68000,
    ownerOccupiedPct: 58,
    topEmployers: ["Utah Valley University", "Blendtec", "Xactware Solutions"],
    commuteTimes: [
      { destination: "Provo/BYU", minutes: 8 },
      { destination: "Silicon Slopes (Lehi)", minutes: 15 },
      { destination: "Downtown Salt Lake City", minutes: 42 },
    ],
    schoolDistrict: "Alpine School District",
    notableSchools: ["Mountain View High School", "Orem High School", "Timpanogos High School"],
    outdoorRec: ["Mt. Timpanogos Trail", "Palisade State Park", "Orem Fitness Park"],
    localLandmarks: ["Utah Valley University campus", "University Place Mall", "SCERA Center for the Arts"],
    elevation: 4650,
    geographyNote: "Known as 'Family City USA,' spanning from the Utah Lake shoreline to the base of Mt. Timpanogos.",
  },

  "Provo": {
    medianHomePrice: 470000,
    medianRent: 1500,
    population: 115000,
    growthRate: "1.5%",
    avgDaysOnMarket: 23,
    medianHouseholdIncome: 52000,
    ownerOccupiedPct: 38,
    topEmployers: ["Brigham Young University", "Vivint", "Nu Skin Enterprises"],
    commuteTimes: [
      { destination: "Silicon Slopes (Lehi)", minutes: 22 },
      { destination: "Downtown Salt Lake City", minutes: 48 },
      { destination: "Sundance Resort", minutes: 20 },
    ],
    schoolDistrict: "Provo School District",
    notableSchools: ["Provo High School", "Timpview High School", "Dixon Middle School"],
    outdoorRec: ["Y Mountain Trail", "Rock Canyon Trail", "Provo River Parkway"],
    localLandmarks: ["Brigham Young University campus", "Provo City Center Temple", "Covey Center for the Arts"],
    elevation: 4550,
    geographyNote: "Utah County seat and college town dominated by BYU, set between Utah Lake and the Wasatch Range with Provo Canyon to the east.",
  },

  "Springville": {
    medianHomePrice: 445000,
    medianRent: 1500,
    population: 37000,
    growthRate: "2.5%",
    avgDaysOnMarket: 24,
    medianHouseholdIncome: 72000,
    ownerOccupiedPct: 70,
    topEmployers: ["Nebo School District", "Springville City", "Xango"],
    commuteTimes: [
      { destination: "Provo/BYU", minutes: 10 },
      { destination: "Silicon Slopes (Lehi)", minutes: 28 },
      { destination: "Downtown Salt Lake City", minutes: 55 },
    ],
    schoolDistrict: "Nebo School District",
    notableSchools: ["Springville High School", "Springville Junior High", "Art City Elementary"],
    outdoorRec: ["Hobble Creek Canyon", "Clyde Recreation Center", "Springville Art City Days trails"],
    localLandmarks: ["Springville Museum of Art", "Historic downtown Main Street", "Clyde Recreation Center"],
    elevation: 4590,
    geographyNote: "Known as 'Art City' for its museum and cultural tradition, located at the mouth of Hobble Creek Canyon.",
  },

  "Mapleton": {
    medianHomePrice: 600000,
    medianRent: 1900,
    population: 12500,
    growthRate: "2.8%",
    avgDaysOnMarket: 32,
    medianHouseholdIncome: 110000,
    ownerOccupiedPct: 88,
    topEmployers: ["Nebo School District", "Mapleton City", "Local agriculture"],
    commuteTimes: [
      { destination: "Provo/BYU", minutes: 12 },
      { destination: "Silicon Slopes (Lehi)", minutes: 30 },
      { destination: "Spanish Fork", minutes: 10 },
    ],
    schoolDistrict: "Nebo School District",
    notableSchools: ["Mapleton Junior High", "Mapleton Elementary", "Springville High School"],
    outdoorRec: ["Maple Canyon trails", "Mapleton Lateral Canal trail", "Hobble Creek Golf Course"],
    localLandmarks: ["Mapleton City Park", "Hobble Creek Golf Course", "Whiting Library"],
    elevation: 4750,
    geographyNote: "Affluent foothill community on the southeastern bench above Springville with panoramic views of Utah Valley.",
  },

  "Spanish Fork": {
    medianHomePrice: 430000,
    medianRent: 1450,
    population: 45000,
    growthRate: "3.0%",
    avgDaysOnMarket: 23,
    medianHouseholdIncome: 75000,
    ownerOccupiedPct: 72,
    topEmployers: ["Nebo School District", "Nestl\u00e9 Prepared Foods", "Spanish Fork City"],
    commuteTimes: [
      { destination: "Provo/BYU", minutes: 15 },
      { destination: "Silicon Slopes (Lehi)", minutes: 32 },
      { destination: "Downtown Salt Lake City", minutes: 58 },
    ],
    schoolDistrict: "Nebo School District",
    notableSchools: ["Spanish Fork High School", "Landmark Elementary", "Riverview Elementary"],
    outdoorRec: ["Spanish Fork River Trail", "Canyon View Park", "Spanish Fork Reservoir"],
    localLandmarks: ["Fiesta Days rodeo grounds", "Spanish Fork Icelandic Hot Springs (nearby)", "Historic Main Street"],
    elevation: 4620,
    geographyNote: "Largest city in south Utah County, situated at the confluence of the Spanish Fork River and its canyon.",
  },

  "Salem": {
    medianHomePrice: 480000,
    medianRent: 1550,
    population: 12000,
    growthRate: "4.0%",
    avgDaysOnMarket: 27,
    medianHouseholdIncome: 90000,
    ownerOccupiedPct: 85,
    topEmployers: ["Nebo School District", "Salem City", "Salem Hills Golf Course"],
    commuteTimes: [
      { destination: "Provo/BYU", minutes: 18 },
      { destination: "Spanish Fork", minutes: 5 },
      { destination: "Silicon Slopes (Lehi)", minutes: 35 },
    ],
    schoolDistrict: "Nebo School District",
    notableSchools: ["Salem Hills High School", "Salem Elementary", "Foothills Elementary"],
    outdoorRec: ["Salem Hills Golf Course", "Salem Pond fishing", "Loafer Mountain trails"],
    localLandmarks: ["Salem Pond Park", "Salem Hills Golf Course", "Salem Days celebration grounds"],
    elevation: 4700,
    geographyNote: "Small community east of Spanish Fork with a popular fishing pond and newer hillside subdivisions.",
  },

  "Payson": {
    medianHomePrice: 400000,
    medianRent: 1400,
    population: 22000,
    growthRate: "2.5%",
    avgDaysOnMarket: 24,
    medianHouseholdIncome: 68000,
    ownerOccupiedPct: 70,
    topEmployers: ["Nebo School District", "Payson City", "Walmart Distribution Center"],
    commuteTimes: [
      { destination: "Provo/BYU", minutes: 22 },
      { destination: "Spanish Fork", minutes: 8 },
      { destination: "Silicon Slopes (Lehi)", minutes: 40 },
    ],
    schoolDistrict: "Nebo School District",
    notableSchools: ["Payson High School", "Payson Junior High", "Wilson Elementary"],
    outdoorRec: ["Payson Canyon trails", "Payson Lakes campground", "Memorial Hill Park"],
    localLandmarks: ["Peteetneet Academy museum", "Payson Temple", "Onion Days festival grounds"],
    elevation: 4640,
    geographyNote: "Historic south Utah County town at the mouth of Payson Canyon with roots in agriculture and the annual Onion Days festival.",
  },

  "Santaquin": {
    medianHomePrice: 380000,
    medianRent: 1350,
    population: 13000,
    growthRate: "4.5%",
    avgDaysOnMarket: 25,
    medianHouseholdIncome: 72000,
    ownerOccupiedPct: 78,
    topEmployers: ["Nebo School District", "Santaquin City", "Local poultry and agriculture"],
    commuteTimes: [
      { destination: "Provo/BYU", minutes: 28 },
      { destination: "Spanish Fork", minutes: 12 },
      { destination: "Silicon Slopes (Lehi)", minutes: 45 },
    ],
    schoolDistrict: "Nebo School District",
    notableSchools: ["Santaquin Elementary", "Payson High School", "Orchard Hills Elementary"],
    outdoorRec: ["Santaquin Canyon trails", "Tinney Flat Campground", "Santaquin Peak hike"],
    localLandmarks: ["Historic Chieftain Museum", "Santaquin Orchard Days grounds", "Old Main Street"],
    elevation: 5100,
    geographyNote: "Small agricultural community at the southern end of Utah Valley, surrounded by orchards and climbing toward the foothills.",
  },

  "Nephi": {
    medianHomePrice: 340000,
    medianRent: 1250,
    population: 6500,
    growthRate: "1.8%",
    avgDaysOnMarket: 35,
    medianHouseholdIncome: 58000,
    ownerOccupiedPct: 68,
    topEmployers: ["Juab School District", "Nephi City", "Christensen's Department Store"],
    commuteTimes: [
      { destination: "Provo/BYU", minutes: 50 },
      { destination: "Spanish Fork", minutes: 35 },
      { destination: "Downtown Salt Lake City", minutes: 85 },
    ],
    schoolDistrict: "Juab School District",
    notableSchools: ["Juab High School", "Juab Middle School", "Red Cliffs Elementary"],
    outdoorRec: ["Salt Creek Canyon", "Mt. Nebo Scenic Byway", "Yuba Reservoir (nearby)"],
    localLandmarks: ["Mt. Nebo Scenic Loop drive", "Ute Stampede rodeo grounds", "Historic Main Street"],
    elevation: 5130,
    geographyNote: "Small ranching town in Juab Valley at the southern base of 11,928-foot Mt. Nebo, the highest peak in the Wasatch Range.",
  },
}
