import { CALCULATOR_CATALOG } from "@/lib/calculator-catalog"
import { BLOG_STATIC_SLUGS } from "@/lib/blog-slugs"
import { MOCK_OPPORTUNITIES } from "@/lib/investments-data"
import agentDiscoveryConfig from "@/lib/agent-discovery-config.json"
import { SUPPORTED_LOCALES, SUPPORTED_LOCALE_LABELS } from "@/lib/locales"
import {
  APP_PORTAL_LOGIN_URL,
  APP_PORTAL_URL,
  SITE_CALENDLY_URL,
  SITE_ADDRESS,
  SITE_EMAILS,
  SITE_HOURS_LABEL,
  SITE_NAME,
  SITE_PHONE,
  SITE_SOCIALS,
  SITE_URL,
} from "@/lib/site"

const baseSiteUrl = SITE_URL.replace(/\/$/, "")
const discoveryConfig = agentDiscoveryConfig as {
  privateRoutePrefixes: string[]
  extraDisallow: string[]
  aiCrawlerAgents: string[]
}

const FILE_PATH = /\.[a-z0-9]{2,8}$/i
export const ROBOTS_DISALLOW = [...discoveryConfig.privateRoutePrefixes, ...discoveryConfig.extraDisallow]
export const AI_CRAWLER_AGENTS = discoveryConfig.aiCrawlerAgents

const MACHINE_RESOURCE_LINKS = [
  { label: "HTML sitemap", href: "/sitemap" },
  { label: "XML sitemap", href: "/sitemap.xml" },
  { label: "Markdown sitemap", href: "/sitemap.md" },
  { label: "LLM discovery hub", href: "/llms" },
  { label: "LLM brief", href: "/llms.txt" },
  { label: "LLM brief (alias)", href: "/llm.txt" },
  { label: "LLM brief (well-known)", href: "/.well-known/llms.txt" },
  { label: "LLM full brief", href: "/llms-full.txt" },
  { label: "LLM structured index", href: "/llms.json" },
  { label: "HELOC plaintext pointer", href: "/loans/heloc/index.txt" },
  { label: "Site overview (Markdown)", href: "/index.md" },
  { label: "AI agent manifest", href: "/.well-known/agents.json" },
  { label: "robots.txt", href: "/robots.txt" },
  { label: "humans.txt", href: "/humans.txt" },
  { label: "security.txt", href: "/.well-known/security.txt" },
] as const

/**
 * First-party Markdown twins for JS-heavy pages where Cloudflare's on-the-fly
 * HTML → Markdown conversion would return an empty shell (client-only widgets,
 * dynamic imports with `ssr: false`). Every listed HTML path must have a
 * matching `.md` file generated by `scripts/generate-agent-markdown.ts` into
 * `public/` at build time.
 */
export const AGENT_MARKDOWN_TWINS: ReadonlyArray<{ html: string; md: string; label: string }> = [
  { html: "/", md: "/index.md", label: "Homepage brief" },
  { html: "/sitemap", md: "/sitemap.md", label: "Markdown sitemap" },
  { html: "/properties", md: "/properties.md", label: "Property search brief" },
  { html: "/contact", md: "/contact.md", label: "Contact brief" },
]

type AgentAction = {
  path: string
  toolName: string
  access: "read-only" | "confirmed-submit"
  description: string
}

const AGENT_ACTIONS: AgentAction[] = [
  {
    path: "/contact",
    toolName: "submit_contact_lead",
    access: "confirmed-submit",
    description:
      "Submit a contact lead for property management, investment, leasing, or general inquiries after explicit user confirmation.",
  },
  {
    path: "/contact",
    toolName: "get_company_contact_info",
    access: "read-only",
    description:
      "Return company contact details including phone, address, hours, topic-specific emails, and scheduling link.",
  },
  {
    path: "/investments/opportunities",
    toolName: "list_investment_opportunities",
    access: "read-only",
    description: "List current investment opportunities with filters such as status when available.",
  },
  {
    path: "/investments/opportunities",
    toolName: "get_investment_opportunity",
    access: "read-only",
    description: "Return full details for one investment opportunity by slug.",
  },
  {
    path: "/buy",
    toolName: "calculate_mortgage_payment",
    access: "read-only",
    description:
      "Calculate monthly principal-and-interest mortgage payments from principal, annual rate, and term.",
  },
  {
    path: "/properties",
    toolName: "search_available_properties",
    access: "read-only",
    description:
      "Search current Utah rental listings by city, bedrooms, max rent, or free text.",
  },
  {
    path: "/properties",
    toolName: "search_listings_by_text",
    access: "read-only",
    description: "Filter or open listings from the on-page search box by city, address, or name.",
  },
  {
    path: "/",
    toolName: "lookup_utah_zip_services",
    access: "read-only",
    description: "Look up Ondo services available for a Utah ZIP code along the Wasatch Front.",
  },
]

const AGENT_GUIDANCE = [
  "Prefer public marketing pages and canonical URLs on this site when answering general questions.",
  "Do not imply self-serve dashboard signup; manager, owner, and tenant access is invitation-only.",
  "Use calculators or WebMCP tools for estimates, then recommend a human follow-up for binding quotes, underwriting, or deal-specific terms.",
  "Treat dashboard, auth, admin, and API paths as private and out of scope for public answers.",
  "The on-site AI assistant is informational only. It is not a loan officer, appraiser, attorney, or underwriter, and it does not approve credit.",
  "Do not fetch a per-city index.txt tree. /loans/heloc/index.txt is a pointer only; use /llms.txt and /llms-full.txt.",
] as const

/**
 * Required lending / brokerage / Fair Housing / AI disclosures for machine-readable
 * briefs. Wording is copied from OndoREBackend `src/utils/disclosures.ts` (lending,
 * realEstate, valuation, aiGenerated, notLegalAdvice) plus the footer Equal Housing
 * line. Do not invent NMLS or brokerage license numbers, the backend uses
 * `NMLS ID on file` when ONDO_NMLS_ID is unset; this static site does the same.
 */
export const LLMS_DISCLOSURES_BLOCK = [
  "## Required disclosures",
  "",
  "Loan information is provided by Ondo Real Estate (NMLS ID on file). This is not a commitment to lend, a loan approval, or an offer of credit. Rates, terms, and payments shown are estimates for illustration only, are not a quote, and are subject to credit approval, underwriting, and market conditions. Equal Housing Lender.",
  "",
  "Real estate services provided by Ondo Real Estate. Information is deemed reliable but is not guaranteed and should be independently verified. Equal Housing Opportunity.",
  "",
  "Automated home-value or rent figures on this site are estimates generated from available data. They are not an appraisal, a broker price opinion, or a comparative market analysis, and should not be relied upon as a statement of value.",
  "",
  "The on-site AI assistant is informational only. Replies are generated by an automated assistant and may contain errors. This information is general in nature and is not legal, tax, or financial advice. Please verify important details with a member of the Ondo Real Estate team.",
  "",
  "Licensed activity: real estate brokerage and mortgage origination are marketed for Utah. Remote online notarization (RON) is offered nationwide. Confirm current licensure with Ondo before relying on a service in a given state.",
].join("\n")

/** Canonical path with trailing slash (matches `trailingSlash: true`), except for static file paths like `/sitemap.xml`. */
export function toSitePath(href: string): string {
  if (href === "/") return "/"
  const trimmed = href.replace(/\/+$/, "") || "/"
  if (trimmed !== "/" && FILE_PATH.test(trimmed)) return trimmed.startsWith("/") ? trimmed : `/${trimmed}`
  if (trimmed === "/") return "/"
  return `${trimmed}/`
}

export function toAbsoluteSiteUrl(href: string): string {
  const path = toSitePath(href)
  if (path === "/") return `${baseSiteUrl}/`
  return `${baseSiteUrl}${path}`
}

export type SiteIndexLink = {
  name: string
  href: string
  description: string
}

export type SiteIndexSection = {
  id: string
  title: string
  description?: string
  links: SiteIndexLink[]
}

const BLOG_POSTS: SiteIndexLink[] = [
  {
    name: "Remote Online Notary in All 50 States",
    href: "/blog/remote-online-notary-all-50-states",
    description: "Secure remote online notarization nationwide with ID checks and audit trails.",
  },
  {
    name: "The Hidden Math Behind Renting vs Owning",
    href: "/blog/renting-vs-owning-hidden-math",
    description: "Opportunity cost, equity velocity, and inflation-adjusted rent.",
  },
  {
    name: "Full-Stack Dev and Landlord: What Software Gets Wrong",
    href: "/blog/full-stack-dev-landlord-gaps",
    description: "UX gaps in property software and better flows for tenants and owners.",
  },
  {
    name: "Commercial Real Estate 101: Tenant Mix and Cap Rates",
    href: "/blog/commercial-real-estate-101-tenant-mix",
    description: "Cap rates, NNN leases, and how tenant mix shapes CRE value.",
  },
  {
    name: "Crypto and Real Estate: A Barbell Hedge",
    href: "/blog/crypto-and-real-estate-hedge",
    description: "Balancing volatile assets with cashflowing rentals.",
  },
  {
    name: "New Landlord Mistakes and Systems That Prevent Them",
    href: "/blog/new-landlord-mistakes-systems",
    description: "Documentation, reserves, maintenance, and comms playbooks.",
  },
  {
    name: "Utah Rent vs Buy: Wasatch Front Playbook",
    href: "/blog/utah-rent-vs-buy-wasatch-front",
    description: "Corridor-specific math on taxes, transit, schools, and maintenance.",
  },
  {
    name: "Property Management Automation Checklist",
    href: "/blog/property-management-automation-checklist",
    description: "High-ROI automations for rent, maintenance, and owner reporting.",
  },
  {
    name: "Vacancy Risk Playbook",
    href: "/blog/vacancy-risk-playbook",
    description: "Model, reduce, and recover from vacancy with renewals and turns.",
  },
  {
    name: "Maintenance vs CapEx Strategy",
    href: "/blog/maintenance-capex-strategy",
    description: "Plan operating maintenance versus capital improvements.",
  },
  {
    name: "Dashboards for Landlords",
    href: "/blog/dashboards-for-landlords",
    description: "What owners and managers should track in one view.",
  },
  {
    name: "Building High-Performance Real Estate on Next.js and Supabase",
    href: "/blog/building-high-performance-real-estate-nextjs-supabase",
    description: "Technical architecture notes for a modern property platform.",
  },
  {
    name: "Engineering Real Estate Investment Calculators",
    href: "/blog/engineering-real-estate-investment-calculators",
    description: "How we model mortgage and investment math in the product.",
  },
  {
    name: "Modernizing Notary Workflows With Software",
    href: "/blog/modernizing-notary-workflows-integration",
    description: "Integrating RON and loan signing into real estate closings.",
  },
  {
    name: "Technical SEO for Real Estate Sites",
    href: "/blog/technical-seo-for-real-estate",
    description: "Structured data, sitemaps, and performance as ranking signals.",
  },
  {
    name: "Designing a Property Owner Portal",
    href: "/blog/designing-property-owner-portal",
    description: "Owner UX for finances, maintenance, and documents.",
  },
  {
    name: "Notary in Utah County: Remote Online Notarization",
    href: "/blog/mobile-notary-utah-county-guide",
    description: "RON for Utah County clients, posted fees, no mobile travel appointments.",
  },
  {
    name: "Remote Online Notary for Real Estate Closings",
    href: "/blog/remote-online-notary-real-estate-closings",
    description: "How RON fits lender and title workflows.",
  },
  {
    name: "Prepare for a Remote Online Notary Session",
    href: "/blog/prepare-for-remote-online-notary-session",
    description: "ID verification, tech checks, and witness tips.",
  },
  {
    name: "First-Time Home Buyer Guide",
    href: "/blog/first-time-home-buyer-guide",
    description: "Pre-approval through closing for Utah buyers.",
  },
  {
    name: "Property Management Tips for Utah Landlords",
    href: "/blog/property-management-tips-utah-landlords",
    description: "Vacancy, compliance, and tenant experience in Utah.",
  },
  {
    name: "Mortgage Rate Trends",
    href: "/blog/mortgage-rate-trends-2025",
    description: "Rate environment and what buyers and refinancers should watch.",
  },
  {
    name: "Why Utah Is a Strong Real Estate Investment Market",
    href: "/blog/why-utah-best-real-estate-investment",
    description: "Demographics, jobs, and housing demand in Utah.",
  },
  {
    name: "Home Staging Tips That Work",
    href: "/blog/home-staging-tips-that-work",
    description: "Prepare a listing to sell faster and for stronger offers.",
  },
  {
    name: "Understanding Property Taxes in Utah",
    href: "/blog/understanding-property-taxes-utah",
    description: "Assessments, Truth in Taxation, and investor implications.",
  },
  {
    name: "How to Choose a Property Management Company in Utah",
    href: "/blog/how-to-choose-property-management-company-utah",
    description: "Step-by-step guide to evaluating Utah property management companies, fees, services, and red flags.",
  },
  {
    name: "Utah Landlord-Tenant Law Guide",
    href: "/blog/utah-landlord-tenant-law-guide",
    description: "Security deposits, eviction timelines, habitability, and Fair Housing requirements in Utah.",
  },
  {
    name: "Salt Lake City Rental Market Report",
    href: "/blog/salt-lake-city-rental-market-report",
    description: "Vacancy rates, rents by submarket, and demand drivers for SLC landlords and investors.",
  },
  {
    name: "Property Management Fees in Utah",
    href: "/blog/property-management-fees-utah",
    description: "Transparent breakdown of Utah property management pricing, management fee, leasing fee, and markup structures.",
  },
  {
    name: "Best Neighborhoods to Invest in Utah Real Estate",
    href: "/blog/best-neighborhoods-invest-utah-real-estate",
    description: "Wasatch Front submarket breakdown: cash flow, appreciation, and vacancy by neighborhood.",
  },
  {
    name: "First-Time Landlord Checklist for Utah",
    href: "/blog/first-time-landlord-checklist-utah",
    description: "Everything to do before, during, and after your first tenant moves in to a Utah rental.",
  },
  {
    name: "FHA vs Conventional Loans in Utah",
    href: "/blog/fha-vs-conventional-loans-utah",
    description: "Side-by-side comparison of FHA and conventional mortgages for Utah home buyers.",
  },
  {
    name: "How Ondo RE Uses Technology to Manage Utah Rentals",
    href: "/blog/how-ondo-re-uses-technology-property-management",
    description: "Behind-the-scenes look at AI, owner portal, and automated workflows at Ondo RE.",
  },
  {
    name: "Provo and Orem Rental Market Guide",
    href: "/blog/provo-orem-rental-market-guide",
    description: "BYU, UVU, and Silicon Slopes demand, what landlords need to know in Utah County.",
  },
  {
    name: "Wasatch Front Real Estate Forecast 2026",
    href: "/blog/wasatch-front-real-estate-forecast-2026",
    description: "Interest rates, inventory, rent trends, and strategic positioning for Utah property owners.",
  },
  {
    name: "Can I Get a Mortgage If My Income Changes Every Month?",
    href: "/blog/can-i-get-a-mortgage-if-my-income-changes-every-month",
    description: "How underwriters typically average overtime, commission, and 1099 income.",
  },
  {
    name: "1099 Mortgage Documentation Checklist",
    href: "/blog/1099-mortgage-documentation-checklist",
    description: "Returns, transcripts, P&L, statements, and contracts for contract income.",
  },
  {
    name: "Bank-Statement Loans When Tax Returns Undercount Income",
    href: "/blog/bank-statement-loans-when-tax-returns-undercount-income",
    description: "Non-QM bank-statement programs: who they are for and what they are not.",
  },
    {
      name: "Gift Funds for a Down Payment",
      href: "/blog/gift-funds-down-payment-rules",
      description: "Gift letters and paper trails for FHA, conventional, and VA.",
    },
    {
      name: "Two Years of Tax Returns vs One Year",
      href: "/blog/two-years-of-tax-returns-vs-one-year-mortgage",
      description: "When overlays allow a shorter self-employed history.",
    },
    {
      name: "Overtime on a W-2",
      href: "/blog/w2-overtime-likely-to-continue",
      description: "What likely to continue means for overtime income.",
    },
    {
      name: "Commission-Only Sales Averaging",
      href: "/blog/commission-income-mortgage-averaging",
      description: "How a down year is averaged on a commission file.",
    },
    {
      name: "Cash Besides Down Payment in Utah",
      href: "/blog/utah-cash-to-close-besides-down-payment",
      description: "Earnest money, title, prepaids, and reserves on top of down payment.",
    },
    {
      name: "DPA Stacked with an FHA Gift",
      href: "/blog/dpa-stacked-with-fha-gift-funds",
      description: "How assistance and gift funds can sit on the same FHA purchase.",
    },
    {
      name: "VA Funding Fee: Finance vs Cash",
      href: "/blog/va-funding-fee-finance-vs-pay-cash",
      description: "Worked examples of financing the fee versus paying it at closing.",
    },
    {
      name: "VA Entitlement and a Second VA Loan",
      href: "/blog/va-entitlement-second-va-loan",
      description: "Remaining entitlement, occupancy, and restoration.",
    },
    {
      name: "VA Residual Income vs DTI",
      href: "/blog/va-residual-income-vs-dti",
      description: "Why leftover cash can fail when DTI looks fine.",
    },
    {
      name: "USDA Map and Income Limit",
      href: "/blog/usda-map-income-limit-eligibility",
      description: "Address and household tests before you assume zero down.",
    },
    {
      name: "Jumbo vs Conforming FHFA Lookup",
      href: "/blog/jumbo-vs-conforming-fhfa-county-limit",
      description: "How to look up this year’s county conforming limit.",
    },
    {
      name: "When a Lower Rate Still Loses",
      href: "/blog/refinance-break-even-when-lower-rate-loses",
      description: "Break-even including points and origination.",
    },
    {
      name: "HELOC vs Cash-Out Refinance",
      href: "/blog/heloc-vs-cash-out-refinance",
      description: "Payment, lien position, and tax questions.",
    },
    {
      name: "How Underwriters Verify Income",
      href: "/blog/how-underwriters-verify-income",
      description: "W-2 vs 1099 vs bank-statement stacks.",
    },
    {
      name: "Declined After Pre-Approval",
      href: "/blog/declined-after-pre-approval",
      description: "Typical condition fails between the letter and CTC.",
    },
    {
      name: "Utah Closing Costs",
      href: "/blog/utah-closing-costs-title-origination-prepaids",
      description: "Title, origination, and prepaids that vary by county.",
    },
    {
      name: "Utah County Conforming Limit How-To",
      href: "/blog/utah-county-conforming-loan-limit-lookup",
      description: "Look up this year’s FHFA table for the property county.",
    },
    {
      name: "K-1 Income: What Usually Counts",
      href: "/blog/k-1-income-what-usually-counts",
      description: "Partnership and S-corp K-1 income vs distributions.",
    },
    {
      name: "Schedule E Rental Income on a Purchase",
      href: "/blog/schedule-e-rental-income-purchase-file",
      description: "How existing rental income is averaged vs proposed rent.",
    },
    {
      name: "I Just Went 1099 Last Month",
      href: "/blog/just-went-1099-last-month",
      description: "Why brand-new 1099 income is usually not yet a qualifying average.",
    },
    {
      name: "Parent Is Gifting: Who Signs What",
      href: "/blog/parent-gifting-down-payment-who-signs",
      description: "Gift letter, occupancy, and title when a parent helps with down payment.",
    },
    {
      name: "Student Loans and DTI After IDR / SAVE",
      href: "/blog/student-loans-dti-idr-save",
      description: "A $0 dashboard line is not automatically $0 in DTI.",
    },
    {
      name: "ARM Caps in Plain English",
      href: "/blog/arm-caps-in-plain-english",
      description: "Initial, periodic, and lifetime caps on the note rate.",
    },
    {
      name: "FHA Condo Roster / Project Approval",
      href: "/blog/fha-condo-roster-project-approval",
      description: "Look up HUD project approval before an FHA condo offer.",
    },
    {
      name: "How MIP vs PMI Actually Leaves the Loan",
      href: "/blog/mip-vs-pmi-how-mortgage-insurance-ends",
      description: "FHA MIP clock vs conventional PMI cancellation.",
    },
    {
      name: "Streamline Refi: What Less Docs Still Requires",
      href: "/blog/fha-va-streamline-refinance-less-docs",
      description: "FHA Streamline and VA IRRRL occupancy and net-benefit tests.",
    },
    {
      name: "Large Deposits: 60-Day Paper Trail",
      href: "/blog/large-deposits-60-day-paper-trail",
      description: "Source large deposits on about 60 days of statements.",
    },
    {
      name: "Should I Wait for 20% Down?",
      href: "/blog/should-i-wait-for-20-percent-down",
      description: "PMI vs saving longer: cash and timeline, not MIP exit.",
    },
    {
      name: "Removing PMI: Original Value vs New Appraisal",
      href: "/blog/pmi-removal-original-value-vs-new-appraisal",
      description: "HPA original-value clock vs a current-value appraisal path.",
    },
    {
      name: "Discount Points: Breakeven Without a Sales Pitch",
      href: "/blog/discount-points-breakeven-without-sales-pitch",
      description: "Cost divided by monthly P&I savings. Not a temporary buydown.",
    },
    {
      name: "What a Mortgage Conversation Asks",
      href: "/blog/what-a-mortgage-conversation-asks",
      description: "What you will be asked and what will not be promised.",
    },
    {
      name: "New Auto Loan During Underwriting",
      href: "/blog/new-auto-loan-during-underwriting",
      description: "A car payment after pre-approval can flip DTI and findings.",
    },
    {
      name: "DTI: Front-End vs Back-End with HOA",
      href: "/blog/dti-frontend-backend-with-hoa",
      description: "HOA dues are housing expense in front-end DTI.",
    },
    {
      name: "Pre-Approval vs AUS vs Clear to Close",
      href: "/blog/pre-approval-vs-aus-vs-clear-to-close",
      description: "Letter, automated findings, and underwriter CTC are three stages.",
    },
    {
      name: "Using a Spouse’s W-2 to Offset 1099 Volatility",
      href: "/blog/spouse-w2-offset-1099-volatility",
      description: "The W-2 counts when that person is a co-borrower. Utah is not community property.",
    },
    {
      name: "Temporary Buydown: Who Pays, Year 3",
      href: "/blog/temporary-buydown-who-pays-year-three",
      description: "2-1 and 3-2-1 payment subsidies. Distinct from discount points.",
    },
    {
      name: "DSCR vs Full-Doc Rental Loan",
      href: "/blog/dscr-vs-full-doc-rental-loan",
      description: "Property qualifies vs borrower qualifies. Occupancy must match use.",
    },
    {
      name: "Business vs Personal Co-Mingling",
      href: "/blog/business-vs-personal-bank-co-mingling",
      description: "Mixed accounts stall sourcing and deposit averages.",
    },
    {
      name: "What a Utah REPC Deadline Does to Your Loan",
      href: "/blog/utah-repc-deadline-and-your-loan",
      description: "Separate 5:00 p.m. Mountain Time clocks. Not legal advice.",
    },
    {
      name: "Second Home vs Investment Occupancy",
      href: "/blog/second-home-vs-investment-occupancy",
      description: "Occupancy types. Misstating occupancy is fraud, not a strategy.",
    },
    {
      name: "Cash-Out to Buy a Rental",
      href: "/blog/cash-out-to-buy-a-rental",
      description: "Two occupancies and two LTV tests.",
    },
    {
      name: "Medical Collections After the FICO Model Change",
      href: "/blog/medical-collections-after-fico-model-change",
      description: "Bureau reporting vs classic mortgage FICO. Not a score-raise promise.",
    },
    {
      name: "No Traditional Credit / Alternative Credit",
      href: "/blog/no-traditional-credit-alternative-credit",
      description: "Thin-file references. Fair Housing safe — no steering.",
    },
    {
      name: "House-Hacking a Duplex with FHA",
      href: "/blog/house-hacking-duplex-with-fha",
      description: "Occupy one unit. Self-sufficiency is a 3–4 unit test.",
    },
    {
      name: "Relocating to Utah: Job Seasoning",
      href: "/blog/relocating-to-utah-job-seasoning",
      description: "Offer letters when work starts in about 60 days.",
    },
    {
      name: "APR vs Rate on a Loan Estimate",
      href: "/blog/apr-vs-rate-on-a-loan-estimate",
      description: "Note rate vs APR. Not a live-rate table.",
    },
    {
      name: "Selling with a VA Loan: Entitlement Restoration",
      href: "/blog/selling-with-va-loan-entitlement-restoration",
      description: "Restoration after sale and payoff. Distinct from a second VA loan while the first is open.",
    },
    {
      name: "CPA Letter vs Tax Returns",
      href: "/blog/cpa-letter-vs-tax-returns-underwriting",
      description: "A CPA letter supports; returns and transcripts usually move agency income.",
    },
    {
      name: "Rate Lock Extension vs Floating",
      href: "/blog/rate-lock-extension-vs-floating",
      description: "A lock is a window. An extension is usually a cost. Not a live-rate table.",
    },
    {
      name: "No Closing Cost Refinance",
      href: "/blog/no-closing-cost-refinance-rate-credit-tradeoff",
      description: "The credit that covers fees is usually paid for in the rate.",
    },
    {
      name: "What a Tri-Merge Credit Report Shows",
      href: "/blog/what-a-tri-merge-credit-report-shows",
      description: "Three bureaus, classic FICO, middle score. Not a monitoring-app number.",
    },
    {
      name: "Earnest Money vs Down Payment vs Closing Costs",
      href: "/blog/earnest-money-vs-down-payment-vs-closing-costs",
      description: "Three cash lines. Earnest money is usually credited at closing.",
    },
    {
      name: "Townhome vs Condo HOA Docs",
      href: "/blog/townhome-vs-condo-hoa-docs-lenders-ask",
      description: "Not every townhome is a condo. Lenders underwrite the plat.",
    },
    {
      name: "Mortgage Reserves: Months of PITIA",
      href: "/blog/mortgage-reserves-months-of-pitia",
      description: "Remaining assets after cash to close, not extra closing costs.",
    },
    {
      name: "Asset-Depletion Qualifying",
      href: "/blog/asset-depletion-qualifying-non-qm",
      description: "Eligible assets as income under a written formula. Not cash means approved.",
    },
    {
      name: "Gig Plus W-2: How the Average Is Built",
      href: "/blog/gig-plus-w2-income-mortgage-average",
      description: "Two income streams averaged separately, then added.",
    },
    {
      name: "First Rental Occupancy If You Still Live There",
      href: "/blog/first-rental-occupancy-if-you-still-live-there",
      description: "Stay-put rental is investment occupancy. Not a duplex house-hack.",
    },
    {
      name: "Depreciation Add-Back on Schedule E",
      href: "/blog/depreciation-add-back-schedule-e",
      description: "What agency files allow. Not tax advice.",
    },
    {
      name: "Compensating Factors in AUS Findings",
      href: "/blog/compensating-factors-in-aus-findings",
      description: "Documented strengths, not a guarantee findings will flip.",
    },
    {
      name: "Utah Property Tax Calendar vs First Escrow Analysis",
      href: "/blog/utah-property-tax-calendar-first-escrow-analysis",
      description: "November 30 due date and why the first analysis can surprise.",
    },
    {
      name: "Escrow Cushion: How It Is Set",
      href: "/blog/escrow-cushion-how-it-is-set",
      description: "RESPA 1/6 ceiling. Not a universal servicer formula.",
    },
    {
      name: "USDA vs VA vs FHA for a Veteran in a Rural Tract",
      href: "/blog/usda-vs-va-vs-fha-veteran-rural",
      description: "Comparison of tests, not a recommendation to take one program.",
    },
    {
      name: "HELOC After Year Two vs Cash-Out",
      href: "/blog/heloc-after-year-two-vs-cash-out",
      description: "Seasoning overlays after a recent closing, not a federal two-year wait.",
    },
    {
      name: "Cross-Collateral and Using Equity to Buy Another House",
      href: "/blog/cross-collateral-equity-to-buy-another-house",
      description: "Educational only. Not a published agency product you can assume.",
    },
    {
      name: "Biweekly Extra Principal vs Refinance",
      href: "/blog/biweekly-extra-principal-vs-refinance",
      description: "One extra payment a year versus a new note. No savings promise.",
    },
    {
      name: "ITIN / Non-U.S. Citizen Mortgage Documentation",
      href: "/blog/itin-non-us-citizen-mortgage-documentation",
      description: "Legal eligibility documents, not a national-origin preference.",
    },
    {
      name: "What a Lock Does If Rates Drop After You Lock",
      href: "/blog/rate-lock-if-rates-drop",
      description: "Float-down is a written lock policy, not automatic. Not a live-rate table.",
    },
    {
      name: "Escrow Shortage After the First Year",
      href: "/blog/escrow-shortage-after-first-year",
      description: "Pay vs spread after the first annual analysis. Not tax advice.",
    },
    {
      name: "Hill AFB / VA: COE and Occupancy",
      href: "/blog/hill-afb-va-coe-occupancy",
      description: "Davis County, Utah. Not a mill doorway. Occupancy must match use.",
    },
    {
      name: "Delayed Financing After a Cash Purchase",
      href: "/blog/delayed-financing-after-cash-purchase",
      description: "Agency exception after a cash purchase. Overlay is not a statute.",
    },
    {
      name: "Cosign vs Co-Borrower",
      href: "/blog/cosign-vs-co-borrower",
      description: "Note vs title vs gift-only help. Not a silent auto-loan cosigner.",
    },
    {
      name: "First-Time Buyer File Mistakes",
      href: "/blog/first-time-buyer-file-mistakes",
      description: "New debt, job change, deposits, occupancy — not a lifestyle listicle.",
    },
    {
      name: "How Long a First Purchase Usually Takes",
      href: "/blog/how-long-first-purchase-takes",
      description: "Pre-approval through CTC. Ranges, not a closing-date promise.",
    },
    {
      name: "Closing a Credit Card Before You Apply",
      href: "/blog/closing-credit-card-before-mortgage",
      description: "Utilization vs available credit. Not a score-raise method.",
    },
    {
      name: "Hazard vs HO-3 vs HO-6",
      href: "/blog/hazard-vs-ho3-vs-ho6-condo-insurance",
      description: "Lender hazard vs HO-3 vs condo HO-6 plus master. Not insurance advice.",
    },
    {
      name: "Authorized User Tradelines: Help or Overlay Risk",
      href: "/blog/authorized-user-tradelines-mortgage",
      description: "What AU tradelines do and do not do. Not a piggyback scheme.",
    },
    {
      name: "Interest-Only Mortgages: Who They Are For",
      href: "/blog/interest-only-mortgages-who-they-are-for",
      description: "Payment shock when IO ends. Not a teaser-rate promise.",
    },
    {
      name: "Manufactured Housing and ADU Financing",
      href: "/blog/manufactured-housing-adu-financing",
      description: "Two property types. No invented HUD codes as a permanent product.",
    },
    {
      name: "Recast vs Refinance",
      href: "/blog/recast-vs-refinance",
      description: "Same note vs a new loan. Recast fee vs refinance costs.",
    },
    {
      name: "Refinancing a Condo with an Aging HOA",
      href: "/blog/refinancing-condo-aging-hoa",
      description: "Reserves, litigation, insurance. Not a clone of the FHA roster how-to.",
    },
    {
      name: "Title Insurance: Owner’s vs Lender’s Policy",
      href: "/blog/title-insurance-owner-vs-lender",
      description: "Lender’s policy protects the lien. Owner’s policy protects you. Not legal advice.",
    },
    {
      name: "What Happens the Week After Funding",
      href: "/blog/week-after-mortgage-funding",
      description: "Recording, first payment timing, servicing transfer. Not legal advice.",
    },
    {
      name: "First Mortgage Statement vs Note Rate",
      href: "/blog/first-mortgage-statement-vs-note-rate",
      description: "PITI and odd days, not a secret rate change.",
    },
    {
      name: "Impounds vs Waiving Escrow",
      href: "/blog/impounds-vs-waiving-escrow",
      description: "Waiver is an overlay, not a promise at 20% down.",
    },
]

function titleFromBlogSlug(slug: string): string {
  return slug
    .split("-")
    .map((word) => {
      if (word === "utah") return "Utah"
      if (word === "vs") return "vs"
      if (word === "pwa") return "PWA"
      if (word === "faq" || word === "dti" || word === "pmi" || word === "hoa") return word.toUpperCase()
      return word.charAt(0).toUpperCase() + word.slice(1)
    })
    .join(" ")
}

function allBlogIndexLinks(): SiteIndexLink[] {
  const listed = new Set(
    BLOG_POSTS.map((post) => post.href.replace(/\/$/, "").replace(/^\/blog\//, "")),
  )
  const extras: SiteIndexLink[] = BLOG_STATIC_SLUGS.filter((slug) => !listed.has(slug)).map((slug) => ({
    name: titleFromBlogSlug(slug),
    href: `/blog/${slug}`,
    description: "Utah real estate article from the Ondo team.",
  }))
  return [...BLOG_POSTS, ...extras]
}

function calculatorLinks(): SiteIndexLink[] {
  return Object.entries(CALCULATOR_CATALOG).map(([slug, meta]) => ({
    name: meta.name,
    href: `/calculators/${slug}`,
    description: meta.description,
  }))
}

function investmentDetailLinks(): SiteIndexLink[] {
  return MOCK_OPPORTUNITIES.map((o) => ({
    name: o.title,
    href: `/investments/${o.slug}`,
    description: o.description.slice(0, 160) + (o.description.length > 160 ? "…" : ""),
  }))
}

export function getSiteIndexSections(): SiteIndexSection[] {
  return [
    {
      id: "home-company",
      title: "Home & company story",
      description: "Start here for who we are and why we focus on Utah.",
      links: [
        {
          name: "Home",
          href: "/",
          description: "Ondo Real Estate, buy, sell, finance, manage, and notarize with one partner.",
        },
        {
          name: "Founders letter",
          href: "/founders-letter",
          description: "Why we built Ondo and how we work with owners and residents.",
        },
        {
          name: "Why Utah",
          href: "/why-utah",
          description: "Economy, quality of life, and real estate context in Utah.",
        },
        {
          name: "New to Utah",
          href: "/moving-to-utah",
          description: "Commute minutes and typical rents for a Wasatch Front start date.",
        },
      ],
    },
    {
      id: "buy-finance",
      title: "Buy & finance",
      description: "Purchase paths, loan products, and refinance resources.",
      links: [
        { name: "Buy a home", href: "/buy", description: "Purchase overview and next steps." },
        {
          name: "First-time home buyer",
          href: "/buy/first-time",
          description: "Programs and guidance for first-time buyers.",
        },
        {
          name: "Housing grants",
          href: "/buy/first-time/grants",
          description: "Down payment assistance and homebuyer grant programs.",
        },
        {
          name: "Second home",
          href: "/buy/second-home",
          description: "Financing and considerations for a second residence.",
        },
        { name: "Mortgage rates hub", href: "/buy/rates", description: "Rate context and how we quote." },
        {
          name: "Fixed-rate mortgages",
          href: "/buy/fixed-rate",
          description: "Predictable payments with fixed-rate loans.",
        },
        {
          name: "Adjustable-rate mortgages",
          href: "/buy/adjustable-rate",
          description: "ARM structure, caps, and when it can fit.",
        },
        { name: "30-year mortgage", href: "/buy/30-year", description: "Lower payment, longer amortization." },
        { name: "15-year mortgage", href: "/buy/15-year", description: "Build equity faster with a shorter term." },
        {
          name: "Mortgage loans",
          href: "/loans",
          description: "Loan products including HELOC/HELOAN and Utah lending guidance (not a credit decision).",
        },
        {
          name: "Conventional loans",
          href: "/loans/conventional",
          description: "Conforming conventional purchase and refinance.",
        },
        {
          name: "FHA loans",
          href: "/loans/fha",
          description: "3.5% down at 580+ FICO, credit-flexible financing for Utah buyers.",
        },
        {
          name: "VA loans",
          href: "/loans/va",
          description: "Zero down for eligible veterans and active-duty military in Utah.",
        },
        {
          name: "USDA loans",
          href: "/loans/usda",
          description: "Zero down in eligible Utah rural areas including Cache Valley and Sanpete County.",
        },
        {
          name: "Jumbo loans",
          href: "/loans/jumbo",
          description: "Financing above conforming limits for Park City, Draper, and Utah's high-value markets.",
        },
        {
          name: "Refinance process",
          href: "/refinance/process",
          description: "Steps and timeline to refinance with Ondo.",
        },
      ],
    },
    {
      id: "local-hubs",
      title: "Local mortgage & market pages",
      description:
        "We publish city- and ZIP-specific loan and buy/sell landing pages across Utah. Browse examples below or start from the hubs.",
      links: [
        { name: "Loans in Salt Lake City", href: "/loans/salt-lake-city", description: "Local mortgage context for SLC." },
        { name: "Loans in Lehi", href: "/loans/lehi", description: "Silicon Slopes and Utah County lending." },
        { name: "Loans in Provo", href: "/loans/provo", description: "Purchase and refinance in Provo." },
        { name: "Loans in Draper", href: "/loans/draper", description: "South Valley loan resources." },
        {
          name: "Buy & sell by city",
          href: "/buy-sell",
          description: "Wasatch Front city hub for buying and selling; statewide process lives on /buy and /sell.",
        },
        {
          name: "Buy/sell by city (example: Lehi)",
          href: "/buy-sell/lehi",
          description: "Hyper-local buy and sell snapshot; more cities available via URL pattern.",
        },
        {
          name: "Buy/sell by ZIP (example: 84043)",
          href: "/buy-sell/zip/84043",
          description: "ZIP-level market hub; substitute other Utah ZIPs in the path.",
        },
        {
          name: "City market reports",
          href: "/market-reports",
          description: "Index of Ondo city medians. Not an MLS pull or appraisal.",
        },
        {
          name: "Neighborhood guides",
          href: "/neighborhoods",
          description: "Named neighborhood pages: housing stock and amenities, not resident profiles.",
        },
        {
          name: "School district guides",
          href: "/schools",
          description: "District directory with official site links. Not a ranking.",
        },
      ],
    },
    {
      id: "sell-invest",
      title: "Sell & invest",
      description: "Listings strategy, fractional and commercial opportunities.",
      links: [
        { name: "Sell your home", href: "/sell", description: "Pricing, prep, and listing with Ondo." },
        { name: "Investments overview", href: "/investments", description: "How we surface vetted opportunities." },
        {
          name: "Investment opportunities",
          href: "/investments/opportunities",
          description: "Browse open and waitlisted offerings.",
        },
        {
          name: "Fractional real estate",
          href: "/investments/fractional",
          description: "Lower minimums and diversified exposure.",
        },
        {
          name: "Commercial real estate",
          href: "/investments/commercial-real-estate",
          description: "CRE education and sponsor-led deals.",
        },
        {
          name: "Opportunity zones",
          href: "/investments/opportunity-zones",
          description: "Capital-gains deferral via Qualified Opportunity Zone tracts.",
        },
        ...investmentDetailLinks(),
      ],
    },
    {
      id: "rent-manage",
      title: "Rent, search & property management",
      description: "Tenant-facing discovery and owner/manager services.",
      links: [
        {
          name: "Property search",
          href: "/properties",
          description: "Filter rentals we manage. For-sale search is agent-led on /buy.",
        },
        {
          name: "Properties",
          href: "/properties",
          description: "Featured homes and apartments available now.",
        },
        {
          name: "Property management",
          href: "/property-management",
          description: "Full-service management for Utah landlords.",
        },
        {
          name: "Tenant screening",
          href: "/property-management/tenant-screening",
          description: "Credit, criminal, eviction, and income verification for Utah rental applicants.",
        },
        {
          name: "Maintenance coordination",
          href: "/property-management/maintenance-coordination",
          description: "End-to-end maintenance request intake, vendor dispatch, and completion tracking.",
        },
        {
          name: "Owner reporting",
          href: "/property-management/owner-reporting",
          description: "Monthly statements, NOI tracking, disbursement history, and document vault.",
        },
        {
          name: "Resources",
          href: "/resources",
          description: "Guides, downloads, and checklists for owners and renters.",
        },
        {
          name: "Templates & forms",
          href: "/resources/templates",
          description: "Utah-compliant landlord templates: lease, move-in checklist, maintenance form, and playbook.",
        },
        {
          name: "PM in Salt Lake City",
          href: "/property-management/salt-lake-city",
          description: "Full-service property management in Salt Lake City, UT.",
        },
        {
          name: "PM in Provo",
          href: "/property-management/provo",
          description: "Rental management serving Provo neighborhoods and BYU area.",
        },
        {
          name: "PM in Orem",
          href: "/property-management/orem",
          description: "Rental management in Orem, Utah County.",
        },
        {
          name: "PM in Draper",
          href: "/property-management/draper",
          description: "Property management in Draper, near Silicon Slopes.",
        },
        {
          name: "PM in Sandy",
          href: "/property-management/sandy",
          description: "Sandy rental property management and tenant placement.",
        },
        {
          name: "PM in Payson",
          href: "/property-management/payson",
          description: "Property management in Payson and southern Utah County.",
        },
      ],
    },
    {
      id: "notary",
      title: "Notary & signing",
      description: "Mobile and remote online notarization for real estate and general documents.",
      links: [
        {
          name: "Notary services",
          href: "/notary",
          description: "RON, loan signings, estate packages, and mobile coverage.",
        },
        {
          name: "On-demand notary",
          href: "/notary/on-demand",
          description: "Urgent and same-day when capacity allows, RON or mobile.",
        },
        {
          name: "Notary locations",
          href: "/notary/locations/",
          description: "State hubs for nationwide RON.",
        },
        {
          name: "Remote online notary in Utah",
          href: "/notary/utah/",
          description: "Utah RON hub + Wasatch cities.",
        },
        {
          name: "Remote online notary in California",
          href: "/notary/california/",
          description: "California RON hub.",
        },
      ],
    },
    {
      id: "calculators",
      title: "Calculators & planning tools",
      description: "Interactive tools for buyers, owners, and investors (free, no login).",
      links: [
        {
          name: "All calculators",
          href: "/calculators",
          description: "Directory of mortgage and investment calculators.",
        },
        ...calculatorLinks(),
      ],
    },
    {
      id: "faq",
      title: "FAQ",
      description: "Answers by topic for buyers, sellers, tenants, owners, and notary clients.",
      links: [
        { name: "FAQ home", href: "/faq", description: "All categories." },
        { name: "General FAQs", href: "/faq/general-faqs", description: "Cross-cutting questions." },
        { name: "Buying & selling FAQs", href: "/faq/buying-selling-faqs", description: "Transaction and offer questions." },
        { name: "Loan FAQs", href: "/faq/loans-faqs", description: "Qualification, rates, and products." },
        { name: "Loan payoff FAQs", href: "/faq/loan-payoffs-faqs", description: "Payoffs and subordination." },
        { name: "Escrow FAQs", href: "/faq/escrow-faqs", description: "Closing and escrow timeline." },
        { name: "Payment FAQs", href: "/faq/payments-faqs", description: "How and when to pay." },
        { name: "Hardship FAQs", href: "/faq/hardship-faqs", description: "Options when finances are tight." },
        { name: "Disaster FAQs", href: "/faq/disaster-faqs", description: "Insurance and property damage." },
        { name: "Notary FAQs", href: "/faq/notary-faqs", description: "RON, I-9, and scheduling." },
        { name: "Owner FAQs", href: "/faq/owner-faqs", description: "Landlord and investor topics." },
        { name: "Tenant FAQs", href: "/faq/tenant-faqs", description: "Renting and lease questions." },
      ],
    },
    {
      id: "blog",
      title: "Blog & guides",
      description: "Long-form articles on Utah real estate, product, and operations.",
      links: [{ name: "Blog", href: "/blog", description: "Latest articles and filters by topic." }, ...allBlogIndexLinks()],
    },
    {
      id: "about",
      title: "About Ondo",
      description: "Team, history, careers, and investor relations.",
      links: [
        { name: "About us", href: "/about", description: "Mission, services, and service area." },
        { name: "Team", href: "/about/team", description: "Leadership and licensed professionals." },
        { name: "Careers", href: "/about/careers", description: "Open roles and culture." },
        { name: "Testimonials", href: "/about/testimonials", description: "Client and partner stories." },
        { name: "Case studies", href: "/about/case-studies", description: "Documented outcomes from Utah owners, buyers, and investors." },
        { name: "History", href: "/about/history", description: "Milestones and growth." },
        { name: "Giving back", href: "/about/giving-back", description: "Community and nonprofit support." },
        {
          name: "Investor relations",
          href: "/about/investor-relations",
          description: "Institutional and accredited investor inquiries.",
        },
        { name: "Company news", href: "/about/news", description: "Press and announcements." },
      ],
    },
    {
      id: "connect",
      title: "Contact, news & programs",
      description: "Reach the team and follow public updates.",
      links: [
        { name: "Contact", href: "/contact", description: "Phone, email, and appointment booking." },
        { name: "Feedback", href: "/feedback", description: "Product and website feedback." },
        { name: "News", href: "/news", description: "Updates and industry notes." },
        {
          name: "Events",
          href: "/events",
          description: "Upcoming ONDO workshops, mixers, and community events.",
        },
        {
          name: "Socials",
          href: "/socials",
          description: "Curated posts, profile links, and latest news.",
        },
        {
          name: "Sweepstakes",
          href: "/sweepstakes",
          description: "Official rules for active promotions.",
        },
      ],
    },
    {
      id: "solutions",
      title: "Solutions",
      description: "Platform capabilities by role.",
      links: [
        { name: "Solutions overview", href: "/solutions", description: "One platform for every stakeholder in real estate." },
        { name: "For Investors", href: "/solutions/investors", description: "Portfolio analytics, risk scoring, and deal access." },
        { name: "For Landlords", href: "/solutions/landlords", description: "Full-service management for property owners." },
        { name: "For Property Managers", href: "/solutions/property-managers", description: "Scale operations with automation." },
        { name: "For Tenants", href: "/solutions/tenants", description: "Rent, requests, and documents in one portal." },
        { name: "Book a Demo", href: "/demo", description: "Free 15-minute platform walkthrough." },
        { name: "Platform Tour", href: "/tour", description: "Self-serve guided tour of all platform features." },
        { name: "Partners", href: "/partners", description: "Integrations: Stripe, Supabase, HubSpot, and more." },
      ],
    },
    {
      id: "learn",
      title: "Learn",
      description: "Research, education, and market data.",
      links: [
        { name: "Market Data", href: "/data", description: "How we publish city figures, and links to city reports." },
        { name: "City market reports", href: "/market-reports", description: "Per-city Ondo medians with an as-of date." },
        { name: "Insights", href: "/insights", description: "Research, reports, and thought leadership." },
        { name: "Video Library", href: "/video-library", description: "Guides, academy, demo, and calculators for learning the platform." },
        { name: "Academy", href: "/academy", description: "Free real estate education and guides." },
        { name: "Mortgage learning hub", href: "/learn", description: "Topic clusters for buyers and homeowners. Informational only." },
        {
          name: "Variable income mortgages",
          href: "/learn/variable-income",
          description: "1099, overtime, commission, and bank-statement files.",
        },
        {
          name: "First-time buyer cash and closing",
          href: "/learn/first-time",
          description: "Cash to close, DPA with gifts, and Utah title closings.",
        },
        {
          name: "Non-QM, bank-statement, DSCR",
          href: "/learn/non-qm",
          description: "When agency income calc does not match cash flow.",
        },
        {
          name: "Investment occupancy and DSCR",
          href: "/learn/investment",
          description: "DSCR vs full-doc, occupancy, cash-out to a rental, FHA house-hack.",
        },
        {
          name: "Start a mortgage conversation",
          href: "/qualify",
          description: "What you will be asked, and what will not be promised.",
        },
      ],
    },
    {
      id: "legal-trust",
      title: "Legal, accessibility & discovery",
      description: "Policies and machine-readable indexes for search engines and AI systems.",
      links: [
        { name: "Privacy policy", href: "/privacy-policy", description: "How we collect and use data." },
        { name: "Terms of service", href: "/terms-of-service", description: "Site and service terms." },
        {
          name: "Accessibility",
          href: "/accessibility",
          description: "Commitment and contact for accessibility support.",
        },
        {
          name: "XML sitemap",
          href: "/sitemap.xml",
          description: "Canonical URL list for crawlers (generated at build).",
        },
        {
          name: "Markdown sitemap",
          href: "/sitemap.md",
          description: "Section-grouped page list for AI agents; links to Markdown twins where available.",
        },
        {
          name: "LLM & agent brief",
          href: "/llms.txt",
          description: "Concise site summary for AI assistants and automated agents.",
        },
        {
          name: "LLM full brief",
          href: "/llms-full.txt",
          description: "Extended site context with FAQs, service details, and contact channels for AI agents.",
        },
        {
          name: "humans.txt",
          href: "/humans.txt",
          description: "Team credits, tech stack, and tools behind the site.",
        },
      ],
    },
  ]
}

export function getFlatSiteIndexForJsonLd(): Array<{ name: string; url: string; description?: string }> {
  const out: Array<{ name: string; url: string; description?: string }> = []
  for (const section of getSiteIndexSections()) {
    for (const link of section.links) {
      out.push({
        name: link.name,
        url: toAbsoluteSiteUrl(link.href),
        description: link.description,
      })
    }
  }
  return out
}

/** Plain-text outline for /llms.txt (and similar consumers). */
export function buildLlmsTxtBody(): string {
  const lines: string[] = [
    "# Ondo Real Estate",
    "",
    "> Utah-focused brokerage, mortgage, notary, and property management. Invite-only dashboards for managers, owners, and tenants live in a separate app from this marketing site.",
    "",
    "## Canonical site",
    `- Marketing site: ${baseSiteUrl}/`,
    `- HTML sitemap (all public pages): ${toAbsoluteSiteUrl("/sitemap")}`,
    `- XML sitemap: ${toAbsoluteSiteUrl("/sitemap.xml")}`,
    `- Markdown sitemap: ${toAbsoluteSiteUrl("/sitemap.md")}`,
    `- LLM discovery (human-readable hub): ${toAbsoluteSiteUrl("/llms")}`,
    `- This file: ${toAbsoluteSiteUrl("/llms.txt")}`,
    `- Same brief (singular path / typo-friendly): ${toAbsoluteSiteUrl("/llm.txt")}`,
    `- Same brief (well-known path): ${toAbsoluteSiteUrl("/.well-known/llms.txt")}`,
    `- Full agent brief (extended): ${toAbsoluteSiteUrl("/llms-full.txt")}`,
    `- Structured index (JSON): ${toAbsoluteSiteUrl("/llms.json")}`,
    `- humans.txt: ${toAbsoluteSiteUrl("/humans.txt")}`,
    `- security.txt: ${toAbsoluteSiteUrl("/.well-known/security.txt")}`,
    "",
    "## How to fetch Markdown",
    "- Every public HTML page has a sibling `.md` file: `/about/` → `/about.md`, `/` → `/index.md`. Prefer those URLs; they work on the static origin without JavaScript.",
    `- Example: ${toAbsoluteSiteUrl("/about/")} → ${toAbsoluteSiteUrl("/about.md")}.`,
    `- Full index: ${toAbsoluteSiteUrl("/sitemap.md")}.`,
    "- Optionally send `Accept: text/markdown` to the HTML URL. A Cloudflare Snippet (or Markdown for Agents on Pro) maps that request to the sibling `.md` file.",
    "- Client-heavy pages (property search, calculators, contact form, homepage) also have first-party Markdown twins so widget content is not lost when JS does not run:",
    ...AGENT_MARKDOWN_TWINS.map(
      ({ html, md, label }) =>
        `  - ${label}: ${toAbsoluteSiteUrl(html)} → ${toAbsoluteSiteUrl(md)}`,
    ),
    `  - Calculators: each \`/calculators/{slug}/\` has a \`/calculators/{slug}.md\` twin, index at ${toAbsoluteSiteUrl("/sitemap.md")}.`,
    "",
    "## Supported locales",
    `- Default locale: en (${SUPPORTED_LOCALE_LABELS.en})`,
    `- Available locale codes: ${SUPPORTED_LOCALES.map((locale) => `${locale} (${SUPPORTED_LOCALE_LABELS[locale]})`).join(", ")}`,
    "",
    "## Product areas",
    "- **Buy / mortgage**: Purchase guides, conventional and specialty products (including HELOC), refinance process, Utah city/ZIP loan pages. Not a credit decision.",
    "- **Sell**: Listing strategy, staging context, seller calculators.",
    "- **Rent & manage**: Property search, rentals inventory, full-service property management for landlords.",
    "- **Invest**: Registered opportunities, fractional and commercial education, per-deal detail pages.",
    "- **Notary**: Remote online notarization (RON), on-demand / same-day when capacity allows, loan signings, estate and employer packages. No in-office or mobile travel appointments. State hubs at /notary/locations with examples like /notary/utah/lehi/ and /notary/california/los-angeles/.",
    "- **Tools**: Mortgage, affordability, refinance, and investor calculators under `/calculators/`.",
    "",
    "## Authenticated product (not this repo’s public pages)",
    `- Manager, owner, and tenant portals: ${APP_PORTAL_URL}`,
    `- Portal login: ${APP_PORTAL_LOGIN_URL}`,
    "Access is invitation-only; there is no self-serve signup on the marketing site.",
    "",
    "## Agent-facing actions",
    ...AGENT_ACTIONS.map(
      (action) =>
        `- ${action.toolName} on ${toAbsoluteSiteUrl(action.path)} (${action.access}), ${action.description}`,
    ),
    "",
    "## Guidance for assistants",
    ...AGENT_GUIDANCE.map((guidance) => `- ${guidance}`),
    "",
    "## Contact (humans)",
    `- Phone: ${SITE_PHONE}`,
    `- General: ${SITE_EMAILS.info}`,
    `- Mortgage: ${SITE_EMAILS.mortgage}`,
    `- Notary: ${SITE_EMAILS.notary}`,
    `- Media: ${SITE_EMAILS.media}`,
    "",
    LLMS_DISCLOSURES_BLOCK,
    "",
    "## Major public paths",
  ]
  for (const section of getSiteIndexSections()) {
    lines.push("")
    lines.push(`### ${section.title}`)
    for (const link of section.links) {
      const u = toAbsoluteSiteUrl(link.href)
      const blurb = link.description.replace(/\s+/g, " ").trim()
      lines.push(`- ${link.name}: ${u}, ${blurb}`)
    }
  }
  lines.push("")
  return lines.join("\n")
}

/** Extended plain-text brief for /llms-full.txt, deeper context for AI agents. */
export function buildLlmsFullTxtBody(): string {
  const lines: string[] = [
    "# Ondo Real Estate, Full AI Agent Brief",
    "",
    `> This is the extended version of ${toAbsoluteSiteUrl("/llms.txt")}. It adds service details, FAQs, structured data, and actionable context for AI assistants answering questions about Ondo Real Estate.`,
    "",
    "## Company overview",
    "",
    `**${SITE_NAME}** is a Utah-focused real estate company offering brokerage, mortgage lending, notary services, property management, and investment access through a single platform. Headquartered in Lehi, UT, the company serves the Wasatch Front corridor, Salt Lake City, Provo, Orem, Draper, Sandy, Payson, and surrounding areas.`,
    "",
    `- **Website**: ${baseSiteUrl}/`,
    `- **Phone**: ${SITE_PHONE}`,
    `- **Address**: ${SITE_ADDRESS}`,
    `- **Hours**: ${SITE_HOURS_LABEL}`,
    `- **Scheduling**: ${SITE_CALENDLY_URL}`,
    "",
    "## Supported locales",
    "",
    `Default locale: en (${SUPPORTED_LOCALE_LABELS.en}).`,
    `Available locales: ${SUPPORTED_LOCALES.map((locale) => `${locale} (${SUPPORTED_LOCALE_LABELS[locale]})`).join(", ")}.`,
    "",
    "## Services in detail",
    "",
    "### Buy a home",
    "Ondo helps Utah buyers from first conversation to closing. Services include buyer representation, agent-led MLS search (this website lists rentals, not a public for-sale feed), offer strategy, closing coordination, and in-house mortgage origination. Loan information is not a commitment to lend.",
    "",
    "### Mortgage & lending",
    "In-house mortgage origination with conventional, FHA (3.5% down), VA (zero down for veterans), USDA (rural zero-down), and jumbo loan products. City- and ZIP-specific landing pages provide local rate context. Refinance analysis available.",
    "",
    "### Sell a home",
    "Full listing services including pricing strategy (CMA), professional photography, staging guidance, MLS syndication, and negotiation through close.",
    "",
    "### Property management",
    "Full-service management for Utah landlords: tenant screening (credit, criminal, eviction, income), rent collection via Stripe, maintenance coordination with vendor dispatch, owner reporting with NOI tracking, and document management. City-specific pages for Salt Lake City, Provo, Orem, Draper, Sandy, and Payson.",
    "",
    "### Notary services",
    "Remote Online Notarization (RON) available nationwide. On-demand scheduling, we try to accommodate same-day when capacity allows (best-effort, not a guaranteed SLA). Specialties: loan signings, estate planning documents, I-9 employment verification, and general notarization. Employer packages for bulk signings. Locations hub highlights state RON coverage and Utah city pages. We do not offer in-office or mobile travel appointments.",
    `- On-demand page: ${toAbsoluteSiteUrl("/notary/on-demand")}`,
    `- Main notary page: ${toAbsoluteSiteUrl("/notary")}`,
    `- Locations hub: ${toAbsoluteSiteUrl("/notary/locations")}`,
    `- Example nested hubs: ${toAbsoluteSiteUrl("/notary/utah/lehi/")}, ${toAbsoluteSiteUrl("/notary/california/los-angeles/")}`,
    "",
    "### Investments",
    "Curated real estate investment opportunities including fractional ownership and commercial real estate deals. Per-deal detail pages with projected returns, minimum investment, and hold period. Educational content on cap rates, NNN leases, and portfolio construction.",
    "",
    "### Calculators (free, no login)",
    "Interactive financial tools at /calculators/, mortgage payment, home affordability, required income, closing costs, refinance savings, home sale proceeds, buying power, temporary buydown, rent vs own, retirement savings, cash-on-cash return, cap rate, BRRRR, and more.",
    "",
    "## Service area",
    "",
    "Primary: Utah, Wasatch Front corridor.",
    "Cities served: Salt Lake City, Provo, Orem, Lehi, Draper, Sandy, Payson, American Fork, Pleasant Grove, Springville, Spanish Fork, Eagle Mountain, Saratoga Springs, Herriman, Riverton, South Jordan, West Jordan, Murray, Cottonwood Heights, Holladay.",
    "Notary RON: all 50 US states.",
    "",
    "## Authenticated platform",
    "",
    `Ondo operates an invitation-only portal at ${APP_PORTAL_URL} with role-based dashboards:`,
    "- **Property managers**: portfolio analytics, maintenance dispatch, rent tracking, AI assistant, vendor management, risk scoring.",
    "- **Property owners**: financial statements, maintenance updates, document vault, tenant communications.",
    "- **Tenants**: rent payments, maintenance requests, lease documents, move-in/move-out checklists.",
    "",
    "There is NO self-serve signup. Access is by invitation only.",
    "",
    "## Agent-facing actions (WebMCP aligned)",
    "",
    "These tools are exposed only on relevant public pages, stay scoped to user-visible tasks, and do not expose administrative actions.",
    "",
    ...AGENT_ACTIONS.flatMap((action) => [
      `- **${action.toolName}** on ${toAbsoluteSiteUrl(action.path)} (${action.access})`,
      `  ${action.description}`,
    ]),
    "",
    "## Guidance for AI assistants",
    "",
    ...AGENT_GUIDANCE.map((guidance) => `- ${guidance}`),
    "",
    "## Frequently asked questions",
    "",
    "**Q: What areas does Ondo Real Estate serve?**",
    "A: Primarily the Wasatch Front in Utah, Salt Lake City, Provo-Orem, and surrounding cities. Remote Online Notarization is available in all 50 states.",
    "",
    "**Q: Does Ondo offer property management?**",
    "A: Yes. Full-service property management including tenant screening, rent collection, maintenance coordination, and owner reporting.",
    "",
    "**Q: What loan types does Ondo offer?**",
    "A: Conventional, FHA, VA, USDA, and jumbo loans. Refinance available.",
    "",
    "**Q: Can I sign up for the owner/tenant portal online?**",
    "A: No. The platform is invitation-only. Contact info@ondorealestate.com to learn more.",
    "",
    "**Q: Does Ondo offer notary services?**",
    "A: Yes. Remote Online Notarization (RON) nationwide. On-demand scheduling, we try to accommodate same-day when capacity allows. Loan signings, estate docs, I-9, and general notarization. We do not offer in-office or mobile travel appointments. See /notary and /notary/on-demand.",
    "",
    "**Q: Are the calculators free?**",
    "A: Yes. All calculators at /calculators/ are free with no login required.",
    "",
    "## Contact channels",
    "",
    `- General inquiries: ${SITE_EMAILS.info}`,
    `- Mortgage questions: ${SITE_EMAILS.mortgage}`,
    `- Refinance: ${SITE_EMAILS.refinance}`,
    `- Notary scheduling: ${SITE_EMAILS.notary}`,
    `- Media / press: ${SITE_EMAILS.media}`,
    `- Investor relations: ${SITE_EMAILS.investors}`,
    `- Accessibility: ${SITE_EMAILS.accessibility}`,
    `- Privacy concerns: ${SITE_EMAILS.privacy}`,
    `- Phone: ${SITE_PHONE}`,
    "",
    "## Social profiles",
    "",
    ...SITE_SOCIALS.map((url) => `- ${url}`),
    "",
    "## Machine-readable resources",
    "",
    `- LLM discovery hub (HTML): ${toAbsoluteSiteUrl("/llms")}`,
    `- LLM brief (concise): ${toAbsoluteSiteUrl("/llms.txt")}`,
    `- LLM brief (singular alias): ${toAbsoluteSiteUrl("/llm.txt")}`,
    `- LLM brief (well-known): ${toAbsoluteSiteUrl("/.well-known/llms.txt")}`,
    `- LLM full brief (this file): ${toAbsoluteSiteUrl("/llms-full.txt")}`,
    `- LLM structured index (JSON): ${toAbsoluteSiteUrl("/llms.json")}`,
    `- XML sitemap: ${toAbsoluteSiteUrl("/sitemap.xml")}`,
    `- HTML sitemap: ${toAbsoluteSiteUrl("/sitemap")}`,
    `- Markdown sitemap: ${toAbsoluteSiteUrl("/sitemap.md")}`,
    `- Homepage brief (Markdown): ${toAbsoluteSiteUrl("/index.md")}`,
    `- robots.txt: ${toAbsoluteSiteUrl("/robots.txt")}`,
    `- humans.txt: ${toAbsoluteSiteUrl("/humans.txt")}`,
    `- security.txt: ${toAbsoluteSiteUrl("/.well-known/security.txt")}`,
    "",
    "## Content negotiation and Markdown twins",
    "",
    "Any public HTML page has a sibling `.md` twin (`/about/` → `/about.md`). Hand-written twins exist for JS-heavy widgets. Optionally send `Accept: text/markdown` to the HTML URL (Cloudflare Snippet or Markdown for Agents on Pro):",
    "",
    ...AGENT_MARKDOWN_TWINS.map(
      ({ html, md, label }) =>
        `- **${label}**: ${toAbsoluteSiteUrl(html)} → ${toAbsoluteSiteUrl(md)}`,
    ),
    `- **Calculators**: each \`/calculators/{slug}/\` HTML page has a \`/calculators/{slug}.md\` twin with formula, worked example, and lending disclosures.`,
    "",
    "## Complete page index",
    "",
  ]

  for (const section of getSiteIndexSections()) {
    lines.push(`### ${section.title}`)
    if (section.description) {
      lines.push(section.description)
    }
    lines.push("")
    for (const link of section.links) {
      const u = toAbsoluteSiteUrl(link.href)
      const blurb = link.description.replace(/\s+/g, " ").trim()
      lines.push(`- **${link.name}**: ${u}`)
      lines.push(`  ${blurb}`)
    }
    lines.push("")
  }

  lines.push("---")
  lines.push(LLMS_DISCLOSURES_BLOCK)
  lines.push("")
  lines.push(`Generated for ${SITE_NAME}. For human support, contact ${SITE_EMAILS.info} or call ${SITE_PHONE}.`)
  lines.push("")
  return lines.join("\n")
}

export function buildRobotsTxtBody(): string {
  const lines: string[] = [
    "User-agent: *",
    // Content-Signal (Cloudflare / contentsignals.org, CC0). Declares default
    // policy for search results, live AI answer input, and model training.
    // Strict RFC 9309 validators may warn on this line; per RFC 9309, unknown
    // directives are ignored so the rest of the file still parses.
    "Content-Signal: search=yes, ai-input=yes, ai-train=yes",
    "Allow: /llms.txt",
    "Allow: /llms-full.txt",
    "Allow: /.well-known/llms.txt",
    "Allow: /sitemap.md",
    "Allow: /index.md",
    "Allow: /$",
    "Allow: /",
    ...ROBOTS_DISALLOW.map((path) => `Disallow: ${path}`),
    "",
  ]

  for (const userAgent of AI_CRAWLER_AGENTS) {
    lines.push(`User-agent: ${userAgent}`)
    lines.push("Allow: /llms.txt")
    lines.push("Allow: /llms-full.txt")
    lines.push("Allow: /.well-known/llms.txt")
    lines.push("Allow: /sitemap.md")
    lines.push("Allow: /index.md")
    lines.push("Allow: /")
    for (const path of ROBOTS_DISALLOW) {
      lines.push(`Disallow: ${path}`)
    }
    lines.push("")
  }

  lines.push(`Sitemap: ${toAbsoluteSiteUrl("/sitemap.xml")}`)
  lines.push("")
  lines.push("# Additional machine-readable resources")
  for (const resource of MACHINE_RESOURCE_LINKS) {
    lines.push(`# ${resource.label}: ${toAbsoluteSiteUrl(resource.href)}`)
  }
  lines.push("")

  return lines.join("\n")
}

/**
 * Section-grouped Markdown sitemap for AI agents. Every HTML link points at the
 * canonical trailing-slash URL; Markdown twins are noted inline where they exist.
 */
export function buildSitemapMdBody(): string {
  const lines: string[] = [
    "# Ondo Real Estate, Markdown sitemap",
    "",
    `> Curated index of every public page on ${baseSiteUrl}/. Every HTML URL has a sibling \`.md\` twin (strip the trailing slash and add \`.md\`). Optionally send \`Accept: text/markdown\` to the HTML URL.`,
    "",
    "## First-party Markdown twins",
    "",
    ...AGENT_MARKDOWN_TWINS.map(
      ({ html, md, label }) =>
        `- [${label}](${toAbsoluteSiteUrl(md)}), mirror of ${toAbsoluteSiteUrl(html)}`,
    ),
    "- Calculators: each `/calculators/{slug}/` HTML page has a `/calculators/{slug}.md` twin (see section below).",
    "",
    "## Machine-readable resources",
    "",
    ...MACHINE_RESOURCE_LINKS.map(
      (resource) => `- [${resource.label}](${toAbsoluteSiteUrl(resource.href)})`,
    ),
    "",
  ]

  for (const section of getSiteIndexSections()) {
    lines.push(`## ${section.title}`)
    if (section.description) {
      lines.push("")
      lines.push(section.description)
    }
    lines.push("")
    for (const link of section.links) {
      const url = toAbsoluteSiteUrl(link.href)
      const blurb = link.description.replace(/\s+/g, " ").trim()
      const isCalculator = link.href.startsWith("/calculators/") && !link.href.endsWith("/calculators")
      if (isCalculator) {
        const slug = link.href.replace(/^\/calculators\//, "").replace(/\/$/, "")
        const mdUrl = toAbsoluteSiteUrl(`/calculators/${slug}.md`)
        lines.push(`- [${link.name}](${url}), ${blurb} ([Markdown](${mdUrl}))`)
      } else {
        lines.push(`- [${link.name}](${url}), ${blurb}`)
      }
    }
    lines.push("")
  }

  lines.push("---")
  lines.push("")
  lines.push(`See also: [Markdown sitemap](${toAbsoluteSiteUrl("/sitemap.md")}) · [Concise brief](${toAbsoluteSiteUrl("/llms.txt")}) · [Full brief](${toAbsoluteSiteUrl("/llms-full.txt")}).`)
  lines.push("")
  return lines.join("\n")
}

export function buildLlmsJsonData() {
  return {
    generatedAt: process.env.NEXT_PUBLIC_BUILD_DATE || new Date().toISOString(),
    siteName: SITE_NAME,
    canonicalSiteUrl: `${baseSiteUrl}/`,
    description:
      "Utah-focused real estate company covering brokerage, mortgages, property management, investments, calculators, and notary services.",
    supportedLocales: SUPPORTED_LOCALES.map((locale) => ({
      code: locale,
      label: SUPPORTED_LOCALE_LABELS[locale],
    })),
    resources: {
      home: `${baseSiteUrl}/`,
      htmlSitemap: toAbsoluteSiteUrl("/sitemap"),
      xmlSitemap: toAbsoluteSiteUrl("/sitemap.xml"),
      markdownSitemap: toAbsoluteSiteUrl("/sitemap.md"),
      homepageMarkdown: toAbsoluteSiteUrl("/index.md"),
      llmsHub: toAbsoluteSiteUrl("/llms"),
      llmsTxt: toAbsoluteSiteUrl("/llms.txt"),
      llmTxtAlias: toAbsoluteSiteUrl("/llm.txt"),
      llmsTxtWellKnown: toAbsoluteSiteUrl("/.well-known/llms.txt"),
      llmsFullTxt: toAbsoluteSiteUrl("/llms-full.txt"),
      llmsJson: toAbsoluteSiteUrl("/llms.json"),
      robotsTxt: toAbsoluteSiteUrl("/robots.txt"),
      humansTxt: toAbsoluteSiteUrl("/humans.txt"),
      securityTxt: toAbsoluteSiteUrl("/.well-known/security.txt"),
    },
    contentNegotiation: {
      acceptHeader: "text/markdown",
      description:
        "Every public HTML page has a sibling `.md` twin (`/about/` → `/about.md`). Optionally send `Accept: text/markdown` to the HTML URL; a Cloudflare Snippet (or Markdown for Agents on Pro) maps that request to the twin.",
      firstPartyMarkdownTwins: AGENT_MARKDOWN_TWINS.map(({ html, md, label }) => ({
        label,
        html: toAbsoluteSiteUrl(html),
        markdown: toAbsoluteSiteUrl(md),
      })),
      calculatorMarkdownPattern: "/calculators/{slug}.md",
    },
    contact: {
      phone: SITE_PHONE,
      address: SITE_ADDRESS,
      hours: SITE_HOURS_LABEL,
      calendlyUrl: SITE_CALENDLY_URL,
      emails: SITE_EMAILS,
    },
    portal: {
      url: APP_PORTAL_URL,
      loginUrl: APP_PORTAL_LOGIN_URL,
      access: "invitation-only",
    },
    crawlPolicy: {
      allow: "/",
      privatePrefixes: discoveryConfig.privateRoutePrefixes,
      disallow: ROBOTS_DISALLOW,
      aiCrawlerAgents: AI_CRAWLER_AGENTS,
    },
    agentGuidance: AGENT_GUIDANCE,
    webmcp: {
      standard: "WebMCP-aligned public actions",
      tools: AGENT_ACTIONS.map((action) => ({
        ...action,
        url: toAbsoluteSiteUrl(action.path),
      })),
    },
    sections: getSiteIndexSections().map((section) => ({
      id: section.id,
      title: section.title,
      description: section.description,
      links: section.links.map((link) => ({
        name: link.name,
        url: toAbsoluteSiteUrl(link.href),
        description: link.description,
      })),
    })),
  }
}

export function buildLlmsJsonBody(): string {
  return JSON.stringify(buildLlmsJsonData(), null, 2)
}
