import { CALCULATOR_CATALOG } from "@/lib/calculator-catalog"
import { getBlogPosts } from "@/lib/blog-posts"
import agentDiscoveryConfig from "@/lib/agent-discovery-config.json"
import { SUPPORTED_LOCALES, SUPPORTED_LOCALE_LABELS } from "@/lib/locales"
import {
  APP_PORTAL_LOGIN_URL,
  APP_PORTAL_URL,
  SITE_CALENDLY_URL,
  SITE_ADDRESS,
  SITE_EMAILS,
  SITE_HOURS_LABEL,
  SITE_NAME,
  SITE_PHONE,
  SITE_SOCIALS,
  SITE_URL,
  nmlsIdentification,
} from "@/lib/site"
import { glossaryHref, sortedGlossaryTerms } from "@/lib/content/glossary"
import { toAbsoluteSiteUrl, toSitePath } from "@/lib/url"

// Re-exported so existing importers keep working; the implementations live in the leaf lib/url.ts.
export { toAbsoluteSiteUrl, toSitePath }

const baseSiteUrl = SITE_URL.replace(/\/$/, "")
const discoveryConfig = agentDiscoveryConfig as {
  privateRoutePrefixes: string[]
  extraDisallow: string[]
  aiCrawlerAgents: string[]
}

export const ROBOTS_DISALLOW = [...discoveryConfig.privateRoutePrefixes, ...discoveryConfig.extraDisallow]
export const AI_CRAWLER_AGENTS = discoveryConfig.aiCrawlerAgents

const MACHINE_RESOURCE_LINKS = [
  { label: "HTML sitemap", href: "/sitemap" },
  { label: "XML sitemap", href: "/sitemap.xml" },
  { label: "Markdown sitemap", href: "/sitemap.md" },
  { label: "LLM discovery hub", href: "/llms" },
  { label: "LLM brief", href: "/llms.txt" },
  { label: "LLM brief (alias)", href: "/llm.txt" },
  { label: "LLM brief (well-known)", href: "/.well-known/llms.txt" },
  { label: "LLM full brief", href: "/llms-full.txt" },
  { label: "LLM structured index", href: "/llms.json" },
  { label: "Site overview (Markdown)", href: "/index.md" },
  { label: "AI agent manifest", href: "/.well-known/agents.json" },
  { label: "robots.txt", href: "/robots.txt" },
  { label: "humans.txt", href: "/humans.txt" },
  { label: "security.txt", href: "/.well-known/security.txt" },
] as const

/**
 * First-party Markdown twins for JS-heavy pages where Cloudflare's on-the-fly
 * HTML → Markdown conversion would return an empty shell (client-only widgets,
 * dynamic imports with `ssr: false`). Every listed HTML path must have a
 * matching `.md` file generated by `scripts/generate-agent-markdown.ts` into
 * `public/` at build time.
 */
export const AGENT_MARKDOWN_TWINS: ReadonlyArray<{ html: string; md: string; label: string }> = [
  { html: "/", md: "/index.md", label: "Homepage brief" },
  { html: "/sitemap", md: "/sitemap.md", label: "Markdown sitemap" },
  { html: "/properties", md: "/properties.md", label: "Property search brief" },
  { html: "/contact", md: "/contact.md", label: "Contact brief" },
]

type AgentAction = {
  path: string
  toolName: string
  access: "read-only" | "confirmed-submit"
  description: string
}

const AGENT_ACTIONS: AgentAction[] = [
  {
    path: "/contact",
    toolName: "submit_contact_lead",
    access: "confirmed-submit",
    description:
      "Submit a contact lead for property management, investment, leasing, or general inquiries after explicit user confirmation.",
  },
  {
    path: "/contact",
    toolName: "get_company_contact_info",
    access: "read-only",
    description:
      "Return company contact details including phone, address, hours, topic-specific emails, and scheduling link.",
  },
  {
    path: "/investments/opportunities",
    toolName: "list_investment_opportunities",
    access: "read-only",
    description: "List the sample investment deal cards. They are illustrations, not live offerings.",
  },
  {
    path: "/investments/opportunities",
    toolName: "get_investment_opportunity",
    access: "read-only",
    description: "Return full details for one sample investment deal by slug. It is an illustration, not a live offering.",
  },
  {
    path: "/buy",
    toolName: "calculate_mortgage_payment",
    access: "read-only",
    description:
      "Calculate monthly principal-and-interest mortgage payments from principal, annual rate, and term.",
  },
  {
    path: "/properties",
    toolName: "search_available_properties",
    access: "read-only",
    description:
      "Search current Utah rental listings by city, bedrooms, max rent, or free text.",
  },
  {
    path: "/properties",
    toolName: "search_listings_by_text",
    access: "read-only",
    description: "Filter or open listings from the on-page search box by city, address, or name.",
  },
  {
    path: "/",
    toolName: "lookup_utah_zip_services",
    access: "read-only",
    description: "Look up Ondo services available for a Utah ZIP code along the Wasatch Front.",
  },
]

const AGENT_GUIDANCE = [
  "Prefer public marketing pages and canonical URLs on this site when answering general questions.",
  "Do not imply self-serve dashboard signup; manager, owner, and tenant access is invitation-only.",
  "Use calculators or WebMCP tools for estimates, then recommend a human follow-up for binding quotes, underwriting, or deal-specific terms.",
  "Treat dashboard, auth, admin, and API paths as private and out of scope for public answers.",
  "The on-site AI assistant is informational only. It is not a loan officer, appraiser, attorney, or underwriter, and it does not approve credit.",
  "Do not fetch a per-city index.txt tree. Those files are framework internals, not content; use /llms.txt and /llms-full.txt.",
] as const

/**
 * Required lending / brokerage / Fair Housing / AI disclosures for machine-readable
 * briefs. Wording is copied from OndoREBackend `src/utils/disclosures.ts` (lending,
 * realEstate, valuation, aiGenerated, notLegalAdvice) plus the footer Equal Housing
 * line. Do not invent NMLS or brokerage license numbers, the backend uses
 * `NMLS ID on file` when ONDO_NMLS_ID is unset; this static site does the same.
 */
export const LLMS_DISCLOSURES_BLOCK = [
  "## Required disclosures",
  "",
  `Loan information is provided by Ondo Real Estate (${nmlsIdentification()}). This is not a commitment to lend, a loan approval, or an offer of credit. Rates, terms, and payments shown are estimates for illustration only, are not a quote, and are subject to credit approval, underwriting, and market conditions. Equal Housing Lender.`,
  "",
  "Real estate services provided by Ondo Real Estate. Information is deemed reliable but is not guaranteed and should be independently verified. Equal Housing Opportunity.",
  "",
  "Automated home-value or rent figures on this site are estimates generated from available data. They are not an appraisal, a broker price opinion, or a comparative market analysis, and should not be relied upon as a statement of value.",
  "",
  "The on-site AI assistant is informational only. Replies are generated by an automated assistant and may contain errors. This information is general in nature and is not legal, tax, or financial advice. Please verify important details with a member of the Ondo Real Estate team.",
  "",
  "Licensed activity: real estate brokerage and mortgage origination are marketed for Utah. Remote online notarization (RON) is offered nationwide. Confirm current licensure with Ondo before relying on a service in a given state.",
].join("\n")

export type SiteIndexLink = {
  name: string
  href: string
  description: string
}

export type SiteIndexSection = {
  id: string
  title: string
  description?: string
  links: SiteIndexLink[]
}

/**
 * Blog links come from lib/blog-posts.ts, which lists exactly the indexable posts (its test fails
 * when an indexable post is missing or a noindexed one is listed). A separate hand-typed list here
 * had drifted and pulled retired, noindexed posts back into the sitemap.
 */
function allBlogIndexLinks(): SiteIndexLink[] {
  return getBlogPosts().map((post) => ({
    name: post.title,
    href: `/blog/${post.slug}`,
    description: post.excerpt,
  }))
}

function calculatorLinks(): SiteIndexLink[] {
  return Object.entries(CALCULATOR_CATALOG).map(([slug, meta]) => ({
    name: meta.name,
    href: `/calculators/${slug}`,
    description: meta.description,
  }))
}

function glossaryLinks(): SiteIndexLink[] {
  return sortedGlossaryTerms().map((entry) => ({
    name: entry.term,
    href: glossaryHref(entry.slug).replace(/\/$/, ""),
    description: entry.short,
  }))
}

/** Every listed page with its name and description, grouped as originally written. */
function catalogSections(): SiteIndexSection[] {
  return [
    {
      id: "home-company",
      title: "Home & company story",
      description: "Start here for who we are and why we focus on Utah.",
      links: [
        {
          name: "Home",
          href: "/",
          description: "Ondo Real Estate, buy, sell, finance, manage, and notarize with one partner.",
        },
        {
          name: "Founders letter",
          href: "/founders-letter",
          description: "Why we built Ondo and how we work with owners and residents.",
        },
        {
          name: "Why Utah",
          href: "/why-utah",
          description: "Economy, quality of life, and real estate context in Utah.",
        },
        {
          name: "New to Utah",
          href: "/moving-to-utah",
          description: "Commute minutes and typical rents for a Wasatch Front start date.",
        },
      ],
    },
    {
      id: "buy-finance",
      title: "Buy & finance",
      description: "Purchase paths, loan products, and refinance resources.",
      links: [
        { name: "Buy a home", href: "/buy", description: "Purchase overview and next steps." },
        {
          name: "First-time home buyer",
          href: "/buy/first-time",
          description: "Programs and guidance for first-time buyers.",
        },
        {
          name: "Housing grants",
          href: "/buy/first-time/grants",
          description: "Down payment assistance and homebuyer grant programs.",
        },
        {
          name: "Second home",
          href: "/buy/second-home",
          description: "Financing and considerations for a second residence.",
        },
        { name: "Mortgage rates hub", href: "/buy/rates", description: "Rate context and how we quote." },
        {
          name: "Fixed-rate mortgages",
          href: "/buy/fixed-rate",
          description: "Predictable payments with fixed-rate loans.",
        },
        {
          name: "Adjustable-rate mortgages",
          href: "/buy/adjustable-rate",
          description: "ARM structure, caps, and when it can fit.",
        },
        { name: "30-year mortgage", href: "/buy/30-year", description: "Lower payment, longer amortization." },
        { name: "15-year mortgage", href: "/buy/15-year", description: "Build equity faster with a shorter term." },
        {
          name: "Mortgage loans",
          href: "/loans",
          description: "Loan products including HELOC/HELOAN and Utah lending guidance (not a credit decision).",
        },
        {
          name: "Conventional loans",
          href: "/loans/conventional",
          description: "Conforming conventional purchase and refinance.",
        },
        {
          name: "FHA loans",
          href: "/loans/fha",
          description: "Minimum down payment and credit requirements depend on the program. Financing for Utah buyers who qualify.",
        },
        {
          name: "VA loans",
          href: "/loans/va",
          description: "Financing for eligible veterans and active-duty military in Utah. Down payment depends on eligibility.",
        },
        {
          name: "USDA loans",
          href: "/loans/usda",
          description: "Financing in eligible Utah rural areas including Cache Valley and Sanpete County. Down payment depends on eligibility.",
        },
        {
          name: "Jumbo loans",
          href: "/loans/jumbo",
          description: "Financing above conforming limits for Park City, Draper, and Utah's high-value markets.",
        },
        {
          name: "Refinance overview",
          href: "/refinance",
          description: "Rate-and-term vs cash-out refinancing in Utah and when each makes sense.",
        },
        {
          name: "Refinance process",
          href: "/refinance/process",
          description: "Steps and timeline to refinance with Ondo.",
        },
      ],
    },
    {
      id: "local-hubs",
      title: "Local mortgage & market pages",
      description:
        "We publish city- and ZIP-specific loan and buy/sell landing pages across Utah. Browse examples below or start from the hubs.",
      links: [
        { name: "Loans in Salt Lake City", href: "/loans/salt-lake-city", description: "Local mortgage context for SLC." },
        { name: "Loans in Lehi", href: "/loans/lehi", description: "Silicon Slopes and Utah County lending." },
        { name: "Loans in Provo", href: "/loans/provo", description: "Purchase and refinance in Provo." },
        { name: "Loans in Draper", href: "/loans/draper", description: "South Valley loan resources." },
        {
          name: "Buy & sell by city",
          href: "/buy-sell",
          description: "Wasatch Front city hub for buying and selling; statewide process lives on /buy and /sell.",
        },
        {
          name: "Buy/sell by city (example: Lehi)",
          href: "/buy-sell/lehi",
          description: "Hyper-local buy and sell snapshot; more cities available via URL pattern.",
        },
        {
          name: "Buy/sell by ZIP (example: 84043)",
          href: "/buy-sell/zip/84043",
          description: "ZIP-level market hub; substitute other Utah ZIPs in the path.",
        },
        {
          name: "City market reports",
          href: "/market-reports",
          description: "Index of Ondo city medians. Not an MLS pull or appraisal.",
        },
        {
          name: "Neighborhood guides",
          href: "/neighborhoods",
          description: "Named neighborhood pages: housing stock and amenities, not resident profiles.",
        },
        {
          name: "School district guides",
          href: "/schools",
          description: "District directory with official site links. Not a ranking.",
        },
      ],
    },
    {
      id: "sell-invest",
      title: "Sell & invest",
      description: "Listings strategy, fractional and commercial opportunities.",
      links: [
        { name: "Sell your home", href: "/sell", description: "Pricing, prep, and listing with Ondo." },
        { name: "Investments overview", href: "/investments", description: "How commercial and fractional investing works." },
        {
          name: "Sample investment deals",
          href: "/investments/opportunities",
          description: "Illustrations of how a deal page could look. Not live offerings.",
        },
        {
          name: "Fractional real estate",
          href: "/investments/fractional",
          description: "Lower minimums and diversified exposure.",
        },
        {
          name: "Commercial real estate",
          href: "/investments/commercial-real-estate",
          description: "CRE education and sponsor-led deals.",
        },
        {
          name: "Opportunity zones",
          href: "/investments/opportunity-zones",
          description: "Capital-gains deferral via Qualified Opportunity Zone tracts.",
        },
        {
          name: "Investment strategy",
          href: "/strategy",
          description: "How Ondo identifies, acquires, and manages value-add Utah properties.",
        },
        {
          name: "New investors",
          href: "/new-investors",
          description: "Getting started with passive income and long-term wealth in Utah real estate.",
        },
        {
          name: "Investor overview",
          href: "/brochure",
          description: "Request the investor overview: strategy, track record, team, and approach.",
        },
      ],
    },
    {
      id: "rent-manage",
      title: "Rent, search & property management",
      description: "Tenant-facing discovery and owner/manager services.",
      links: [
        {
          name: "Property search",
          href: "/properties",
          description: "Filter rentals we manage. For-sale search is agent-led on /buy.",
        },
        {
          name: "Properties",
          href: "/properties",
          description: "Featured homes and apartments available now.",
        },
        {
          name: "Property management",
          href: "/property-management",
          description: "Full-service management for Utah landlords.",
        },
        {
          name: "Pricing",
          href: "/pricing",
          description: "Transparent percentage-based property management plans.",
        },
        {
          name: "Explore listings on a map",
          href: "/explore",
          description: "Map view of homes and rentals available now.",
        },
        {
          name: "Compare property management software",
          href: "/compare",
          description: "Ondo RE vs Buildium, AppFolio, TurboTenant, and RentRedi.",
        },
        {
          name: "Utah property management companies compared",
          href: "/compare-utah-property-managers",
          description: "Side-by-side fees, tech, and services across Utah managers.",
        },
        {
          name: "Ondo RE vs Buildium",
          href: "/vs/buildium",
          description: "Price, features, AI tools, and tenant experience compared.",
        },
        {
          name: "Ondo RE vs TurboTenant",
          href: "/vs/turbotenant",
          description: "Risk scoring, calculators, roles, and PWA compared.",
        },
        {
          name: "Tenant screening",
          href: "/property-management/tenant-screening",
          description: "Credit, criminal, eviction, and income verification for Utah rental applicants.",
        },
        {
          name: "Maintenance coordination",
          href: "/property-management/maintenance-coordination",
          description: "End-to-end maintenance request intake, vendor dispatch, and completion tracking.",
        },
        {
          name: "Owner reporting",
          href: "/property-management/owner-reporting",
          description: "Monthly statements, NOI tracking, disbursement history, and document vault.",
        },
        {
          name: "Resources",
          href: "/resources",
          description: "Guides, downloads, and checklists for owners and renters.",
        },
        {
          name: "Templates & forms",
          href: "/resources/templates",
          description: "Utah-compliant landlord templates: lease, move-in checklist, maintenance form, and playbook.",
        },
        {
          name: "PM in Salt Lake City",
          href: "/property-management/salt-lake-city",
          description: "Full-service property management in Salt Lake City, UT.",
        },
        {
          name: "PM in Provo",
          href: "/property-management/provo",
          description: "Rental management serving Provo neighborhoods and BYU area.",
        },
        {
          name: "PM in Orem",
          href: "/property-management/orem",
          description: "Rental management in Orem, Utah County.",
        },
        {
          name: "PM in Draper",
          href: "/property-management/draper",
          description: "Property management in Draper, near Silicon Slopes.",
        },
        {
          name: "PM in Sandy",
          href: "/property-management/sandy",
          description: "Sandy rental property management and tenant placement.",
        },
        {
          name: "PM in Payson",
          href: "/property-management/payson",
          description: "Property management in Payson and southern Utah County.",
        },
      ],
    },
    {
      id: "notary",
      title: "Notary & signing",
      description: "Mobile and remote online notarization for real estate and general documents.",
      links: [
        {
          name: "Notary services",
          href: "/notary",
          description: "RON, loan signings, estate packages, and mobile coverage.",
        },
        {
          name: "On-demand notary",
          href: "/notary/on-demand",
          description: "Urgent and same-day when capacity allows, RON or mobile.",
        },
        {
          name: "Notary locations",
          href: "/notary/locations/",
          description: "State hubs for nationwide RON.",
        },
        {
          name: "Remote online notary in Utah",
          href: "/notary/utah/",
          description: "Utah RON hub + Wasatch cities.",
        },
        {
          name: "Remote online notary in California",
          href: "/notary/california/",
          description: "California RON hub.",
        },
      ],
    },
    {
      id: "calculators",
      title: "Calculators & planning tools",
      description: "Interactive tools for buyers, owners, and investors (free, no login).",
      links: [
        {
          name: "All calculators",
          href: "/calculators",
          description: "Directory of mortgage and investment calculators.",
        },
        ...calculatorLinks(),
      ],
    },
    {
      id: "glossary",
      title: "Glossary",
      description: "Plain-English definitions for the terms used across buying, lending, investing, leasing, and closing.",
      links: [
        {
          name: "Real estate glossary",
          href: "/glossary",
          description: "Searchable index of every term, by topic and A–Z.",
        },
        ...glossaryLinks(),
      ],
    },
    {
      id: "faq",
      title: "FAQ",
      description: "Answers by topic for buyers, sellers, tenants, owners, and notary clients.",
      links: [
        { name: "FAQ home", href: "/faq", description: "All categories." },
        { name: "General FAQs", href: "/faq/general-faqs", description: "Cross-cutting questions." },
        { name: "Buying & selling FAQs", href: "/faq/buying-selling-faqs", description: "Transaction and offer questions." },
        { name: "Loan FAQs", href: "/faq/loans-faqs", description: "Qualification, rates, and products." },
        { name: "Loan payoff FAQs", href: "/faq/loan-payoffs-faqs", description: "Who to ask for a mortgage payoff." },
        { name: "Escrow FAQs", href: "/faq/escrow-faqs", description: "Closing and escrow timeline." },
        { name: "Payment FAQs", href: "/faq/payments-faqs", description: "How and when to pay." },
        { name: "Hardship FAQs", href: "/faq/hardship-faqs", description: "Where to get free help if you fall behind." },
        { name: "Disaster FAQs", href: "/faq/disaster-faqs", description: "Insurance and property damage." },
        { name: "Notary FAQs", href: "/faq/notary-faqs", description: "RON, I-9, and scheduling." },
        { name: "Owner FAQs", href: "/faq/owner-faqs", description: "Landlord and investor topics." },
        { name: "Tenant FAQs", href: "/faq/tenant-faqs", description: "Renting and lease questions." },
      ],
    },
    {
      id: "blog",
      title: "Blog & guides",
      description: "Long-form articles on Utah real estate, product, and operations.",
      links: [{ name: "Blog", href: "/blog", description: "Latest articles and filters by topic." }, ...allBlogIndexLinks()],
    },
    {
      id: "about",
      title: "About Ondo",
      description: "Team and case studies.",
      links: [
        { name: "About us", href: "/about", description: "Mission, services, and service area." },
        { name: "Team", href: "/about/team", description: "The founder of Ondo Real Estate." },
        { name: "Case studies", href: "/about/case-studies", description: "Illustrative scenarios for Utah owners, buyers, and investors." },
      ],
    },
    {
      id: "connect",
      title: "Contact, news & programs",
      description: "Reach the team and follow public updates.",
      links: [
        { name: "Contact", href: "/contact", description: "Phone, email, and appointment booking." },
        { name: "News", href: "/news", description: "Updates and industry notes." },
        {
          name: "Events",
          href: "/events",
          description: "Upcoming ONDO workshops, mixers, and community events.",
        },
        {
          name: "Socials",
          href: "/socials",
          description: "Profile links and news sources we follow.",
        },
        {
          name: "Subscribe",
          href: "/subscribe",
          description: "Utah market updates, owner tips, and Ondo news by email.",
        },
        {
          name: "Get matched",
          href: "/get-matched",
          description: "A 60-second quiz that routes you to the right Ondo service.",
        },
        {
          name: "Referral program",
          href: "/referral",
          description: "Invite a friend to Ondo RE and earn a free month.",
        },
      ],
    },
    {
      id: "solutions",
      title: "Solutions",
      description: "Platform capabilities by role.",
      links: [
        { name: "Solutions overview", href: "/solutions", description: "One platform for every stakeholder in real estate." },
        { name: "For Investors", href: "/solutions/investors", description: "Portfolio analytics, risk scoring, and deal access." },
        { name: "For Landlords", href: "/solutions/landlords", description: "Full-service management for property owners." },
        { name: "For Property Managers", href: "/solutions/property-managers", description: "Scale operations with automation." },
        { name: "For Tenants", href: "/solutions/tenants", description: "Rent, requests, and documents in one portal." },
        { name: "Book a Demo", href: "/demo", description: "Free 15-minute platform walkthrough." },
        { name: "Platform Tour", href: "/tour", description: "Self-serve guided tour of all platform features." },
        { name: "Partners", href: "/partners", description: "Integrations: Stripe, Supabase, HubSpot, and more." },
      ],
    },
    {
      id: "learn",
      title: "Learn",
      description: "Research, education, and market data.",
      links: [
        { name: "Market Data", href: "/data", description: "How we publish city figures, and links to city reports." },
        { name: "City market reports", href: "/market-reports", description: "Per-city Ondo medians with an as-of date." },
        { name: "Insights", href: "/insights", description: "Research, reports, and thought leadership." },
        { name: "Video Library", href: "/video-library", description: "Guides, academy, demo, and calculators for learning the platform." },
        { name: "Academy", href: "/academy", description: "Free real estate education and guides." },
        { name: "Mortgage learning hub", href: "/learn", description: "Topic clusters for buyers and homeowners. Informational only." },
        {
          name: "Variable income mortgages",
          href: "/learn/variable-income",
          description: "1099, overtime, commission, and bank-statement files.",
        },
        {
          name: "First-time buyer cash and closing",
          href: "/learn/first-time",
          description: "Cash to close, DPA with gifts, and Utah title closings.",
        },
        {
          name: "Non-QM, bank-statement, DSCR",
          href: "/learn/non-qm",
          description: "When agency income calc does not match cash flow.",
        },
        {
          name: "Investment occupancy and DSCR",
          href: "/learn/investment",
          description: "DSCR vs full-doc, occupancy, cash-out to a rental, FHA house-hack.",
        },
        {
          name: "Start a mortgage conversation",
          href: "/qualify",
          description: "What you will be asked, and what will not be promised.",
        },
      ],
    },
    {
      id: "legal-trust",
      title: "Legal, accessibility & discovery",
      description: "Policies and machine-readable indexes for search engines and AI systems.",
      links: [
        { name: "Privacy policy", href: "/privacy-policy", description: "How we collect and use data." },
        { name: "Terms of service", href: "/terms-of-service", description: "Site and service terms." },
        {
          name: "Accessibility",
          href: "/accessibility",
          description: "Commitment and contact for accessibility support.",
        },
        {
          name: "XML sitemap",
          href: "/sitemap.xml",
          description: "Canonical URL list for crawlers (generated at build).",
        },
        {
          name: "Markdown sitemap",
          href: "/sitemap.md",
          description: "Section-grouped page list for AI agents; links to Markdown twins where available.",
        },
        {
          name: "LLM & agent brief",
          href: "/llms.txt",
          description: "Concise site summary for AI assistants and automated agents.",
        },
        {
          name: "LLM full brief",
          href: "/llms-full.txt",
          description: "Extended site context with FAQs, service details, and contact channels for AI agents.",
        },
        {
          name: "humans.txt",
          href: "/humans.txt",
          description: "Team credits, tech stack, and tools behind the site.",
        },
      ],
    },
  ]
}

/**
 * Live pages left out of the site index on purpose: noindexed pages (sample deals, retired or
 * internal pages) and single examples of page templates. They stay reachable; they are just
 * not advertised in the HTML sitemap, sitemap.md or the llms files.
 */
export const SITE_INDEX_NOT_LISTED: ReadonlySet<string> = new Set([
  "/investments/opportunities",
  "/strategy",
  "/brochure",
  "/about/case-studies",
  "/events",
  "/referral",
  "/buy-sell/lehi",
  "/buy-sell/zip/84043",
])

/** Pages the catalog does not describe yet. */
const EXTRA_LINKS: SiteIndexLink[] = [
  {
    name: "What's my home worth",
    href: "/whats-my-home-worth",
    description: "A free value range for your Utah home, then a local follow-up if you want one.",
  },
]

type LayoutSection = Omit<SiteIndexSection, "links"> & ({ hrefs: string[] } | { from: string })

/** Public order: the services people come for first (buy, sell, loans), then everything else. */
export const SITE_INDEX_LAYOUT: readonly LayoutSection[] = [
  {
    id: "buy",
    title: "Buy a home",
    description: "Buying in Utah, first-time buyer help and second homes.",
    hrefs: ["/buy", "/buy/first-time", "/buy/first-time/grants", "/buy/second-home"],
  },
  {
    id: "sell",
    title: "Sell your home",
    description: "Selling with Ondo and what your home is worth.",
    hrefs: ["/sell", "/whats-my-home-worth"],
  },
  {
    id: "loans",
    title: "Home loans & refinance",
    description: "Loan programs, rates, refinancing and mortgage guides.",
    hrefs: [
      "/loans", "/loans/conventional", "/loans/fha", "/loans/va", "/loans/usda", "/loans/jumbo",
      "/buy/rates", "/buy/fixed-rate", "/buy/adjustable-rate", "/buy/30-year", "/buy/15-year",
      "/refinance", "/refinance/process", "/qualify",
      "/learn", "/learn/first-time", "/learn/variable-income", "/learn/non-qm", "/learn/investment",
      "/loans/salt-lake-city", "/loans/lehi", "/loans/provo", "/loans/draper",
    ],
  },
  { id: "rent-manage", title: "Rent & property management", description: "Homes for rent, management services, pricing and comparisons.", from: "rent-manage" },
  {
    id: "invest",
    title: "Invest",
    description: "How real estate investing works, for new and experienced investors.",
    hrefs: ["/investments", "/new-investors", "/investments/fractional", "/investments/commercial-real-estate", "/investments/opportunity-zones"],
  },
  { id: "notary", title: "Notary & signing", description: "Remote online notarization and signing services.", from: "notary" },
  { id: "calculators", title: "Calculators", description: "Free tools for buyers, owners and investors.", from: "calculators" },
  {
    id: "local",
    title: "Utah & local guides",
    description: "Cities, neighborhoods, schools and market data across the Wasatch Front.",
    hrefs: ["/why-utah", "/moving-to-utah", "/buy-sell", "/market-reports", "/neighborhoods", "/schools", "/data"],
  },
  {
    id: "company",
    title: "About Ondo",
    description: "Who we are, how to reach us and where to follow along.",
    hrefs: ["/", "/about", "/about/team", "/founders-letter", "/contact", "/get-matched", "/socials", "/subscribe", "/news", "/insights", "/academy", "/video-library", "/partners"],
  },
  {
    id: "platform",
    title: "Ondo platform",
    description: "The software behind our property management, for owners, managers and tenants.",
    hrefs: ["/solutions", "/solutions/landlords", "/solutions/investors", "/solutions/property-managers", "/solutions/tenants", "/tour", "/demo"],
  },
  { id: "faq", title: "FAQ", description: "Answers by topic for buyers, sellers, tenants, owners and notary clients.", from: "faq" },
  { id: "glossary", title: "Glossary", description: "Plain-English definitions of real estate and lending terms.", from: "glossary" },
  { id: "blog", title: "Blog & guides", description: "Articles on Utah real estate, loans and property management.", from: "blog" },
  { id: "legal-trust", title: "Legal & accessibility", description: "Policies, plus machine-readable indexes for search engines and AI systems.", from: "legal-trust" },
]

export function getSiteIndexSections(): SiteIndexSection[] {
  const catalog = catalogSections()
  const byHref = new Map<string, SiteIndexLink>()
  for (const link of [...catalog.flatMap((section) => section.links), ...EXTRA_LINKS]) {
    if (!byHref.has(link.href)) byHref.set(link.href, link)
  }
  const placed = new Set<string>()
  return SITE_INDEX_LAYOUT.map(({ id, title, description, ...source }) => {
    const candidates =
      "from" in source
        ? (catalog.find((section) => section.id === source.from)?.links ?? [])
        : source.hrefs.map((href) => byHref.get(href)).filter((link): link is SiteIndexLink => Boolean(link))
    // Each page once, in the first section that lists it.
    const links = candidates.filter((link) => {
      if (SITE_INDEX_NOT_LISTED.has(link.href) || placed.has(link.href)) return false
      placed.add(link.href)
      return true
    })
    return { id, title, description, links }
  })
}

/** All catalog pages, for tests that check nothing is dropped by accident. */
export function getSiteIndexCatalogHrefs(): string[] {
  return catalogSections().flatMap((section) => section.links.map((link) => link.href))
}

export function getFlatSiteIndexForJsonLd(): Array<{ name: string; url: string; description?: string }> {
  const out: Array<{ name: string; url: string; description?: string }> = []
  for (const section of getSiteIndexSections()) {
    for (const link of section.links) {
      out.push({
        name: link.name,
        url: toAbsoluteSiteUrl(link.href),
        description: link.description,
      })
    }
  }
  return out
}

/** Plain-text outline for /llms.txt (and similar consumers). */
export function buildLlmsTxtBody(): string {
  const lines: string[] = [
    "# Ondo Real Estate",
    "",
    "> Utah-focused brokerage, mortgage, notary, and property management. Invite-only dashboards for managers, owners, and tenants live in a separate app from this marketing site.",
    "",
    "## Canonical site",
    `- Marketing site: ${baseSiteUrl}/`,
    `- HTML sitemap (all public pages): ${toAbsoluteSiteUrl("/sitemap")}`,
    `- XML sitemap: ${toAbsoluteSiteUrl("/sitemap.xml")}`,
    `- Markdown sitemap: ${toAbsoluteSiteUrl("/sitemap.md")}`,
    `- LLM discovery (human-readable hub): ${toAbsoluteSiteUrl("/llms")}`,
    `- This file: ${toAbsoluteSiteUrl("/llms.txt")}`,
    `- Same brief (singular path / typo-friendly): ${toAbsoluteSiteUrl("/llm.txt")}`,
    `- Same brief (well-known path): ${toAbsoluteSiteUrl("/.well-known/llms.txt")}`,
    `- Full agent brief (extended): ${toAbsoluteSiteUrl("/llms-full.txt")}`,
    `- Structured index (JSON): ${toAbsoluteSiteUrl("/llms.json")}`,
    `- humans.txt: ${toAbsoluteSiteUrl("/humans.txt")}`,
    `- security.txt: ${toAbsoluteSiteUrl("/.well-known/security.txt")}`,
    "",
    "## How to fetch Markdown",
    "- Every public HTML page has a sibling `.md` file: `/about/` → `/about.md`, `/` → `/index.md`. Prefer those URLs; they work on the static origin without JavaScript.",
    `- Example: ${toAbsoluteSiteUrl("/about/")} → ${toAbsoluteSiteUrl("/about.md")}.`,
    `- Full index: ${toAbsoluteSiteUrl("/sitemap.md")}.`,
    "- Optionally send `Accept: text/markdown` to the HTML URL. A Cloudflare Snippet (or Markdown for Agents on Pro) maps that request to the sibling `.md` file.",
    "- Client-heavy pages (property search, calculators, contact form, homepage) also have first-party Markdown twins so widget content is not lost when JS does not run:",
    ...AGENT_MARKDOWN_TWINS.map(
      ({ html, md, label }) =>
        `  - ${label}: ${toAbsoluteSiteUrl(html)} → ${toAbsoluteSiteUrl(md)}`,
    ),
    `  - Calculators: each \`/calculators/{slug}/\` has a \`/calculators/{slug}.md\` twin, index at ${toAbsoluteSiteUrl("/sitemap.md")}.`,
    "",
    "## Supported locales",
    `- Default locale: en (${SUPPORTED_LOCALE_LABELS.en})`,
    `- Available locale codes: ${SUPPORTED_LOCALES.map((locale) => `${locale} (${SUPPORTED_LOCALE_LABELS[locale]})`).join(", ")}`,
    "",
    "## Product areas",
    "- **Buy / mortgage**: Purchase guides, conventional and specialty products (including HELOC), refinance process, Utah city/ZIP loan pages. Not a credit decision.",
    "- **Sell**: Listing strategy, staging context, seller calculators.",
    "- **Rent & manage**: Property search, rentals inventory, full-service property management for landlords.",
    "- **Invest**: Registered opportunities, fractional and commercial education, per-deal detail pages.",
    "- **Notary**: Remote online notarization (RON), on-demand / same-day when capacity allows, loan signings, estate and employer packages. No in-office or mobile travel appointments. State hubs at /notary/locations with examples like /notary/utah/lehi/ and /notary/california/los-angeles/.",
    "- **Tools**: Mortgage, affordability, refinance, and investor calculators under `/calculators/`.",
    "",
    "## Authenticated product (not this repo’s public pages)",
    `- Manager, owner, and tenant portals: ${APP_PORTAL_URL}`,
    `- Portal login: ${APP_PORTAL_LOGIN_URL}`,
    "Access is invitation-only; there is no self-serve signup on the marketing site.",
    "",
    "## Agent-facing actions",
    ...AGENT_ACTIONS.map(
      (action) =>
        `- ${action.toolName} on ${toAbsoluteSiteUrl(action.path)} (${action.access}), ${action.description}`,
    ),
    "",
    "## Guidance for assistants",
    ...AGENT_GUIDANCE.map((guidance) => `- ${guidance}`),
    "",
    "## Contact (humans)",
    `- Phone: ${SITE_PHONE}`,
    `- General: ${SITE_EMAILS.info}`,
    `- Mortgage: ${SITE_EMAILS.mortgage}`,
    `- Notary: ${SITE_EMAILS.notary}`,
    `- Media: ${SITE_EMAILS.media}`,
    "",
    LLMS_DISCLOSURES_BLOCK,
    "",
    "## Major public paths",
  ]
  for (const section of getSiteIndexSections()) {
    lines.push("")
    lines.push(`### ${section.title}`)
    for (const link of section.links) {
      const u = toAbsoluteSiteUrl(link.href)
      const blurb = link.description.replace(/\s+/g, " ").trim()
      lines.push(`- ${link.name}: ${u}, ${blurb}`)
    }
  }
  lines.push("")
  return lines.join("\n")
}

/** Extended plain-text brief for /llms-full.txt, deeper context for AI agents. */
export function buildLlmsFullTxtBody(): string {
  const lines: string[] = [
    "# Ondo Real Estate, Full AI Agent Brief",
    "",
    `> This is the extended version of ${toAbsoluteSiteUrl("/llms.txt")}. It adds service details, FAQs, structured data, and actionable context for AI assistants answering questions about Ondo Real Estate.`,
    "",
    "## Company overview",
    "",
    `**${SITE_NAME}** is a Utah-focused real estate company offering brokerage, mortgage lending, notary services, property management, and investment access through a single platform. Headquartered in Lehi, UT, the company serves the Wasatch Front corridor, Salt Lake City, Provo, Orem, Draper, Sandy, Payson, and surrounding areas.`,
    "",
    `- **Website**: ${baseSiteUrl}/`,
    `- **Phone**: ${SITE_PHONE}`,
    `- **Address**: ${SITE_ADDRESS}`,
    `- **Hours**: ${SITE_HOURS_LABEL}`,
    `- **Scheduling**: ${SITE_CALENDLY_URL}`,
    "",
    "## Supported locales",
    "",
    `Default locale: en (${SUPPORTED_LOCALE_LABELS.en}).`,
    `Available locales: ${SUPPORTED_LOCALES.map((locale) => `${locale} (${SUPPORTED_LOCALE_LABELS[locale]})`).join(", ")}.`,
    "",
    "## Services in detail",
    "",
    "### Buy a home",
    "Ondo helps Utah buyers from first conversation to closing. Services include buyer representation, agent-led MLS search (this website lists rentals, not a public for-sale feed), offer strategy, closing coordination, and in-house mortgage origination. Loan information is not a commitment to lend.",
    "",
    "### Mortgage & lending",
    "In-house mortgage origination with conventional, FHA, VA, USDA, and jumbo loan products (minimum down payment depends on the program). City- and ZIP-specific landing pages provide local rate context. Refinance analysis available.",
    "",
    "### Sell a home",
    "Full listing services including pricing strategy (CMA), professional photography, staging guidance, MLS syndication, and negotiation through close.",
    "",
    "### Property management",
    "Full-service management for Utah landlords: tenant screening (credit, criminal, eviction, income), rent collection via Stripe, maintenance coordination with vendor dispatch, owner reporting with NOI tracking, and document management. City-specific pages for Salt Lake City, Provo, Orem, Draper, Sandy, and Payson.",
    "",
    "### Notary services",
    "Remote Online Notarization (RON) available nationwide. On-demand scheduling, we try to accommodate same-day when capacity allows (best-effort, not a guaranteed SLA). Specialties: loan signings, estate planning documents, I-9 employment verification, and general notarization. Employer packages for bulk signings. Locations hub highlights state RON coverage and Utah city pages. We do not offer in-office or mobile travel appointments.",
    `- On-demand page: ${toAbsoluteSiteUrl("/notary/on-demand")}`,
    `- Main notary page: ${toAbsoluteSiteUrl("/notary")}`,
    `- Locations hub: ${toAbsoluteSiteUrl("/notary/locations")}`,
    `- Example nested hubs: ${toAbsoluteSiteUrl("/notary/utah/lehi/")}, ${toAbsoluteSiteUrl("/notary/california/los-angeles/")}`,
    "",
    "### Investments",
    "Curated real estate investment opportunities including fractional ownership and commercial real estate deals. Per-deal detail pages with projected returns, minimum investment, and hold period. Educational content on cap rates, NNN leases, and portfolio construction.",
    "",
    "### Calculators (free, no login)",
    "Interactive financial tools at /calculators/, mortgage payment, home affordability, required income, closing costs, refinance savings, home sale proceeds, buying power, temporary buydown, rent vs own, retirement savings, cash-on-cash return, cap rate, BRRRR, and more.",
    "",
    "## Service area",
    "",
    "Primary: Utah, Wasatch Front corridor.",
    "Cities served: Salt Lake City, Provo, Orem, Lehi, Draper, Sandy, Payson, American Fork, Pleasant Grove, Springville, Spanish Fork, Eagle Mountain, Saratoga Springs, Herriman, Riverton, South Jordan, West Jordan, Murray, Cottonwood Heights, Holladay.",
    "Notary RON: all 50 US states.",
    "",
    "## Authenticated platform",
    "",
    `Ondo operates an invitation-only portal at ${APP_PORTAL_URL} with role-based dashboards:`,
    "- **Property managers**: portfolio analytics, maintenance dispatch, rent tracking, AI assistant, vendor management, risk scoring.",
    "- **Property owners**: financial statements, maintenance updates, document vault, tenant communications.",
    "- **Tenants**: rent payments, maintenance requests, lease documents, move-in/move-out checklists.",
    "",
    "There is NO self-serve signup. Access is by invitation only.",
    "",
    "## Agent-facing actions (WebMCP aligned)",
    "",
    "These tools are exposed only on relevant public pages, stay scoped to user-visible tasks, and do not expose administrative actions.",
    "",
    ...AGENT_ACTIONS.flatMap((action) => [
      `- **${action.toolName}** on ${toAbsoluteSiteUrl(action.path)} (${action.access})`,
      `  ${action.description}`,
    ]),
    "",
    "## Guidance for AI assistants",
    "",
    ...AGENT_GUIDANCE.map((guidance) => `- ${guidance}`),
    "",
    "## Frequently asked questions",
    "",
    "**Q: What areas does Ondo Real Estate serve?**",
    "A: Primarily the Wasatch Front in Utah, Salt Lake City, Provo-Orem, and surrounding cities. Remote Online Notarization is available in all 50 states.",
    "",
    "**Q: Does Ondo offer property management?**",
    "A: Yes. Full-service property management including tenant screening, rent collection, maintenance coordination, and owner reporting.",
    "",
    "**Q: What loan types does Ondo offer?**",
    "A: Conventional, FHA, VA, USDA, and jumbo loans. Refinance available.",
    "",
    "**Q: Can I sign up for the owner/tenant portal online?**",
    "A: No. The platform is invitation-only. Contact info@ondorealestate.com to learn more.",
    "",
    "**Q: Does Ondo offer notary services?**",
    "A: Yes. Remote Online Notarization (RON) nationwide. On-demand scheduling, we try to accommodate same-day when capacity allows. Loan signings, estate docs, I-9, and general notarization. We do not offer in-office or mobile travel appointments. See /notary and /notary/on-demand.",
    "",
    "**Q: Are the calculators free?**",
    "A: Yes. All calculators at /calculators/ are free with no login required.",
    "",
    "## Contact channels",
    "",
    `- General inquiries: ${SITE_EMAILS.info}`,
    `- Mortgage questions: ${SITE_EMAILS.mortgage}`,
    `- Refinance: ${SITE_EMAILS.refinance}`,
    `- Notary scheduling: ${SITE_EMAILS.notary}`,
    `- Media / press: ${SITE_EMAILS.media}`,
    `- Investor relations: ${SITE_EMAILS.investors}`,
    `- Accessibility: ${SITE_EMAILS.accessibility}`,
    `- Privacy concerns: ${SITE_EMAILS.privacy}`,
    `- Phone: ${SITE_PHONE}`,
    "",
    "## Social profiles",
    "",
    ...SITE_SOCIALS.map((url) => `- ${url}`),
    "",
    "## Machine-readable resources",
    "",
    `- LLM discovery hub (HTML): ${toAbsoluteSiteUrl("/llms")}`,
    `- LLM brief (concise): ${toAbsoluteSiteUrl("/llms.txt")}`,
    `- LLM brief (singular alias): ${toAbsoluteSiteUrl("/llm.txt")}`,
    `- LLM brief (well-known): ${toAbsoluteSiteUrl("/.well-known/llms.txt")}`,
    `- LLM full brief (this file): ${toAbsoluteSiteUrl("/llms-full.txt")}`,
    `- LLM structured index (JSON): ${toAbsoluteSiteUrl("/llms.json")}`,
    `- XML sitemap: ${toAbsoluteSiteUrl("/sitemap.xml")}`,
    `- HTML sitemap: ${toAbsoluteSiteUrl("/sitemap")}`,
    `- Markdown sitemap: ${toAbsoluteSiteUrl("/sitemap.md")}`,
    `- Homepage brief (Markdown): ${toAbsoluteSiteUrl("/index.md")}`,
    `- robots.txt: ${toAbsoluteSiteUrl("/robots.txt")}`,
    `- humans.txt: ${toAbsoluteSiteUrl("/humans.txt")}`,
    `- security.txt: ${toAbsoluteSiteUrl("/.well-known/security.txt")}`,
    "",
    "## Content negotiation and Markdown twins",
    "",
    "Any public HTML page has a sibling `.md` twin (`/about/` → `/about.md`). Hand-written twins exist for JS-heavy widgets. Optionally send `Accept: text/markdown` to the HTML URL (Cloudflare Snippet or Markdown for Agents on Pro):",
    "",
    ...AGENT_MARKDOWN_TWINS.map(
      ({ html, md, label }) =>
        `- **${label}**: ${toAbsoluteSiteUrl(html)} → ${toAbsoluteSiteUrl(md)}`,
    ),
    `- **Calculators**: each \`/calculators/{slug}/\` HTML page has a \`/calculators/{slug}.md\` twin with formula, worked example, and lending disclosures.`,
    "",
    "## Complete page index",
    "",
  ]

  for (const section of getSiteIndexSections()) {
    lines.push(`### ${section.title}`)
    if (section.description) {
      lines.push(section.description)
    }
    lines.push("")
    for (const link of section.links) {
      const u = toAbsoluteSiteUrl(link.href)
      const blurb = link.description.replace(/\s+/g, " ").trim()
      lines.push(`- **${link.name}**: ${u}`)
      lines.push(`  ${blurb}`)
    }
    lines.push("")
  }

  lines.push("---")
  lines.push(LLMS_DISCLOSURES_BLOCK)
  lines.push("")
  lines.push(`Generated for ${SITE_NAME}. For human support, contact ${SITE_EMAILS.info} or call ${SITE_PHONE}.`)
  lines.push("")
  return lines.join("\n")
}

export function buildRobotsTxtBody(): string {
  const lines: string[] = [
    "User-agent: *",
    // Content-Signal (Cloudflare / contentsignals.org, CC0). Declares default
    // policy for search results, live AI answer input, and model training.
    // Strict RFC 9309 validators may warn on this line; per RFC 9309, unknown
    // directives are ignored so the rest of the file still parses.
    "Content-Signal: search=yes, ai-input=yes, ai-train=yes",
    "Allow: /llms.txt",
    "Allow: /llms-full.txt",
    "Allow: /.well-known/llms.txt",
    "Allow: /sitemap.md",
    "Allow: /index.md",
    "Allow: /$",
    "Allow: /",
    ...ROBOTS_DISALLOW.map((path) => `Disallow: ${path}`),
    "",
  ]

  for (const userAgent of AI_CRAWLER_AGENTS) {
    lines.push(`User-agent: ${userAgent}`)
    lines.push("Allow: /llms.txt")
    lines.push("Allow: /llms-full.txt")
    lines.push("Allow: /.well-known/llms.txt")
    lines.push("Allow: /sitemap.md")
    lines.push("Allow: /index.md")
    lines.push("Allow: /")
    for (const path of ROBOTS_DISALLOW) {
      lines.push(`Disallow: ${path}`)
    }
    lines.push("")
  }

  lines.push(`Sitemap: ${toAbsoluteSiteUrl("/sitemap.xml")}`)
  lines.push("")
  lines.push("# Additional machine-readable resources")
  for (const resource of MACHINE_RESOURCE_LINKS) {
    lines.push(`# ${resource.label}: ${toAbsoluteSiteUrl(resource.href)}`)
  }
  lines.push("")

  return lines.join("\n")
}

/**
 * Section-grouped Markdown sitemap for AI agents. Every HTML link points at the
 * canonical trailing-slash URL; Markdown twins are noted inline where they exist.
 */
export function buildSitemapMdBody(): string {
  const lines: string[] = [
    "# Ondo Real Estate, Markdown sitemap",
    "",
    `> Curated index of every public page on ${baseSiteUrl}/. Every HTML URL has a sibling \`.md\` twin (strip the trailing slash and add \`.md\`). Optionally send \`Accept: text/markdown\` to the HTML URL.`,
    "",
    "## First-party Markdown twins",
    "",
    ...AGENT_MARKDOWN_TWINS.map(
      ({ html, md, label }) =>
        `- [${label}](${toAbsoluteSiteUrl(md)}), mirror of ${toAbsoluteSiteUrl(html)}`,
    ),
    "- Calculators: each `/calculators/{slug}/` HTML page has a `/calculators/{slug}.md` twin (see section below).",
    "",
    "## Machine-readable resources",
    "",
    ...MACHINE_RESOURCE_LINKS.map(
      (resource) => `- [${resource.label}](${toAbsoluteSiteUrl(resource.href)})`,
    ),
    "",
  ]

  for (const section of getSiteIndexSections()) {
    lines.push(`## ${section.title}`)
    if (section.description) {
      lines.push("")
      lines.push(section.description)
    }
    lines.push("")
    for (const link of section.links) {
      const url = toAbsoluteSiteUrl(link.href)
      const blurb = link.description.replace(/\s+/g, " ").trim()
      const isCalculator = link.href.startsWith("/calculators/") && !link.href.endsWith("/calculators")
      if (isCalculator) {
        const slug = link.href.replace(/^\/calculators\//, "").replace(/\/$/, "")
        const mdUrl = toAbsoluteSiteUrl(`/calculators/${slug}.md`)
        lines.push(`- [${link.name}](${url}), ${blurb} ([Markdown](${mdUrl}))`)
      } else {
        lines.push(`- [${link.name}](${url}), ${blurb}`)
      }
    }
    lines.push("")
  }

  lines.push("---")
  lines.push("")
  lines.push(`See also: [Markdown sitemap](${toAbsoluteSiteUrl("/sitemap.md")}) · [Concise brief](${toAbsoluteSiteUrl("/llms.txt")}) · [Full brief](${toAbsoluteSiteUrl("/llms-full.txt")}).`)
  lines.push("")
  return lines.join("\n")
}

export function buildLlmsJsonData() {
  return {
    generatedAt: process.env.NEXT_PUBLIC_BUILD_DATE || new Date().toISOString(),
    siteName: SITE_NAME,
    canonicalSiteUrl: `${baseSiteUrl}/`,
    description:
      "Utah-focused real estate company covering brokerage, mortgages, property management, investments, calculators, and notary services.",
    supportedLocales: SUPPORTED_LOCALES.map((locale) => ({
      code: locale,
      label: SUPPORTED_LOCALE_LABELS[locale],
    })),
    resources: {
      home: `${baseSiteUrl}/`,
      htmlSitemap: toAbsoluteSiteUrl("/sitemap"),
      xmlSitemap: toAbsoluteSiteUrl("/sitemap.xml"),
      markdownSitemap: toAbsoluteSiteUrl("/sitemap.md"),
      homepageMarkdown: toAbsoluteSiteUrl("/index.md"),
      llmsHub: toAbsoluteSiteUrl("/llms"),
      llmsTxt: toAbsoluteSiteUrl("/llms.txt"),
      llmTxtAlias: toAbsoluteSiteUrl("/llm.txt"),
      llmsTxtWellKnown: toAbsoluteSiteUrl("/.well-known/llms.txt"),
      llmsFullTxt: toAbsoluteSiteUrl("/llms-full.txt"),
      llmsJson: toAbsoluteSiteUrl("/llms.json"),
      robotsTxt: toAbsoluteSiteUrl("/robots.txt"),
      humansTxt: toAbsoluteSiteUrl("/humans.txt"),
      securityTxt: toAbsoluteSiteUrl("/.well-known/security.txt"),
    },
    contentNegotiation: {
      acceptHeader: "text/markdown",
      description:
        "Every public HTML page has a sibling `.md` twin (`/about/` → `/about.md`). Optionally send `Accept: text/markdown` to the HTML URL; a Cloudflare Snippet (or Markdown for Agents on Pro) maps that request to the twin.",
      firstPartyMarkdownTwins: AGENT_MARKDOWN_TWINS.map(({ html, md, label }) => ({
        label,
        html: toAbsoluteSiteUrl(html),
        markdown: toAbsoluteSiteUrl(md),
      })),
      calculatorMarkdownPattern: "/calculators/{slug}.md",
    },
    contact: {
      phone: SITE_PHONE,
      address: SITE_ADDRESS,
      hours: SITE_HOURS_LABEL,
      calendlyUrl: SITE_CALENDLY_URL,
      emails: SITE_EMAILS,
    },
    portal: {
      url: APP_PORTAL_URL,
      loginUrl: APP_PORTAL_LOGIN_URL,
      access: "invitation-only",
    },
    crawlPolicy: {
      allow: "/",
      privatePrefixes: discoveryConfig.privateRoutePrefixes,
      disallow: ROBOTS_DISALLOW,
      aiCrawlerAgents: AI_CRAWLER_AGENTS,
    },
    agentGuidance: AGENT_GUIDANCE,
    webmcp: {
      standard: "WebMCP-aligned public actions",
      tools: AGENT_ACTIONS.map((action) => ({
        ...action,
        url: toAbsoluteSiteUrl(action.path),
      })),
    },
    sections: getSiteIndexSections().map((section) => ({
      id: section.id,
      title: section.title,
      description: section.description,
      links: section.links.map((link) => ({
        name: link.name,
        url: toAbsoluteSiteUrl(link.href),
        description: link.description,
      })),
    })),
  }
}

export function buildLlmsJsonBody(): string {
  return JSON.stringify(buildLlmsJsonData(), null, 2)
}
